/** IPA transcriptions for every Business and Academic Communication Lab takeaway phrase. */
const COMMUNICATION_PHRASE_IPA: Record<string, string> = {
  "action item": "/æˈkʃʌn aɪˈtʌm/",
  "actionable advice": "/æˈkʃʌnʌbʌl ædvaɪˈs/",
  "agree on next steps": "/ʌgriˈ ɑˈn nɛˈkst stɛˈps/",
  "agree to disagree": "/ʌgriˈ tə dɪsʌgriˈ/",
  "area for improvement": "/ɛˈriʌ fər ɪmpruˈvmʌnt/",
  "as per our conversation": "/æˈz pɚˈ aʊər kɑˌnvɚseɪˈʃʌn/",
  "async": "/eɪˈsɪŋk/",
  "automate": "/ɔˈtʌmeɪˌt/",
  "back up a claim": "/bæˈk ʌp ə kleɪˈm/",
  "back up with evidence": "/bæˈk ʌp wɪˈð ɛˈvʌdʌns/",
  "ballpark figure": "/bɔˈlpɑˌrk fɪˈgɪɚ/",
  "bear with me": "/bɛˈr wɪˈð miˈ/",
  "bias in data": "/baɪˈʌs ɪn deɪˈtʌ/",
  "bottom line": "/bɑˈtʌm laɪˈn/",
  "bounce back": "/bawˈns bæˈk/",
  "break a leg": "/breɪˈk ə lɛˈg/",
  "break it down": "/breɪˈk ɪˈt dawˈn/",
  "break the ice": "/breɪˈk ðə aɪˈs/",
  "bring to the table": "/brɪˈŋ tə ðə teɪˈbʌl/",
  "brown-noser": "/braʊn ˈnoʊzər/",
  "buddy system": "/bʌˈdi sɪˈstʌm/",
  "build on": "/bɪˈld ɑˈn/",
  "burn bridges": "/bɚˈn brɪˈʤʌz/",
  "burn rate": "/bɚˈn reɪˈt/",
  "burned out": "/bɚˈnd awˈt/",
  "carbon footprint": "/kɑˈrbʌn fʊˈtprɪˌnt/",
  "career path": "/kɚɪˈr pæˈθ/",
  "check in on progress": "/tʃek ɪn ɑˈn prɑˈgrɛˌs/",
  "check-in": "/tʃek ɪn/",
  "circle back": "/sɚˈkʌl bæˈk/",
  "cite a source": "/saɪˈt ə sɔˈrs/",
  "clarify a point": "/klɛˈrʌfaɪˌ ə pɔɪˈnt/",
  "clear the air": "/klɪˈr ðə ɛˈr/",
  "clickbait": "/ˈklɪkbeɪt/",
  "cold email": "/kowˈld imeɪˈl/",
  "comfort zone": "/kʌˈmfɚt zowˈn/",
  "community impact": "/kʌmɪuˈnʌti ɪmpæˈkt/",
  "concede a point": "/kʌnsiˈd ə pɔɪˈnt/",
  "confirmation bias": "/kɑˌnfɚmeɪˈʃʌn baɪˈʌs/",
  "constructive feedback": "/kʌnstrʌˈktɪv fiˈdbæˌk/",
  "corporate ladder": "/kɔˈrpɚʌt læˈdɚ/",
  "counter-offer": "/ˈkaʊntər ˈɔːfər/",
  "counterargument": "/ˈkaʊntərˌɑːrɡjəmənt/",
  "cover letter": "/kʌˈvɚ lɛˈtɚ/",
  "cram": "/kræˈm/",
  "cross-check": "/krɔːs tʃek/",
  "cultural norm": "/kʌˈlʧɚʌl nɔˈrm/",
  "culture shock": "/kʌˈlʧɚ ʃɑˈk/",
  "cut to the chase": "/kʌˈt tə ðə ʧeɪˈs/",
  "cutting-edge": "/ˈkʌtɪŋ edʒ/",
  "deadline": "/dɛˈdlaɪˌn/",
  "deal-breaker": "/diːl ˈbreɪkər/",
  "deep work": "/diˈp wɚˈk/",
  "delegate": "/dɛˈlʌgeɪˌt/",
  "deliverable": "/dɪlɪˈvɚʌbʌl/",
  "devil's advocate": "/dɛˈvʌlz æˈdvʌkʌt/",
  "digital divide": "/dɪˈʤʌtʌl dɪvaɪˈd/",
  "disruptive technology": "/dɪsrʌˈptɪv tɛknɑˈlʌʤi/",
  "divide the workload": "/dɪvaɪˈd ðə wɚˈklowˌd/",
  "document the issue": "/dɑˈkɪʌmɛnt ðə ɪˈʃu/",
  "double-edged sword": "/ˈdʌbəl edʒd sɔˈrd/",
  "draft": "/dræˈft/",
  "draw the line": "/drɔˈ ðə laɪˈn/",
  "dress code": "/drɛˈs kowˈd/",
  "drop a class": "/drɑˈp ə klæˈs/",
  "drop off the call": "/drɑˈp ɔːf ðə kɔˈl/",
  "drop the ball": "/drɑˈp ðə bɔːl/",
  "early adopter": "/ɚˈli ʌdɑˈptɚ/",
  "echo chamber": "/ɛˈkow ʧeɪˈmbɚ/",
  "empower": "/ɪmpawˈɚ/",
  "EOD": "/ˌiː.oʊˈdiː/",
  "escalate": "/ɛˈskʌleɪˌt/",
  "escalate a case": "/ɛˈskʌleɪˌt ə keɪˈs/",
  "exit interview": "/ɛˈgzɪt ɪˈntɚvɪuˌ/",
  "fact-check": "/fækt tʃek/",
  "fake news": "/feɪˈk nuˈz/",
  "field questions": "/fiˈld kwɛˈsʧʌnz/",
  "figure out": "/fɪˈgɪɚ awˈt/",
  "find your calling": "/faɪˈnd jər kɔˈlɪŋ/",
  "fit in": "/fɪˈt ɪn/",
  "follow through": "/ˈfɑːloʊ θruˈ/",
  "follow up": "/ˈfɑːloʊ ʌp/",
  "follow up on": "/ˈfɑːloʊ ʌp ɑˈn/",
  "follow-up": "/ˈfɑːloʊ ʌp/",
  "food for thought": "/fuˈd fər θɔˈt/",
  "foot in the door": "/fʊˈt ɪn ðə dɔːr/",
  "future-proof": "/ˈfjuːtʃər pruːf/",
  "game changer": "/geɪˈm ʧeɪˈnʤɚ/",
  "gap year": "/gæˈp ɪɪˈr/",
  "geopolitics": "/ʤiˌowpɑˈlʌtɪks/",
  "get back to you": "/gɛˈt bæˈk tə ɪuˈ/",
  "get up to speed": "/gɛˈt ʌp tə spiˈd/",
  "give back": "/gɪˈv bæˈk/",
  "give notice": "/gɪˈv nowˈtʌs/",
  "give the floor to": "/gɪˈv ðə flɔˈr tə/",
  "go green": "/ɡoʊ griˈn/",
  "go the extra mile": "/ɡoʊ ðə ɛˈkstrʌ maɪˈl/",
  "go-getter": "/ɡoʊ ˈɡetər/",
  "GPA": "/ˌdʒiː.piːˈeɪ/",
  "grassroots": "/græˈsruˈts/",
  "grassroots movement": "/græˈsruˈts muˈvmʌnt/",
  "greenwashing": "/ˈɡriːnwɑːʃɪŋ/",
  "growth mindset": "/growˈθ maɪˈndsɛˌt/",
  "hand over": "/hæˈnd owˈvɚ/",
  "handle objections": "/hæˈndʌl ʌbʤɛˈkʃʌnz/",
  "heads up": "/hɛˈdz ʌp/",
  "hedge a claim": "/hɛˈʤ ə kleɪˈm/",
  "hit the books": "/hɪˈt ðə bʊˈks/",
  "hit the ground running": "/hɪˈt ðə grawˈnd rʌˈnɪŋ/",
  "hold water": "/howˈld wɔˈtɚ/",
  "human oversight": "/hɪuˈmʌn owˈvɚsaɪˌt/",
  "humanitarian crisis": "/hɪuˌmæˌnʌtɛˈriʌn kraɪˈsʌs/",
  "hustle": "/hʌˈsʌl/",
  "in a nutshell": "/ɪn ə nʌˈtʃɛˌl/",
  "in my humble opinion": "/ɪn maɪˈ hʌˈmbʌl ʌpɪˈnɪʌn/",
  "invoice": "/ɪˈnvɔɪs/",
  "keep your options open": "/kiˈp jər ɑˈpʃʌnz ˈoʊpən/",
  "key takeaway": "/kiˈ ˈteɪkəweɪ/",
  "land a job": "/læˈnd ə ʤɑˈb/",
  "lead by example": "/lɛˈd baɪˈ ɪgzæˈmpʌl/",
  "learn the ropes": "/lɚˈn ðə rowˈps/",
  "lend a hand": "/lɛˈnd ə hæˈnd/",
  "level up": "/lɛˈvʌl ʌp/",
  "literature review": "/lɪˈtɚʌʧɚ riˌvɪuˈ/",
  "log off": "/lɔˈg ɔːf/",
  "loop someone in": "/luˈp sʌˈmwʌˌn ɪn/",
  "lost in translation": "/lɔˈst ɪn trænzleɪˈʃʌn/",
  "low-ball": "/loʊ bɔːl/",
  "make a difference": "/meɪˈk ə dɪˈfɚʌns/",
  "make it right": "/meɪˈk ɪˈt raɪˈt/",
  "market rate": "/ˈmɑːrkɪt reɪˈt/",
  "meet someone halfway": "/miˈt sʌˈmwʌˌn hæˈfweɪˈ/",
  "melting pot": "/mɛˈltɪŋ pɑˈt/",
  "moat": "/mowˈt/",
  "move on": "/muˈv ɑˈn/",
  "nail the interview": "/neɪˈl ðə ɪˈntɚvɪuˌ/",
  "nail the talk": "/neɪˈl ðə tɔˈk/",
  "narrow down": "/nɛˈrow dawˈn/",
  "network": "/nɛˈtwɚˌk/",
  "on the other hand": "/ɑˈn ðə ʌˈðɚ hæˈnd/",
  "on the same page": "/ɑˈn ðə seɪˈm peɪˈʤ/",
  "onboarding": "/ˈɑːnbɔːrdɪŋ/",
  "open-door policy": "/ˈoʊpən dɔːr pɑˈlʌsi/",
  "paraphrase": "/pɛˈrʌfreɪˌz/",
  "pause for emphasis": "/pɔˈz fər ɛˈmfʌsʌs/",
  "pay it forward": "/peɪˈ ɪˈt fɔˈrwɚd/",
  "peer feedback": "/pɪr fiˈdbæˌk/",
  "peer review": "/pɪr riˌvɪuˈ/",
  "peer-reviewed": "/pɪr rɪˈvjuːd/",
  "pick someone's brain": "/pɪˈk ˈsʌmwʌnz breɪˈn/",
  "pilot": "/paɪˈlʌt/",
  "plagiarism": "/pleɪˈʤɚɪˌzʌm/",
  "play devil's advocate": "/pleɪˈ dɛˈvʌlz æˈdvʌkʌt/",
  "play it safe": "/pleɪˈ ɪˈt seɪˈf/",
  "policy maker": "/pɑˈlʌsi meɪˈkɚ/",
  "polish": "/pɑˈlɪʃ/",
  "primary source": "/praɪˈmɛˌri sɔˈrs/",
  "product-market fit": "/ˈprɑːdʌkt ˈmɑːrkɪt fɪˈt/",
  "pull an all-nighter": "/pʊˈl ən ɔːl ˈnaɪtər/",
  "pull your weight": "/pʊˈl jər weɪˈt/",
  "put in a good word": "/pʊˈt ɪn ə gʊˈd wɚˈd/",
  "raise a point": "/reɪˈz ə pɔɪˈnt/",
  "raise the bar": "/reɪˈz ðə bɑˈr/",
  "reach out": "/riˈʧ awˈt/",
  "read the room": "/rɛˈd ðə ruˈm/",
  "reference letter": "/rɛˈfɚʌns lɛˈtɚ/",
  "research question": "/risɚˈʧ kwɛˈsʧʌn/",
  "retainer": "/rɪteɪˈnɚ/",
  "ROI": "/ˌɑːr.oʊˈaɪ/",
  "rub the wrong way": "/rʌˈb ðə rɔˈŋ weɪˈ/",
  "run through": "/rʌˈn θruˈ/",
  "runway": "/rʌˈnweɪˌ/",
  "scalable": "/ˈskeɪləbəl/",
  "scale up": "/skeɪˈl ʌp/",
  "scope creep": "/skowˈp kriˈp/",
  "see eye to eye": "/siˈ aɪˈ tə aɪˈ/",
  "seek support": "/siˈk sʌpɔˈrt/",
  "self-care": "/self ker/",
  "set a goal": "/sɛˈt ə gowˈl/",
  "set boundaries": "/sɛˈt bawˈndɚiz/",
  "set expectations": "/sɛˈt ɛˌkspɛkteɪˈʃʌnz/",
  "shadow someone": "/ʃæˈdowˌ sʌˈmwʌˌn/",
  "share your screen": "/ʃɛˈr jər skriˈn/",
  "shortlist": "/ˈʃɔːrtlɪst/",
  "show the ropes": "/ʃowˈ ðə rowˈps/",
  "sign up for": "/saɪˈn ʌp fər/",
  "signpost": "/saɪˈnpowˌst/",
  "signpost the structure": "/saɪˈnpowˌst ðə strʌˈkʧɚ/",
  "signposting language": "/ˈsaɪnpoʊstɪŋ læˈŋgwʌʤ/",
  "single-use": "/ˈsɪŋɡəl juːs/",
  "sort out": "/sɔˈrt awˈt/",
  "speak up": "/spiˈk ʌp/",
  "split tasks": "/splɪˈt tæˈsks/",
  "stage fright": "/steɪˈʤ fraɪˈt/",
  "statement of work": "/steɪˈtmʌnt əv wɚˈk/",
  "stay professional": "/steɪˈ prʌfɛˈʃʌnʌl/",
  "step up": "/stɛˈp ʌp/",
  "stereotype": "/stɛˈriʌtaɪˌp/",
  "strawman argument": "/ˈstrɔːmæn ɑˈrgɪʌmʌnt/",
  "sustainable": "/sʌsteɪˈnʌbʌl/",
  "sweeten the deal": "/swiˈtʌn ðə diːl/",
  "table a discussion": "/teɪˈbʌl ə dɪskʌˈʃʌn/",
  "tailor (your resume)": "/teɪˈlɚ jər rɪzuˈm/",
  "take a step back": "/teɪˈk ə stɛˈp bæˈk/",
  "take away": "/teɪˈk əˈweɪ/",
  "take ownership": "/teɪˈk owˈnɚʃɪˌp/",
  "take something with a grain of salt": "/teɪˈk sʌˈmθɪŋ wɪˈð ə greɪˈn əv sɔˈlt/",
  "take the floor": "/teɪˈk ðə flɔˈr/",
  "the ball is in your court": "/ðə bɔːl ɪˈz ɪn jər kɔˈrt/",
  "the bigger picture": "/ðə bɪˈgɚ pɪˈkʧɚ/",
  "the elephant in the room": "/ðə ɛˈlʌfʌnt ɪn ðə ruˈm/",
  "thesis statement": "/θiˈsʌs steɪˈtmʌnt/",
  "time zone": "/taɪˈm zowˈn/",
  "to elaborate": "/tə ɪlæˈbrʌt/",
  "topic sentence": "/tɑˈpɪk sɛˈntʌns/",
  "total package": "/towˈtʌl pæˈkʌʤ/",
  "touch base": "/tʌˈʧ beɪˈs/",
  "traction": "/træˈkʃʌn/",
  "trade-off": "/treɪd ɔːf/",
  "transferable skills": "/trænsfɚˈʌbʌl skɪˈlz/",
  "two weeks' notice": "/tuˈ wiˈks nowˈtʌs/",
  "use case": "/juːs keɪˈs/",
  "value proposition": "/væˈlɪu prɑˌpʌzɪˈʃʌn/",
  "vent": "/vɛˈnt/",
  "walk through": "/wɔːk θruˈ/",
  "walk-away point": "/wɔːk əˈweɪ pɔɪˈnt/",
  "warm introduction": "/wɔˈrm ɪˌntrʌdʌˈkʃʌn/",
  "warm up": "/wɔˈrm ʌp/",
  "water cooler talk": "/wɔˈtɚ kuˈlɚ tɔˈk/",
  "when in Rome, do as the Romans do": "/wɛˈn ɪn rowˈm duˈ æˈz ðə rowˈmʌnz duˈ/",
  "win-win": "/wɪn wɪn/",
  "wrap up": "/ræˈp ʌp/",
  "you're on mute": "/jʊr ɑˈn mɪuˈt/",
};

export const getCommunicationPhraseIpa = (term: string): string =>
  COMMUNICATION_PHRASE_IPA[term] ?? "";
