/**
 * IPA transcriptions for every Business and Academic English lesson phrase.
 * Generated from the CMU Pronouncing Dictionary and reviewed supplements.
 */
const PURPOSE_PHRASE_IPA: Record<string, string> = {
  "Best regards": "/best rɪɡˈɑːrdz/",
  "Can everyone hear me?": "/kæn ˈevriwˌʌn hiːr miː/",
  "Could I speak to": "/kʊd aɪ spiːk tuː/",
  "Could you clarify": "/kʊd juː klˈerəfˌaɪ/",
  "Could you please": "/kʊd juː pliːz/",
  "DOI": "/dɔɪ/",
  "Do let me know if": "/duː let miː noʊ ɪf/",
  "Do you have any questions for us?": "/duː juː hæv ˈeni kwˈestʃənz fɔːr ʌs/",
  "Does that answer your question?": "/dʌz ðæt ˈænsər jɔːr kwˈestʃən/",
  "Go ahead": "/ɡoʊ əhˈed/",
  "How are things at your end?": "/haʊ ɑːr θɪŋz æt jɔːr end/",
  "How does that look from ...?": "/haʊ dʌz ðæt lʊk frʌm/",
  "How was your trip?": "/haʊ wɑːz jɔːr trɪp/",
  "How would this apply to": "/haʊ wʊd ðɪs əplˈaɪ tuː/",
  "I am not sure I agree": "/aɪ æm nɑːt ʃʊr aɪ əɡrˈiː/",
  "I am writing to": "/aɪ æm rˈaɪtɪŋ tuː/",
  "I am writing to apply for": "/aɪ æm rˈaɪtɪŋ tuː əplˈaɪ fɔːr/",
  "I apologise for": "/aɪ əpˈɑːlədʒˌaɪz fɔːr/",
  "I bring": "/aɪ brɪŋ/",
  "I help ... to ...": "/aɪ help tuː/",
  "I recommend that we": "/aɪ rˌekəmˈend ðæt wiː/",
  "I see your point, but": "/aɪ siː jɔːr pɔɪnt bʌt/",
  "I would appreciate it if": "/aɪ wʊd əprˈiːʃiˌeɪt ɪt ɪf/",
  "I would welcome the chance to": "/aɪ wʊd wˈelkəm ðə tʃæns tuː/",
  "If you ..., we can ...": "/ɪf juː wiː kæn/",
  "Is this your first time in": "/ɪz ðɪs jɔːr fɜːrst taɪm ɪn/",
  "It can be seen that": "/ɪt kæn biː siːn ðæt/",
  "It was a pleasure meeting you": "/ɪt wɑːz ə plˈeʒər mˈiːtɪŋ juː/",
  "Let us turn to": "/let ʌs tɜːrn tuː/",
  "Shall we make a start?": "/ʃæl wiː meɪk ə stɑːrt/",
  "Tell me about a time when": "/tel miː əbˈaʊt ə taɪm wen/",
  "Thank you for your time": "/θæŋk juː fɔːr jɔːr taɪm/",
  "Thanks in advance": "/θæŋks ɪn ədvˈæns/",
  "That brings me to": "/ðæt brɪŋz miː tuː/",
  "That is a good question": "/ðæt ɪz ə ɡʊd kwˈestʃən/",
  "There is evidence that": "/ðer ɪz ˈevədəns ðæt/",
  "This is ... speaking": "/ðɪs ɪz spˈiːkɪŋ/",
  "This paper argues that": "/ðɪs pˈeɪpər ˈɑːrɡjuz ðæt/",
  "Today I will show": "/tədˈeɪ aɪ wɪl ʃoʊ/",
  "What evidence supports": "/wʌt ˈevədəns səpˈɔːrts/",
  "Would ... suit you?": "/wʊd suːt juː/",
  "Would you mind + V-ing": "/wʊd juː maɪnd viːɪŋ/",
  "You are on mute": "/juː ɑːr ɑːn mjuːt/",
  "Yours sincerely": "/jʊrz sɪnsˈɪrli/",
  "a minority": "/ə maɪnˈɔːrəti/",
  "a quick favour": "/ə kwɪk fˈeɪvər/",
  "a valid point": "/ə vˈælɪd pɔɪnt/",
  "abbreviation": "/əbrˌiːviˈeɪʃən/",
  "abstract": "/æbstrˈækt/",
  "according to": "/əkˈɔːrdɪŋ tuː/",
  "acquisition": "/ˌækwəzˈɪʃən/",
  "action item": "/ˈækʃən ˈaɪtəm/",
  "action required": "/ˈækʃən rikwˈaɪərd/",
  "active recall": "/ˈæktɪv rˈiːkˌɔːl/",
  "adoption": "/ədˈɑːpʃən/",
  "agenda": "/ədʒˈendə/",
  "agenda slide": "/ədʒˈendə slaɪd/",
  "amendment": "/əmˈendmənt/",
  "anecdotal evidence": "/ˌænəkdˈoʊtəl ˈevədəns/",
  "any final comments": "/ˈeni fˈaɪnəl kˈɑːments/",
  "apologies": "/əpˈɑːlədʒˌiːz/",
  "approximately": "/əprˈɑːksəmətli/",
  "area for development": "/ˈeriə fɔːr dɪvˈeləpmənt/",
  "arguably": "/ˈɑːrɡjuəbli/",
  "as I mentioned earlier": "/æz aɪ mˈenʃənd ˈɜːrliər/",
  "as a result": "/æz ə rɪzˈʌlt/",
  "as advertised on": "/æz ˈædvərtˌaɪzd ɑːn/",
  "as agreed": "/æz əɡrˈiːd/",
  "as cited in": "/æz sˈaɪtəd ɪn/",
  "as per my previous email": "/æz pɜːr maɪ prˈiːviəs imˈeɪl/",
  "as shown in figure 2": "/æz ʃoʊn ɪn fˈɪɡjər/",
  "assessment": "/əsˈesmənt/",
  "assumption": "/əsˈʌmpʃən/",
  "at short notice": "/æt ʃɔːrt nˈoʊtəs/",
  "at your earliest convenience": "/æt jɔːr ˈɜːrliəst kənvˈiːnjəns/",
  "attribution": "/ˌætrɪbjˈuːʃən/",
  "author-date style": "/ˈɔːθərdeɪt staɪl/",
  "authority": "/əθˈɔːrəti/",
  "available from": "/əvˈeɪləbəl frʌm/",
  "bandwidth": "/bˈændwɪdθ/",
  "base number": "/beɪs nˈʌmbər/",
  "baseline": "/bˈeɪslˌaɪn/",
  "bias": "/bˈaɪəs/",
  "bottom line": "/bˈɑːtəm laɪn/",
  "bulk discount": "/bʌlk dɪskˈaʊnt/",
  "by contrast": "/baɪ kˈɑːntræst/",
  "by end of day (EOD)": "/baɪ end ʌv deɪ ˌiːoʊˈdiː/",
  "call to action": "/kɔːl tuː ˈækʃən/",
  "citation": "/saɪtˈeɪʃən/",
  "close reading": "/kloʊs rˈiːdɪŋ/",
  "coherent": "/koʊhˈɪrənt/",
  "collusion": "/kəlˈuːʒən/",
  "common ground": "/kˈɑːmən ɡraʊnd/",
  "common knowledge": "/kˈɑːmən nˈɑːlədʒ/",
  "compelling evidence": "/kəmpˈelɪŋ ˈevədəns/",
  "compliance": "/kəmplˈaɪəns/",
  "concession": "/kənsˈeʃən/",
  "concise": "/kənsˈaɪs/",
  "concluding sentence": "/kənklˈuːdɪŋ sˈentəns/",
  "confidentiality": "/kˌɑːnfədˌenʃiˈæləti/",
  "conflict of interest": "/kˈɑːnflɪkt ʌv ˈɪntrəst/",
  "confounding factor": "/kənfˈaʊndɪŋ fˈæktər/",
  "connected speech": "/kənˈektɪd spiːtʃ/",
  "consequently": "/kˈɑːnsəkwəntli/",
  "considerable": "/kənsˈɪdərəbəl/",
  "consistency": "/kənsˈɪstənsi/",
  "contrary to": "/kˈɑːntreri tuː/",
  "contribution": "/kˌɑːntrəbjˈuːʃən/",
  "control group": "/kəntrˈoʊl ɡruːp/",
  "controlling idea": "/kəntrˈoʊlɪŋ aɪdˈiːə/",
  "corrective action": "/kərˈektɪv ˈækʃən/",
  "correlation": "/kˌɔːrəlˈeɪʃən/",
  "counter-argument": "/kˈaʊntərˈɑːrɡjəmənt/",
  "counterexample": "/ˈkaʊntəreɡˌzæmpəl/",
  "credibility": "/krˌedəbˈɪlɪti/",
  "credit note": "/krˈedət noʊt/",
  "cross-functional": "/krɔːsfˈʌŋkʃənəl/",
  "cross-sectional": "/krɔːssˈekʃənəl/",
  "cue column": "/kjuː kˈɑːləm/",
  "currency": "/kˈɜːrənsi/",
  "deadline": "/dˈedlˌaɪn/",
  "deliverable": "/dɪlˈɪvərəbəl/",
  "deposit": "/dəpˈɑːzɪt/",
  "digression": "/daɪɡrˈeʃən/",
  "direct quotation": "/dərˈekt kwoʊtˈeɪʃən/",
  "discussant": "/dɪˈskʌsənt/",
  "due to": "/duː tuː/",
  "edition": "/ədˈɪʃən/",
  "effect size": "/ɪfˈekt saɪz/",
  "elevator pitch": "/ˈeləvˌeɪtər pɪtʃ/",
  "elision": "/ɪˈlɪʒən/",
  "emergence": "/ɪmˈɜːrdʒəns/",
  "enclosed": "/enklˈoʊzd/",
  "et al.": "/et æl/",
  "excluding VAT": "/ɪksklˈuːdɪŋ væt/",
  "executive summary": "/ɪɡzˈekjətɪv sˈʌməri/",
  "extension": "/ɪkstˈenʃən/",
  "faulty": "/fˈɔːlti/",
  "filler": "/fˈɪlər/",
  "final offer": "/fˈaɪnəl ˈɔːfər/",
  "findings": "/fˈaɪndɪŋz/",
  "flat": "/flæt/",
  "flawed": "/flɔːd/",
  "force majeure": "/fɔːrs mədʒˈuːr/",
  "from a ... perspective": "/frʌm ə pərspˈektɪv/",
  "further work": "/fˈɜːrðər wɜːrk/",
  "furthermore": "/fˈɜːrðərmˌɔːr/",
  "generalisable": "/ˈdʒenərəlaɪzəbəl/",
  "gentle reminder": "/dʒˈentəl rimˈaɪndər/",
  "gist": "/dʒɪst/",
  "given that": "/ɡˈɪvən ðæt/",
  "goodwill gesture": "/ɡˈʊdwˈɪl dʒˈestʃər/",
  "grey literature": "/ɡreɪ lˈɪtərətʃər/",
  "handout": "/hˈændˌaʊt/",
  "hanging indent": "/hˈæŋɪŋ ˌɪndˈent/",
  "heading": "/hˈedɪŋ/",
  "headline": "/hˈedlˌaɪn/",
  "however": "/hˌaʊˈevər/",
  "hypothesis": "/haɪpˈɑːθəsəs/",
  "hypothetical": "/hˌaɪpəθˈetəkəl/",
  "ibid.": "/ˈɪbɪd/",
  "if possible": "/ɪf pˈɑːsəbəl/",
  "implementation": "/ˌɪmpləmentˈeɪʃən/",
  "implication": "/ˌɪmpləkˈeɪʃən/",
  "implicit": "/ˌɪmplˈɪsət/",
  "in a nutshell": "/ɪn ə nˈʌtʃˌel/",
  "in addition to": "/ɪn ədˈɪʃən tuː/",
  "in conclusion": "/ɪn kənklˈuːʒən/",
  "in most cases": "/ɪn moʊst kˈeɪsəz/",
  "in my view": "/ɪn maɪ vjuː/",
  "in other words": "/ɪn ˈʌðər wɜːrdz/",
  "in principle": "/ɪn prˈɪnsəpəl/",
  "in the long run": "/ɪn ðə lɔːŋ rʌn/",
  "in writing": "/ɪn rˈaɪtɪŋ/",
  "in-text citation": "/ɪntekst saɪtˈeɪʃən/",
  "inclusive of shipping": "/ˌɪnklˈuːsɪv ʌv ʃˈɪpɪŋ/",
  "inconvenience": "/ˌɪnkənvˈiːnjəns/",
  "informational interview": "/ˌɪnfərmˈeɪʃənəl ˈɪntərvjˌuː/",
  "insufficient": "/ˌɪnsəfˈɪʃənt/",
  "intonation": "/ˌɪntənˈeɪʃən/",
  "it appears that": "/ɪt əpˈɪrz ðæt/",
  "key term": "/kiː tɜːrm/",
  "keyword": "/kˈiːwˌɜːrd/",
  "keywords": "/kˈiːwˌɜːrdz/",
  "lag": "/læɡ/",
  "lead time": "/led taɪm/",
  "leverage": "/lˈevərɪdʒ/",
  "liability": "/lˌaɪəbˈɪlɪti/",
  "likewise": "/lˈaɪkwˌaɪz/",
  "limitation": "/lˌɪmɪtˈeɪʃən/",
  "line of reasoning": "/laɪn ʌv rˈiːzənɪŋ/",
  "linking": "/lˈɪŋkɪŋ/",
  "longitudinal": "/lˌɑːndʒətˈuːdənəl/",
  "margin": "/mˈɑːrdʒən/",
  "may": "/meɪ/",
  "median": "/mˈiːdiən/",
  "methodology": "/mˌeθədˈɑːlədʒi/",
  "milestone": "/mˈaɪlstˌoʊn/",
  "minutes": "/mˈɪnəts/",
  "moreover": "/mɔːrˈoʊvər/",
  "mutual connection": "/mjˈuːtʃuəl kənˈekʃən/",
  "my role was to": "/maɪ roʊl wɑːz tuː/",
  "my sense is that": "/maɪ sens ɪz ðæt/",
  "negligible": "/nˈeɡlədʒəbəl/",
  "next steps": "/nekst steps/",
  "not necessarily": "/nɑːt nˌesəsˈerəli/",
  "notice period": "/nˈoʊtəs pˈɪriəd/",
  "notwithstanding": "/nˌɑːtwɪθstˈændɪŋ/",
  "numeric style": "/numˈerɪk staɪl/",
  "numerous": "/nˈuːmərəs/",
  "objective": "/əbdʒˈektɪv/",
  "off the top of my head": "/ɔːf ðə tɑːp ʌv maɪ hed/",
  "on balance": "/ɑːn bˈæləns/",
  "on behalf of": "/ɑːn bɪhˈæf ʌv/",
  "originality report": "/ərˌɪdʒənˈælɪti ripˈɔːrt/",
  "outlier": "/ˈaʊtlaɪər/",
  "outstanding": "/ˌaʊtstˈændɪŋ/",
  "over to you": "/ˈoʊvər tuː juː/",
  "owing to": "/ˈoʊɪŋ tuː/",
  "owner": "/ˈoʊnər/",
  "p-value": "/piːvˈælju/",
  "page range": "/peɪdʒ reɪndʒ/",
  "participants": "/pɑːrtˈɪsəpənts/",
  "patchwriting": "/ˈpætʃraɪtɪŋ/",
  "payment terms": "/pˈeɪmənt tɜːrmz/",
  "peer-reviewed": "/pɪrrivjˈuːd/",
  "pending": "/pˈendɪŋ/",
  "percentage point": "/pərsˈentədʒ pɔɪnt/",
  "plagiarism": "/plˈeɪdʒərˌɪzəm/",
  "plausible": "/plˈɔːzəbəl/",
  "please find attached": "/pliːz faɪnd ətˈætʃt/",
  "point me in the right direction": "/pɔɪnt miː ɪn ðə raɪt dərˈekʃən/",
  "preliminary findings": "/prɪlˈɪmənˌeri fˈaɪndɪŋz/",
  "premise": "/prˈemɪs/",
  "proficient in": "/prɑːfˈɪʃənt ɪn/",
  "provided that": "/prəvˈaɪdɪd ðæt/",
  "provision": "/prəvˈɪʒən/",
  "purpose statement": "/pˈɜːrpəs stˈeɪtmənt/",
  "questionnaire": "/kwˌestʃənˈer/",
  "quote is valid for": "/kwoʊt ɪz vˈælɪd fɔːr/",
  "recipient": "/rəsˈɪpiənt/",
  "reduction": "/rədˈʌkʃən/",
  "referee": "/rˌefərˈiː/",
  "reference list": "/rˈefərəns lɪst/",
  "referral": "/rɪfˈɜːrəl/",
  "relevance": "/rˈeləvəns/",
  "reliability": "/rilˌaɪəbˈɪləti/",
  "replacement": "/rɪplˈeɪsmənt/",
  "research gap": "/risˈɜːrtʃ ɡæp/",
  "research question": "/risˈɜːrtʃ kwˈestʃən/",
  "retrieved from": "/ritrˈiːvd frʌm/",
  "return on investment (ROI)": "/rɪtˈɜːrn ɑːn ˌɪnvˈestmənt rɔɪ/",
  "revision": "/rivˈɪʒən/",
  "root cause": "/ruːt kɑːz/",
  "salary expectations": "/sˈæləri ˌekspektˈeɪʃənz/",
  "sample": "/sˈæmpəl/",
  "scope": "/skoʊp/",
  "scope for future work": "/skoʊp fɔːr fjˈuːtʃər wɜːrk/",
  "scope of work": "/skoʊp ʌv wɜːrk/",
  "secondary source": "/sˈekəndˌeri sɔːrs/",
  "self-contained": "/sˈelfkəntˈeɪnd/",
  "self-plagiarism": "/selfplˈeɪdʒərˌɪzəm/",
  "self-reported": "/selfrˌiːpˈɔːrtɪd/",
  "seminar": "/sˈemənˌɑːr/",
  "shall": "/ʃæl/",
  "slot": "/slɑːt/",
  "small talk": "/smɔːl tɔːk/",
  "so we have agreed that": "/soʊ wiː hæv əɡrˈiːd ðæt/",
  "spaced review": "/speɪst rˌiːvjˈuː/",
  "stakeholder": "/stˈeɪkhˌoʊldər/",
  "stance": "/stæns/",
  "statistically significant": "/stətˈɪstɪkəli səɡnˈɪfɪkənt/",
  "strength": "/streŋkθ/",
  "stress pattern": "/stres pˈætərn/",
  "structured abstract": "/strˈʌktʃərd æbstrˈækt/",
  "subject to": "/səbdʒˈekt tuː/",
  "subjective": "/səbdʒˈektɪv/",
  "such approaches": "/sʌtʃ əprˈoʊtʃəz/",
  "summary strip": "/sˈʌməri strɪp/",
  "supporting detail": "/səpˈɔːrtɪŋ dɪtˈeɪl/",
  "tailored": "/tˈeɪlərd/",
  "takeaway": "/tˈeɪkəwˌeɪ/",
  "takeaway sentence": "/tˈeɪkəwˌeɪ sˈentəns/",
  "tend to": "/tend tuː/",
  "tentative": "/tˈentətɪv/",
  "termination clause": "/tərmənˈeɪʃən klɔːz/",
  "the ask": "/ðə æsk/",
  "the benefit is": "/ðə bˈenəfɪt ɪz/",
  "the bottom line": "/ðə bˈɑːtəm laɪn/",
  "the crucial point": "/ðə krˈuːʃəl pɔɪnt/",
  "the data suggests": "/ðə dˈeɪtə sədʒˈests/",
  "the evidence suggests": "/ðə ˈevədəns sədʒˈests/",
  "the findings indicate": "/ðə fˈaɪndɪŋz ˈɪndəkˌeɪt/",
  "the former ... the latter": "/ðə fˈɔːrmər ðə lˈætər/",
  "the present study": "/ðə prˈezənt stˈʌdi/",
  "the vast majority": "/ðə væst mədʒˈɔːrəti/",
  "thesis statement": "/θˈiːsəs stˈeɪtmənt/",
  "this finding": "/ðɪs fˈaɪndɪŋ/",
  "this paper examines": "/ðɪs pˈeɪpər ɪɡzˈæmənz/",
  "thus": "/ðʌs/",
  "time zone": "/taɪm zoʊn/",
  "to a certain extent": "/tuː ə sˈɜːrtən ɪkstˈent/",
  "to accommodate": "/tuː əkˈɑːmədˌeɪt/",
  "to account for": "/tuː əkˈaʊnt fɔːr/",
  "to acknowledge": "/tuː æknˈɑːlɪdʒ/",
  "to acknowledge a source": "/tuː æknˈɑːlɪdʒ ə sɔːrs/",
  "to add value": "/tuː æd vˈælju/",
  "to address a point": "/tuː ˈædrˌes ə pɔɪnt/",
  "to address a question": "/tuː ˈædrˌes ə kwˈestʃən/",
  "to align with": "/tuː əlˈaɪn wɪð/",
  "to argue that": "/tuː ˈɑːrɡju ðæt/",
  "to attribute A to B": "/tuː ˈætrəbjˌuːt ə tuː biː/",
  "to back up a claim": "/tuː bæk ʌp ə kleɪm/",
  "to be binding": "/tuː biː bˈaɪndɪŋ/",
  "to be observed": "/tuː biː əbzˈɜːrvd/",
  "to be on the same page": "/tuː biː ɑːn ðə seɪm peɪdʒ/",
  "to be promoted to": "/tuː biː prəmˈoʊtɪd tuː/",
  "to be structured as follows": "/tuː biː strˈʌktʃərd æz fˈɑːloʊz/",
  "to bear out": "/tuː ber aʊt/",
  "to bear with me": "/tuː ber wɪð miː/",
  "to break the ice": "/tuː breɪk ðə aɪs/",
  "to break up": "/tuː breɪk ʌp/",
  "to bring forward": "/tuː brɪŋ fˈɔːrwərd/",
  "to build a case": "/tuː bɪld ə keɪs/",
  "to build on": "/tuː bɪld ɑːn/",
  "to build on the previous comment": "/tuː bɪld ɑːn ðə prˈiːviəs kˈɑːment/",
  "to call back": "/tuː kɔːl bæk/",
  "to cap costs": "/tuː kæp kɑːsts/",
  "to catch up": "/tuː kætʃ ʌp/",
  "to caveat": "/tuː kˈeɪviˌæt/",
  "to chair a meeting": "/tuː tʃer ə mˈiːtɪŋ/",
  "to chase up": "/tuː tʃeɪs ʌp/",
  "to circle back": "/tuː sˈɜːrkəl bæk/",
  "to circulate": "/tuː sˈɜːrkjəlˌeɪt/",
  "to cite": "/tuː saɪt/",
  "to claim": "/tuː kleɪm/",
  "to clash with": "/tuː klæʃ wɪð/",
  "to compress": "/tuː kˈɑːmpres/",
  "to concede a point": "/tuː kənsˈiːd ə pɔɪnt/",
  "to conduct": "/tuː kˈɑːndəkt/",
  "to confirm in writing": "/tuː kənfˈɜːrm ɪn rˈaɪtɪŋ/",
  "to contend": "/tuː kəntˈend/",
  "to corroborate": "/tuː kərˈɑːbərˌeɪt/",
  "to cover three areas": "/tuː kˈʌvər θriː ˈeriəz/",
  "to demonstrate": "/tuː dˈemənstrˌeɪt/",
  "to digress": "/tuː daɪɡrˈes/",
  "to double-book": "/tuː dˈʌbəlbʊk/",
  "to drop something in the chat": "/tuː drɑːp sˈʌmθɪŋ ɪn ðə tʃæt/",
  "to elaborate": "/tuː ɪlˈæbrət/",
  "to elaborate on": "/tuː ɪlˈæbrət ɑːn/",
  "to endorse": "/tuː endˈɔːrs/",
  "to escalate": "/tuː ˈeskəlˌeɪt/",
  "to establish": "/tuː ɪstˈæblɪʃ/",
  "to exceed a target": "/tuː ɪksˈiːd ə tˈɑːrɡət/",
  "to fall short of": "/tuː fɔːl ʃɔːrt ʌv/",
  "to fall steadily": "/tuː fɔːl stˈedəli/",
  "to fit someone in": "/tuː fɪt sˈʌmwˌʌn ɪn/",
  "to flag": "/tuː flæɡ/",
  "to fluctuate": "/tuː flˈʌktʃəwˌeɪt/",
  "to follow through": "/tuː fˈɑːloʊ θruː/",
  "to follow up": "/tuː fˈɑːloʊ ʌp/",
  "to follow up on": "/tuː fˈɑːloʊ ʌp ɑːn/",
  "to follow up on that": "/tuː fˈɑːloʊ ʌp ɑːn ðæt/",
  "to get back to you": "/tuː ɡet bæk tuː juː/",
  "to get cut off": "/tuː ɡet kʌt ɔːf/",
  "to go along with": "/tuː ɡoʊ əlˈɔːŋ wɪð/",
  "to go over the details": "/tuː ɡoʊ ˈoʊvər ðə dɪtˈeɪlz/",
  "to green-light": "/tuː ɡriːnlaɪt/",
  "to have reservations about": "/tuː hæv rˌezərvˈeɪʃənz əbˈaʊt/",
  "to have something in common": "/tuː hæv sˈʌmθɪŋ ɪn kˈɑːmən/",
  "to hold the line": "/tuː hoʊld ðə laɪn/",
  "to increase": "/tuː ˌɪnkrˈiːs/",
  "to investigate": "/tuː ˌɪnvˈestəɡˌeɪt/",
  "to invite comments": "/tuː ˌɪnvˈaɪt kˈɑːments/",
  "to itemise": "/tuː ˈaɪtəmaɪz/",
  "to keep in touch": "/tuː kiːp ɪn tʌtʃ/",
  "to keep it concise": "/tuː kiːp ɪt kənsˈaɪs/",
  "to keep someone in mind": "/tuː kiːp sˈʌmwˌʌn ɪn maɪnd/",
  "to keep you posted": "/tuː kiːp juː pˈoʊstɪd/",
  "to kick off": "/tuː kɪk ɔːf/",
  "to learn from": "/tuː lɜːrn frʌm/",
  "to level off": "/tuː lˈevəl ɔːf/",
  "to lodge a complaint": "/tuː lɑːdʒ ə kəmplˈeɪnt/",
  "to loop in": "/tuː luːp ɪn/",
  "to make up for": "/tuː meɪk ʌp fɔːr/",
  "to meet halfway": "/tuː miːt hˈæfwˈeɪ/",
  "to move on to": "/tuː muːv ɑːn tuː/",
  "to obtain": "/tuː əbtˈeɪn/",
  "to omit": "/tuː oʊmˈɪt/",
  "to overlook": "/tuː ˈoʊvərlˌʊk/",
  "to paraphrase": "/tuː pˈerəfrˌeɪz/",
  "to paraphrase in notes": "/tuː pˈerəfrˌeɪz ɪn noʊts/",
  "to park a question": "/tuː pɑːrk ə kwˈestʃən/",
  "to park an issue": "/tuː pɑːrk æn ˈɪʃu/",
  "to peak at": "/tuː piːk æt/",
  "to play devil's advocate": "/tuː pleɪ dˈevəlz ˈædvəkət/",
  "to present in brief": "/tuː prˈezənt ɪn briːf/",
  "to prioritise": "/tuː praɪˈɒrətaɪz/",
  "to prioritise sources": "/tuː praɪˈɒrətaɪz sˈɔːrsəz/",
  "to push back": "/tuː pʊʃ bæk/",
  "to put someone through": "/tuː pʊt sˈʌmwˌʌn θruː/",
  "to raise a point": "/tuː reɪz ə pɔɪnt/",
  "to reach a compromise": "/tuː riːtʃ ə kˈɑːmprəmˌaɪz/",
  "to reach out": "/tuː riːtʃ aʊt/",
  "to recap": "/tuː rˈiːkˌæp/",
  "to record the session": "/tuː rəkˈɔːrd ðə sˈeʃən/",
  "to refute": "/tuː rɪfjˈuːt/",
  "to rejoin": "/tuː ridʒˈɔɪn/",
  "to rephrase": "/tuː rifrˈeɪz/",
  "to rephrase from memory": "/tuː rifrˈeɪz frʌm mˈeməri/",
  "to replicate": "/tuː rˈepləkˌeɪt/",
  "to reschedule": "/tuː riskˈedʒul/",
  "to resolve": "/tuː rizˈɑːlv/",
  "to respectfully disagree": "/tuː rɪspˈektfəli dɪsəɡrˈiː/",
  "to result in": "/tuː rɪzˈʌlt ɪn/",
  "to rise sharply": "/tuː raɪz ʃˈɑːrpli/",
  "to run over time": "/tuː rʌn ˈoʊvər taɪm/",
  "to scale up": "/tuː skeɪl ʌp/",
  "to scan": "/tuː skæn/",
  "to shadow": "/tuː ʃˈædˌoʊ/",
  "to share your screen": "/tuː ʃer jɔːr skriːn/",
  "to sign off on": "/tuː saɪn ɔːf ɑːn/",
  "to signpost": "/tuː sˈaɪnpˌoʊst/",
  "to skim": "/tuː skɪm/",
  "to spearhead": "/tuː spˈɪrhˌed/",
  "to stem from": "/tuː stem frʌm/",
  "to stick to the agenda": "/tuː stɪk tuː ðə ədʒˈendə/",
  "to streamline": "/tuː strˈiːmlˌaɪn/",
  "to substantiate": "/tuː səbstˈæntʃiˌeɪt/",
  "to substantiate a claim": "/tuː səbstˈæntʃiˌeɪt ə kleɪm/",
  "to sum up": "/tuː sʌm ʌp/",
  "to summarise findings": "/tuː ˈsʌməraɪz fˈaɪndɪŋz/",
  "to summarise in one sentence": "/tuː ˈsʌməraɪz ɪn wʌn sˈentəns/",
  "to sweeten the deal": "/tuː swˈiːtən ðə diːl/",
  "to take a message": "/tuː teɪk ə mˈesədʒ/",
  "to take ownership": "/tuː teɪk ˈoʊnərʃˌɪp/",
  "to take the initiative": "/tuː teɪk ðə ˌɪnˈɪʃətɪv/",
  "to talk over someone": "/tuː tɔːk ˈoʊvər sˈʌmwˌʌn/",
  "to touch base": "/tuː tʌtʃ beɪs/",
  "to triangulate": "/tuː traɪˈæŋɡjəleɪt/",
  "to tune in to an accent": "/tuː tuːn ɪn tuː æn əksˈent/",
  "to walk away": "/tuː wɔːk əwˈeɪ/",
  "to walk you through": "/tuː wɔːk juː θruː/",
  "to warrant further research": "/tuː wˈɔːrənt fˈɜːrðər risˈɜːrtʃ/",
  "to weigh the risk": "/tuː weɪ ðə rɪsk/",
  "to weigh up": "/tuː weɪ ʌp/",
  "to wrap up": "/tuː ræp ʌp/",
  "topic sentence": "/tˈɑːpɪk sˈentəns/",
  "topic sentence scan": "/tˈɑːpɪk sˈentəns skæn/",
  "track record": "/træk rəkˈɔːrd/",
  "trade-off": "/trˈeɪdˌɔːf/",
  "transcript": "/trˈænskrˌɪpt/",
  "transparent method": "/trænspˈerənt mˈeθəd/",
  "under pressure": "/ˈʌndər prˈeʃər/",
  "underlying cause": "/ˌʌndərlˈaɪɪŋ kɑːz/",
  "unfortunately": "/ənfˈɔːrtʃənətli/",
  "unit price": "/jˈuːnət praɪs/",
  "unity": "/jˈuːnəti/",
  "unlikely to": "/ənlˈaɪkli tuː/",
  "up to a point": "/ʌp tuː ə pɔɪnt/",
  "valid concern": "/vˈælɪd kənsˈɜːrn/",
  "variability": "/veriəbˈɪlɪti/",
  "variable": "/vˈeriəbəl/",
  "verbatim": "/vərbˈeɪtəm/",
  "verbatim copying": "/vərbˈeɪtəm kˈɑːpiɪŋ/",
  "vested interest": "/vˈestɪd ˈɪntrəst/",
  "weak form": "/wiːk fɔːrm/",
  "whereas": "/werˈæz/",
  "win-win": "/wˌɪnwˈɪn/",
  "with immediate effect": "/wɪð ˌɪmˈiːdˌiːət ɪfˈekt/",
  "with reference to": "/wɪð rˈefərəns tuː/",
  "with regard to": "/wɪð rɪɡˈɑːrd tuː/",
  "with respect": "/wɪð rɪspˈekt/",
  "word limit": "/wɜːrd lˈɪmət/",
  "worst case": "/wɜːrst keɪs/",
  "year on year": "/jɪr ɑːn jɪr/",
};

export const getPurposePhraseIpa = (term: string): string => PURPOSE_PHRASE_IPA[term] ?? "";
