/**
 * IPA transcriptions for every Business and Academic English lesson phrase.
 * Generated from the CMU Pronouncing Dictionary and reviewed supplements.
 */
const PURPOSE_PHRASE_IPA: Record<string, string> = {
  "Best regards": "/best rɪɡˈɑːrdz/",
  "Can everyone hear me?": "/kæn ˈevriwˌʌn hiːr miː/",
  "Could I speak to": "/kʊd aɪ spiːk tuː/",
  "Could you clarify": "/kʊd juː klˈerəfˌaɪ/",
  "Could you please": "/kʊd juː pliːz/",
  "DOI": "/dɔɪ/",
  "Do let me know if": "/duː let miː noʊ ɪf/",
  "Do you have any questions for us?": "/duː juː hæv ˈeni kwˈestʃənz fɔːr ʌs/",
  "Does that answer your question?": "/dʌz ðæt ˈænsər jɔːr kwˈestʃən/",
  "Go ahead": "/ɡoʊ əhˈed/",
  "How are things at your end?": "/haʊ ɑːr θɪŋz æt jɔːr end/",
  "How does that look from ...?": "/haʊ dʌz ðæt lʊk frʌm/",
  "How was your trip?": "/haʊ wɑːz jɔːr trɪp/",
  "How would this apply to": "/haʊ wʊd ðɪs əplˈaɪ tuː/",
  "I am not sure I agree": "/aɪ æm nɑːt ʃʊr aɪ əɡrˈiː/",
  "I am writing to": "/aɪ æm rˈaɪtɪŋ tuː/",
  "I am writing to apply for": "/aɪ æm rˈaɪtɪŋ tuː əplˈaɪ fɔːr/",
  "I apologise for": "/aɪ əpˈɑːlədʒˌaɪz fɔːr/",
  "I bring": "/aɪ brɪŋ/",
  "I help ... to ...": "/aɪ help tuː/",
  "I recommend that we": "/aɪ rˌekəmˈend ðæt wiː/",
  "I see your point, but": "/aɪ siː jɔːr pɔɪnt bʌt/",
  "I would appreciate it if": "/aɪ wʊd əprˈiːʃiˌeɪt ɪt ɪf/",
  "I would welcome the chance to": "/aɪ wʊd wˈelkəm ðə tʃæns tuː/",
  "If you ..., we can ...": "/ɪf juː wiː kæn/",
  "Is this your first time in": "/ɪz ðɪs jɔːr fɜːrst taɪm ɪn/",
  "It can be seen that": "/ɪt kæn biː siːn ðæt/",
  "It was a pleasure meeting you": "/ɪt wɑːz ə plˈeʒər mˈiːtɪŋ juː/",
  "Let us turn to": "/let ʌs tɜːrn tuː/",
  "Shall we make a start?": "/ʃæl wiː meɪk ə stɑːrt/",
  "Tell me about a time when": "/tel miː əbˈaʊt ə taɪm wen/",
  "Thank you for your time": "/θæŋk juː fɔːr jɔːr taɪm/",
  "Thanks in advance": "/θæŋks ɪn ədvˈæns/",
  "That brings me to": "/ðæt brɪŋz miː tuː/",
  "That is a good question": "/ðæt ɪz ə ɡʊd kwˈestʃən/",
  "There is evidence that": "/ðer ɪz ˈevədəns ðæt/",
  "This is ... speaking": "/ðɪs ɪz spˈiːkɪŋ/",
  "This paper argues that": "/ðɪs pˈeɪpər ˈɑːrɡjuz ðæt/",
  "Today I will show": "/tədˈeɪ aɪ wɪl ʃoʊ/",
  "What evidence supports": "/wʌt ˈevədəns səpˈɔːrts/",
  "Would ... suit you?": "/wʊd suːt juː/",
  "Would you mind + V-ing": "/wʊd juː maɪnd viːɪŋ/",
  "You are on mute": "/juː ɑːr ɑːn mjuːt/",
  "Yours sincerely": "/jʊrz sɪnsˈɪrli/",
  "a minority": "/ə maɪnˈɔːrəti/",
  "a quick favour": "/ə kwɪk fˈeɪvər/",
  "a valid point": "/ə vˈælɪd pɔɪnt/",
  "abbreviation": "/əbrˌiːviˈeɪʃən/",
  "abstract": "/æbstrˈækt/",
  "according to": "/əkˈɔːrdɪŋ tuː/",
  "acquisition": "/ˌækwəzˈɪʃən/",
  "action item": "/ˈækʃən ˈaɪtəm/",
  "action required": "/ˈækʃən rikwˈaɪərd/",
  "active recall": "/ˈæktɪv rˈiːkˌɔːl/",
  "adoption": "/ədˈɑːpʃən/",
  "agenda": "/ədʒˈendə/",
  "agenda slide": "/ədʒˈendə slaɪd/",
  "amendment": "/əmˈendmənt/",
  "anecdotal evidence": "/ˌænəkdˈoʊtəl ˈevədəns/",
  "any final comments": "/ˈeni fˈaɪnəl kˈɑːments/",
  "apologies": "/əpˈɑːlədʒˌiːz/",
  "approximately": "/əprˈɑːksəmətli/",
  "area for development": "/ˈeriə fɔːr dɪvˈeləpmənt/",
  "arguably": "/ˈɑːrɡjuəbli/",
  "as I mentioned earlier": "/æz aɪ mˈenʃənd ˈɜːrliər/",
  "as a result": "/æz ə rɪzˈʌlt/",
  "as advertised on": "/æz ˈædvərtˌaɪzd ɑːn/",
  "as agreed": "/æz əɡrˈiːd/",
  "as cited in": "/æz sˈaɪtəd ɪn/",
  "as per my previous email": "/æz pɜːr maɪ prˈiːviəs imˈeɪl/",
  "as shown in figure 2": "/æz ʃoʊn ɪn fˈɪɡjər/",
  "assessment": "/əsˈesmənt/",
  "assumption": "/əsˈʌmpʃən/",
  "at short notice": "/æt ʃɔːrt nˈoʊtəs/",
  "at your earliest convenience": "/æt jɔːr ˈɜːrliəst kənvˈiːnjəns/",
  "attribution": "/ˌætrɪbjˈuːʃən/",
  "author-date style": "/ˈɔːθərdeɪt staɪl/",
  "authority": "/əθˈɔːrəti/",
  "available from": "/əvˈeɪləbəl frʌm/",
  "bandwidth": "/bˈændwɪdθ/",
  "base number": "/beɪs nˈʌmbər/",
  "baseline": "/bˈeɪslˌaɪn/",
  "bias": "/bˈaɪəs/",
  "bottom line": "/bˈɑːtəm laɪn/",
  "bulk discount": "/bʌlk dɪskˈaʊnt/",
  "by contrast": "/baɪ kˈɑːntræst/",
  "by end of day (EOD)": "/baɪ end ʌv deɪ ˌiːoʊˈdiː/",
  "call to action": "/kɔːl tuː ˈækʃən/",
  "citation": "/saɪtˈeɪʃən/",
  "close reading": "/kloʊs rˈiːdɪŋ/",
  "coherent": "/koʊhˈɪrənt/",
  "collusion": "/kəlˈuːʒən/",
  "common ground": "/kˈɑːmən ɡraʊnd/",
  "common knowledge": "/kˈɑːmən nˈɑːlədʒ/",
  "compelling evidence": "/kəmpˈelɪŋ ˈevədəns/",
  "compliance": "/kəmplˈaɪəns/",
  "concession": "/kənsˈeʃən/",
  "concise": "/kənsˈaɪs/",
  "concluding sentence": "/kənklˈuːdɪŋ sˈentəns/",
  "confidentiality": "/kˌɑːnfədˌenʃiˈæləti/",
  "conflict of interest": "/kˈɑːnflɪkt ʌv ˈɪntrəst/",
  "confounding factor": "/kənfˈaʊndɪŋ fˈæktər/",
  "connected speech": "/kənˈektɪd spiːtʃ/",
  "consequently": "/kˈɑːnsəkwəntli/",
  "considerable": "/kənsˈɪdərəbəl/",
  "consistency": "/kənsˈɪstənsi/",
  "contrary to": "/kˈɑːntreri tuː/",
  "contribution": "/kˌɑːntrəbjˈuːʃən/",
  "control group": "/kəntrˈoʊl ɡruːp/",
  "controlling idea": "/kəntrˈoʊlɪŋ aɪdˈiːə/",
  "corrective action": "/kərˈektɪv ˈækʃən/",
  "correlation": "/kˌɔːrəlˈeɪʃən/",
  "counter-argument": "/kˈaʊntərˈɑːrɡjəmənt/",
  "counterexample": "/ˈkaʊntəreɡˌzæmpəl/",
  "credibility": "/krˌedəbˈɪlɪti/",
  "credit note": "/krˈedət noʊt/",
  "cross-functional": "/krɔːsfˈʌŋkʃənəl/",
  "cross-sectional": "/krɔːssˈekʃənəl/",
  "cue column": "/kjuː kˈɑːləm/",
  "currency": "/kˈɜːrənsi/",
  "deadline": "/dˈedlˌaɪn/",
  "deliverable": "/dɪlˈɪvərəbəl/",
  "deposit": "/dəpˈɑːzɪt/",
  "digression": "/daɪɡrˈeʃən/",
  "direct quotation": "/dərˈekt kwoʊtˈeɪʃən/",
  "discussant": "/dɪˈskʌsənt/",
  "due to": "/duː tuː/",
  "edition": "/ədˈɪʃən/",
  "effect size": "/ɪfˈekt saɪz/",
  "elevator pitch": "/ˈeləvˌeɪtər pɪtʃ/",
  "elision": "/ɪˈlɪʒən/",
  "emergence": "/ɪmˈɜːrdʒəns/",
  "enclosed": "/enklˈoʊzd/",
  "et al.": "/et æl/",
  "excluding VAT": "/ɪksklˈuːdɪŋ væt/",
  "executive summary": "/ɪɡzˈekjətɪv sˈʌməri/",
  "extension": "/ɪkstˈenʃən/",
  "faulty": "/fˈɔːlti/",
  "filler": "/fˈɪlər/",
  "final offer": "/fˈaɪnəl ˈɔːfər/",
  "findings": "/fˈaɪndɪŋz/",
  "flat": "/flæt/",
  "flawed": "/flɔːd/",
  "force majeure": "/fɔːrs mədʒˈuːr/",
  "from a ... perspective": "/frʌm ə pərspˈektɪv/",
  "further work": "/fˈɜːrðər wɜːrk/",
  "furthermore": "/fˈɜːrðərmˌɔːr/",
  "generalisable": "/ˈdʒenərəlaɪzəbəl/",
  "gentle reminder": "/dʒˈentəl rimˈaɪndər/",
  "gist": "/dʒɪst/",
  "given that": "/ɡˈɪvən ðæt/",
  "goodwill gesture": "/ɡˈʊdwˈɪl dʒˈestʃər/",
  "grey literature": "/ɡreɪ lˈɪtərətʃər/",
  "handout": "/hˈændˌaʊt/",
  "hanging indent": "/hˈæŋɪŋ ˌɪndˈent/",
  "heading": "/hˈedɪŋ/",
  "headline": "/hˈedlˌaɪn/",
  "however": "/hˌaʊˈevər/",
  "hypothesis": "/haɪpˈɑːθəsəs/",
  "hypothetical": "/hˌaɪpəθˈetəkəl/",
  "ibid.": "/ˈɪbɪd/",
  "if possible": "/ɪf pˈɑːsəbəl/",
  "implementation": "/ˌɪmpləmentˈeɪʃən/",
  "implication": "/ˌɪmpləkˈeɪʃən/",
  "implicit": "/ˌɪmplˈɪsət/",
  "in a nutshell": "/ɪn ə nˈʌtʃˌel/",
  "in addition to": "/ɪn ədˈɪʃən tuː/",
  "in conclusion": "/ɪn kənklˈuːʒən/",
  "in most cases": "/ɪn moʊst kˈeɪsəz/",
  "in my view": "/ɪn maɪ vjuː/",
  "in other words": "/ɪn ˈʌðər wɜːrdz/",
  "in principle": "/ɪn prˈɪnsəpəl/",
  "in the long run": "/ɪn ðə lɔːŋ rʌn/",
  "in writing": "/ɪn rˈaɪtɪŋ/",
  "in-text citation": "/ɪntekst saɪtˈeɪʃən/",
  "inclusive of shipping": "/ˌɪnklˈuːsɪv ʌv ʃˈɪpɪŋ/",
  "inconvenience": "/ˌɪnkənvˈiːnjəns/",
  "informational interview": "/ˌɪnfərmˈeɪʃənəl ˈɪntərvjˌuː/",
  "insufficient": "/ˌɪnsəfˈɪʃənt/",
  "intonation": "/ˌɪntənˈeɪʃən/",
  "it appears that": "/ɪt əpˈɪrz ðæt/",
  "key term": "/kiː tɜːrm/",
  "keyword": "/kˈiːwˌɜːrd/",
  "keywords": "/kˈiːwˌɜːrdz/",
  "lag": "/læɡ/",
  "lead time": "/led taɪm/",
  "leverage": "/lˈevərɪdʒ/",
  "liability": "/lˌaɪəbˈɪlɪti/",
  "likewise": "/lˈaɪkwˌaɪz/",
  "limitation": "/lˌɪmɪtˈeɪʃən/",
  "line of reasoning": "/laɪn ʌv rˈiːzənɪŋ/",
  "linking": "/lˈɪŋkɪŋ/",
  "longitudinal": "/lˌɑːndʒətˈuːdənəl/",
  "margin": "/mˈɑːrdʒən/",
  "may": "/meɪ/",
  "median": "/mˈiːdiən/",
  "methodology": "/mˌeθədˈɑːlədʒi/",
  "milestone": "/mˈaɪlstˌoʊn/",
  "minutes": "/mˈɪnəts/",
  "moreover": "/mɔːrˈoʊvər/",
  "mutual connection": "/mjˈuːtʃuəl kənˈekʃən/",
  "my role was to": "/maɪ roʊl wɑːz tuː/",
  "my sense is that": "/maɪ sens ɪz ðæt/",
  "negligible": "/nˈeɡlədʒəbəl/",
  "next steps": "/nekst steps/",
  "not necessarily": "/nɑːt nˌesəsˈerəli/",
  "notice period": "/nˈoʊtəs pˈɪriəd/",
  "notwithstanding": "/nˌɑːtwɪθstˈændɪŋ/",
  "numeric style": "/numˈerɪk staɪl/",
  "numerous": "/nˈuːmərəs/",
  "objective": "/əbdʒˈektɪv/",
  "off the top of my head": "/ɔːf ðə tɑːp ʌv maɪ hed/",
  "on balance": "/ɑːn bˈæləns/",
  "on behalf of": "/ɑːn bɪhˈæf ʌv/",
  "originality report": "/ərˌɪdʒənˈælɪti ripˈɔːrt/",
  "outlier": "/ˈaʊtlaɪər/",
  "outstanding": "/ˌaʊtstˈændɪŋ/",
  "over to you": "/ˈoʊvər tuː juː/",
  "owing to": "/ˈoʊɪŋ tuː/",
  "owner": "/ˈoʊnər/",
  "p-value": "/piːvˈælju/",
  "page range": "/peɪdʒ reɪndʒ/",
  "participants": "/pɑːrtˈɪsəpənts/",
  "patchwriting": "/ˈpætʃraɪtɪŋ/",
  "payment terms": "/pˈeɪmənt tɜːrmz/",
  "peer-reviewed": "/pɪrrivjˈuːd/",
  "pending": "/pˈendɪŋ/",
  "percentage point": "/pərsˈentədʒ pɔɪnt/",
  "plagiarism": "/plˈeɪdʒərˌɪzəm/",
  "plausible": "/plˈɔːzəbəl/",
  "please find attached": "/pliːz faɪnd ətˈætʃt/",
  "point me in the right direction": "/pɔɪnt miː ɪn ðə raɪt dərˈekʃən/",
  "preliminary findings": "/prɪlˈɪmənˌeri fˈaɪndɪŋz/",
  "premise": "/prˈemɪs/",
  "proficient in": "/prɑːfˈɪʃənt ɪn/",
  "provided that": "/prəvˈaɪdɪd ðæt/",
  "provision": "/prəvˈɪʒən/",
  "purpose statement": "/pˈɜːrpəs stˈeɪtmənt/",
  "questionnaire": "/kwˌestʃənˈer/",
  "quote is valid for": "/kwoʊt ɪz vˈælɪd fɔːr/",
  "recipient": "/rəsˈɪpiənt/",
  "reduction": "/rədˈʌkʃən/",
  "referee": "/rˌefərˈiː/",
  "reference list": "/rˈefərəns lɪst/",
  "referral": "/rɪfˈɜːrəl/",
  "relevance": "/rˈeləvəns/",
  "reliability": "/rilˌaɪəbˈɪləti/",
  "replacement": "/rɪplˈeɪsmənt/",
  "research gap": "/risˈɜːrtʃ ɡæp/",
  "research question": "/risˈɜːrtʃ kwˈestʃən/",
  "retrieved from": "/ritrˈiːvd frʌm/",
  "return on investment (ROI)": "/rɪtˈɜːrn ɑːn ˌɪnvˈestmənt rɔɪ/",
  "revision": "/rivˈɪʒən/",
  "root cause": "/ruːt kɑːz/",
  "salary expectations": "/sˈæləri ˌekspektˈeɪʃənz/",
  "sample": "/sˈæmpəl/",
  "scope": "/skoʊp/",
  "scope for future work": "/skoʊp fɔːr fjˈuːtʃər wɜːrk/",
  "scope of work": "/skoʊp ʌv wɜːrk/",
  "secondary source": "/sˈekəndˌeri sɔːrs/",
  "self-contained": "/sˈelfkəntˈeɪnd/",
  "self-plagiarism": "/selfplˈeɪdʒərˌɪzəm/",
  "self-reported": "/selfrˌiːpˈɔːrtɪd/",
  "seminar": "/sˈemənˌɑːr/",
  "shall": "/ʃæl/",
  "slot": "/slɑːt/",
  "small talk": "/smɔːl tɔːk/",
  "so we have agreed that": "/soʊ wiː hæv əɡrˈiːd ðæt/",
  "spaced review": "/speɪst rˌiːvjˈuː/",
  "stakeholder": "/stˈeɪkhˌoʊldər/",
  "stance": "/stæns/",
  "statistically significant": "/stətˈɪstɪkəli səɡnˈɪfɪkənt/",
  "strength": "/streŋkθ/",
  "stress pattern": "/stres pˈætərn/",
  "structured abstract": "/strˈʌktʃərd æbstrˈækt/",
  "subject to": "/səbdʒˈekt tuː/",
  "subjective": "/səbdʒˈektɪv/",
  "such approaches": "/sʌtʃ əprˈoʊtʃəz/",
  "summary strip": "/sˈʌməri strɪp/",
  "supporting detail": "/səpˈɔːrtɪŋ dɪtˈeɪl/",
  "tailored": "/tˈeɪlərd/",
  "takeaway": "/tˈeɪkəwˌeɪ/",
  "takeaway sentence": "/tˈeɪkəwˌeɪ sˈentəns/",
  "tend to": "/tend tuː/",
  "tentative": "/tˈentətɪv/",
  "termination clause": "/tərmənˈeɪʃən klɔːz/",
  "the ask": "/ðə æsk/",
  "the benefit is": "/ðə bˈenəfɪt ɪz/",
  "the bottom line": "/ðə bˈɑːtəm laɪn/",
  "the crucial point": "/ðə krˈuːʃəl pɔɪnt/",
  "the data suggests": "/ðə dˈeɪtə sədʒˈests/",
  "the evidence suggests": "/ðə ˈevədəns sədʒˈests/",
  "the findings indicate": "/ðə fˈaɪndɪŋz ˈɪndəkˌeɪt/",
  "the former ... the latter": "/ðə fˈɔːrmər ðə lˈætər/",
  "the present study": "/ðə prˈezənt stˈʌdi/",
  "the vast majority": "/ðə væst mədʒˈɔːrəti/",
  "thesis statement": "/θˈiːsəs stˈeɪtmənt/",
  "this finding": "/ðɪs fˈaɪndɪŋ/",
  "this paper examines": "/ðɪs pˈeɪpər ɪɡzˈæmənz/",
  "thus": "/ðʌs/",
  "time zone": "/taɪm zoʊn/",
  "to a certain extent": "/ə sˈɜːrtən ɪkstˈent/",
  "to accommodate": "/əkˈɑːmədˌeɪt/",
  "to account for": "/əkˈaʊnt fɔːr/",
  "to acknowledge": "/æknˈɑːlɪdʒ/",
  "to acknowledge a source": "/æknˈɑːlɪdʒ ə sɔːrs/",
  "to add value": "/æd vˈælju/",
  "to address a point": "/ˈædrˌes ə pɔɪnt/",
  "to address a question": "/ˈædrˌes ə kwˈestʃən/",
  "to align with": "/əlˈaɪn wɪð/",
  "to argue that": "/ˈɑːrɡju ðæt/",
  "to attribute A to B": "/ˈætrəbjˌuːt ə tuː biː/",
  "to back up a claim": "/bæk ʌp ə kleɪm/",
  "to be binding": "/biː bˈaɪndɪŋ/",
  "to be observed": "/biː əbzˈɜːrvd/",
  "to be on the same page": "/biː ɑːn ðə seɪm peɪdʒ/",
  "to be promoted to": "/biː prəmˈoʊtɪd tuː/",
  "to be structured as follows": "/biː strˈʌktʃərd æz fˈɑːloʊz/",
  "to bear out": "/ber aʊt/",
  "to bear with me": "/ber wɪð miː/",
  "to break the ice": "/breɪk ðə aɪs/",
  "to break up": "/breɪk ʌp/",
  "to bring forward": "/brɪŋ fˈɔːrwərd/",
  "to build a case": "/bɪld ə keɪs/",
  "to build on": "/bɪld ɑːn/",
  "to build on the previous comment": "/bɪld ɑːn ðə prˈiːviəs kˈɑːment/",
  "to call back": "/kɔːl bæk/",
  "to cap costs": "/kæp kɑːsts/",
  "to catch up": "/kætʃ ʌp/",
  "to caveat": "/kˈeɪviˌæt/",
  "to chair a meeting": "/tʃer ə mˈiːtɪŋ/",
  "to chase up": "/tʃeɪs ʌp/",
  "to circle back": "/sˈɜːrkəl bæk/",
  "to circulate": "/sˈɜːrkjəlˌeɪt/",
  "to cite": "/saɪt/",
  "to claim": "/kleɪm/",
  "to clash with": "/klæʃ wɪð/",
  "to compress": "/kˈɑːmpres/",
  "to concede a point": "/kənsˈiːd ə pɔɪnt/",
  "to conduct": "/kˈɑːndəkt/",
  "to confirm in writing": "/kənfˈɜːrm ɪn rˈaɪtɪŋ/",
  "to contend": "/kəntˈend/",
  "to corroborate": "/kərˈɑːbərˌeɪt/",
  "to cover three areas": "/kˈʌvər θriː ˈeriəz/",
  "to demonstrate": "/dˈemənstrˌeɪt/",
  "to digress": "/daɪɡrˈes/",
  "to double-book": "/dˈʌbəlbʊk/",
  "to drop something in the chat": "/drɑːp sˈʌmθɪŋ ɪn ðə tʃæt/",
  "to elaborate": "/ɪlˈæbrət/",
  "to elaborate on": "/ɪlˈæbrət ɑːn/",
  "to endorse": "/endˈɔːrs/",
  "to escalate": "/ˈeskəlˌeɪt/",
  "to establish": "/ɪstˈæblɪʃ/",
  "to exceed a target": "/ɪksˈiːd ə tˈɑːrɡət/",
  "to fall short of": "/fɔːl ʃɔːrt ʌv/",
  "to fall steadily": "/fɔːl stˈedəli/",
  "to fit someone in": "/fɪt sˈʌmwˌʌn ɪn/",
  "to flag": "/flæɡ/",
  "to fluctuate": "/flˈʌktʃəwˌeɪt/",
  "to follow through": "/fˈɑːloʊ θruː/",
  "to follow up": "/fˈɑːloʊ ʌp/",
  "to follow up on": "/fˈɑːloʊ ʌp ɑːn/",
  "to follow up on that": "/fˈɑːloʊ ʌp ɑːn ðæt/",
  "to get back to you": "/ɡet bæk tuː juː/",
  "to get cut off": "/ɡet kʌt ɔːf/",
  "to go along with": "/ɡoʊ əlˈɔːŋ wɪð/",
  "to go over the details": "/ɡoʊ ˈoʊvər ðə dɪtˈeɪlz/",
  "to green-light": "/ɡriːnlaɪt/",
  "to have reservations about": "/hæv rˌezərvˈeɪʃənz əbˈaʊt/",
  "to have something in common": "/hæv sˈʌmθɪŋ ɪn kˈɑːmən/",
  "to hold the line": "/hoʊld ðə laɪn/",
  "to increase": "/ˌɪnkrˈiːs/",
  "to investigate": "/ˌɪnvˈestəɡˌeɪt/",
  "to invite comments": "/ˌɪnvˈaɪt kˈɑːments/",
  "to itemise": "/ˈaɪtəmaɪz/",
  "to keep in touch": "/kiːp ɪn tʌtʃ/",
  "to keep it concise": "/kiːp ɪt kənsˈaɪs/",
  "to keep someone in mind": "/kiːp sˈʌmwˌʌn ɪn maɪnd/",
  "to keep you posted": "/kiːp juː pˈoʊstɪd/",
  "to kick off": "/kɪk ɔːf/",
  "to learn from": "/lɜːrn frʌm/",
  "to level off": "/lˈevəl ɔːf/",
  "to lodge a complaint": "/lɑːdʒ ə kəmplˈeɪnt/",
  "to loop in": "/luːp ɪn/",
  "to make up for": "/meɪk ʌp fɔːr/",
  "to meet halfway": "/miːt hˈæfwˈeɪ/",
  "to move on to": "/muːv ɑːn tuː/",
  "to obtain": "/əbtˈeɪn/",
  "to omit": "/oʊmˈɪt/",
  "to overlook": "/ˈoʊvərlˌʊk/",
  "to paraphrase": "/pˈerəfrˌeɪz/",
  "to paraphrase in notes": "/pˈerəfrˌeɪz ɪn noʊts/",
  "to park a question": "/pɑːrk ə kwˈestʃən/",
  "to park an issue": "/pɑːrk æn ˈɪʃu/",
  "to peak at": "/piːk æt/",
  "to play devil's advocate": "/pleɪ dˈevəlz ˈædvəkət/",
  "to present in brief": "/prˈezənt ɪn briːf/",
  "to prioritise": "/praɪˈɒrətaɪz/",
  "to prioritise sources": "/praɪˈɒrətaɪz sˈɔːrsəz/",
  "to push back": "/pʊʃ bæk/",
  "to put someone through": "/pʊt sˈʌmwˌʌn θruː/",
  "to raise a point": "/reɪz ə pɔɪnt/",
  "to reach a compromise": "/riːtʃ ə kˈɑːmprəmˌaɪz/",
  "to reach out": "/riːtʃ aʊt/",
  "to recap": "/rˈiːkˌæp/",
  "to record the session": "/rəkˈɔːrd ðə sˈeʃən/",
  "to refute": "/rɪfjˈuːt/",
  "to rejoin": "/ridʒˈɔɪn/",
  "to rephrase": "/rifrˈeɪz/",
  "to rephrase from memory": "/rifrˈeɪz frʌm mˈeməri/",
  "to replicate": "/rˈepləkˌeɪt/",
  "to reschedule": "/riskˈedʒul/",
  "to resolve": "/rizˈɑːlv/",
  "to respectfully disagree": "/rɪspˈektfəli dɪsəɡrˈiː/",
  "to result in": "/rɪzˈʌlt ɪn/",
  "to rise sharply": "/raɪz ʃˈɑːrpli/",
  "to run over time": "/rʌn ˈoʊvər taɪm/",
  "to scale up": "/skeɪl ʌp/",
  "to scan": "/skæn/",
  "to shadow": "/ʃˈædˌoʊ/",
  "to share your screen": "/ʃer jɔːr skriːn/",
  "to sign off on": "/saɪn ɔːf ɑːn/",
  "to signpost": "/sˈaɪnpˌoʊst/",
  "to skim": "/skɪm/",
  "to spearhead": "/spˈɪrhˌed/",
  "to stem from": "/stem frʌm/",
  "to stick to the agenda": "/stɪk tuː ðə ədʒˈendə/",
  "to streamline": "/strˈiːmlˌaɪn/",
  "to substantiate": "/səbstˈæntʃiˌeɪt/",
  "to substantiate a claim": "/səbstˈæntʃiˌeɪt ə kleɪm/",
  "to sum up": "/sʌm ʌp/",
  "to summarise findings": "/ˈsʌməraɪz fˈaɪndɪŋz/",
  "to summarise in one sentence": "/ˈsʌməraɪz ɪn wʌn sˈentəns/",
  "to sweeten the deal": "/swˈiːtən ðə diːl/",
  "to take a message": "/teɪk ə mˈesədʒ/",
  "to take ownership": "/teɪk ˈoʊnərʃˌɪp/",
  "to take the initiative": "/teɪk ðə ˌɪnˈɪʃətɪv/",
  "to talk over someone": "/tɔːk ˈoʊvər sˈʌmwˌʌn/",
  "to touch base": "/tʌtʃ beɪs/",
  "to triangulate": "/traɪˈæŋɡjəleɪt/",
  "to tune in to an accent": "/tuːn ɪn tuː æn əksˈent/",
  "to walk away": "/wɔːk əwˈeɪ/",
  "to walk you through": "/wɔːk juː θruː/",
  "to warrant further research": "/wˈɔːrənt fˈɜːrðər risˈɜːrtʃ/",
  "to weigh the risk": "/weɪ ðə rɪsk/",
  "to weigh up": "/weɪ ʌp/",
  "to wrap up": "/ræp ʌp/",
  "topic sentence": "/tˈɑːpɪk sˈentəns/",
  "topic sentence scan": "/tˈɑːpɪk sˈentəns skæn/",
  "track record": "/træk rəkˈɔːrd/",
  "trade-off": "/trˈeɪdˌɔːf/",
  "transcript": "/trˈænskrˌɪpt/",
  "transparent method": "/trænspˈerənt mˈeθəd/",
  "under pressure": "/ˈʌndər prˈeʃər/",
  "underlying cause": "/ˌʌndərlˈaɪɪŋ kɑːz/",
  "unfortunately": "/ənfˈɔːrtʃənətli/",
  "unit price": "/jˈuːnət praɪs/",
  "unity": "/jˈuːnəti/",
  "unlikely to": "/ənlˈaɪkli tuː/",
  "up to a point": "/ʌp tuː ə pɔɪnt/",
  "valid concern": "/vˈælɪd kənsˈɜːrn/",
  "variability": "/veriəbˈɪlɪti/",
  "variable": "/vˈeriəbəl/",
  "verbatim": "/vərbˈeɪtəm/",
  "verbatim copying": "/vərbˈeɪtəm kˈɑːpiɪŋ/",
  "vested interest": "/vˈestɪd ˈɪntrəst/",
  "weak form": "/wiːk fɔːrm/",
  "whereas": "/werˈæz/",
  "win-win": "/wˌɪnwˈɪn/",
  "with immediate effect": "/wɪð ˌɪmˈiːdˌiːət ɪfˈekt/",
  "with reference to": "/wɪð rˈefərəns tuː/",
  "with regard to": "/wɪð rɪɡˈɑːrd tuː/",
  "with respect": "/wɪð rɪspˈekt/",
  "word limit": "/wɜːrd lˈɪmət/",
  "worst case": "/wɜːrst keɪs/",
  "year on year": "/jɪr ɑːn jɪr/",
};

export const getPurposePhraseIpa = (term: string): string => PURPOSE_PHRASE_IPA[term] ?? "";
