import { useMemo, useState } from "react";
import { Plus, Download, Save, ExternalLink, Pencil, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { useLanguage } from "@/contexts/LanguageContext";
import { downloadResearch, researchCsv, safeResearchUrl } from "@/lib/phdResearch";
import { toast } from "sonner";

export interface ResearchCitation { id: string; title: string; topic: string; authors: string | null; year: number | null; source_url: string | null; summary: string | null; tags: string[]; created_at: string }
interface Props { citations: ResearchCitation[]; onSave: (entry: Partial<ResearchCitation>) => Promise<boolean> }
export default function PhdEvidenceMatrix({ citations, onSave }: Props) {
  const { t } = useLanguage();
  const [query, setQuery] = useState("");
  const [draft, setDraft] = useState<Partial<ResearchCitation> | null>(null);
  const [busy, setBusy] = useState(false);
  const filtered = useMemo(() => citations.filter(c => `${c.title} ${c.authors ?? ""} ${c.topic} ${c.summary ?? ""} ${c.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query, citations]);
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold">{t("Ma trận bằng chứng", "Evidence matrix")}</h3><p className="text-sm text-muted-foreground">{filtered.length} / {citations.length} {t("tài liệu", "sources")}</p></div><div className="flex gap-2"><Button variant="outline" disabled={!filtered.length} onClick={() => downloadResearch(researchCsv([["Title", "Authors", "Year", "Topic", "URL", "Evidence / limitations", "Tags"], ...filtered.map(c => [c.title, c.authors ?? "", String(c.year ?? ""), c.topic, c.source_url ?? "", c.summary ?? "", c.tags.join("; ")])]), "research-evidence.csv", "text/csv;charset=utf-8")} className="gap-2"><Download className="w-4 h-4" />CSV</Button><Button className="gap-2" onClick={() => setDraft({ title: "", topic: "General", summary: "Research question:\nDesign / sample:\nMeasures:\nFindings:\nLimitations:\nResearch gap:\nVerification: Not verified", tags: [] })}><Plus className="w-4 h-4" />{t("Thêm tài liệu", "Add source")}</Button></div></div>
    <Input aria-label="Search evidence" placeholder={t("Tìm tiêu đề, tác giả, phương pháp…", "Search title, author, methods…")} value={query} onChange={e => setQuery(e.target.value)} />
    {draft && <div className="border border-border rounded-md bg-muted/20 p-5 space-y-4">
      <div className="grid gap-4 md:grid-cols-2">{[{ key: "title", label: t("Tiêu đề", "Title") }, { key: "authors", label: t("Tác giả", "Authors") }, { key: "topic", label: t("Chủ đề", "Topic") }, { key: "source_url", label: "DOI / URL" }].map(f => <div key={f.key} className="space-y-2"><Label htmlFor={`source-${f.key}`}>{f.label}</Label><Input id={`source-${f.key}`} value={String(draft[f.key as keyof ResearchCitation] ?? "")} onChange={e => setDraft({ ...draft, [f.key]: e.target.value })} /></div>)}<div className="space-y-2"><Label htmlFor="source-year">{t("Năm xuất bản", "Publication year")}</Label><Input id="source-year" type="number" min="1000" max="9999" value={draft.year ?? ""} onChange={e => setDraft({ ...draft, year: e.target.value ? Number(e.target.value) : null })} /></div><div className="space-y-2"><Label htmlFor="source-tags">Tags</Label><Input id="source-tags" value={draft.tags?.join(", ") ?? ""} onChange={e => setDraft({ ...draft, tags: e.target.value.split(",").map(s => s.trim()).filter(Boolean) })} /></div></div>
      <div className="space-y-2"><Label htmlFor="source-evidence">{t("Phương pháp, kết quả, giới hạn & khoảng trống", "Methods, findings, limitations & gap")}</Label><Textarea id="source-evidence" rows={9} value={draft.summary ?? ""} onChange={e => setDraft({ ...draft, summary: e.target.value })} /></div>
      <div className="flex gap-2"><Button disabled={busy || !draft.title?.trim()} className="gap-2" onClick={async () => { if (draft.source_url && !safeResearchUrl(draft.source_url)) { toast.error(t("URL cần bắt đầu bằng http hoặc https", "URL must use http or https")); return; } if (draft.year != null && (!Number.isInteger(draft.year) || draft.year < 1000 || draft.year > 9999)) { toast.error(t("Năm không hợp lệ", "Invalid publication year")); return; } setBusy(true); try { if (await onSave(draft)) setDraft(null); } finally { setBusy(false); } }}>{busy ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}{t("Lưu tài liệu", "Save source")}</Button><Button variant="ghost" onClick={() => setDraft(null)}>{t("Hủy", "Cancel")}</Button></div>
    </div>}
    <div className="overflow-x-auto border-y border-border"><table className="w-full min-w-[760px] text-sm"><thead className="bg-muted/50"><tr>{[t("Tài liệu", "Source"), t("Chủ đề", "Topic"), t("Bằng chứng & giới hạn", "Evidence & limitations"), ""].map((s,i) => <th key={i} className="text-left p-4 font-medium">{s}</th>)}</tr></thead><tbody>{filtered.map(c => <tr key={c.id} className="border-t border-border align-top"><td className="p-4 w-[30%]"><div className="font-semibold">{c.title}</div><div className="mt-1 text-muted-foreground">{c.authors ?? t("Chưa có tác giả", "Author not recorded")} · {c.year ?? "n.d."}</div>{safeResearchUrl(c.source_url) && <a href={safeResearchUrl(c.source_url)} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex items-center gap-1 text-primary"><ExternalLink className="w-3 h-3" />{t("Nguồn gốc", "Original source")}</a>}</td><td className="p-4 w-[18%] text-muted-foreground">{c.topic}<div className="mt-2 text-xs">{c.tags.join(" · ")}</div></td><td className="p-4"><div className="whitespace-pre-wrap max-h-64 overflow-y-auto leading-relaxed">{c.summary || t("Chưa có ghi chú bằng chứng", "No evidence notes")}</div></td><td className="p-4"><Button variant="ghost" size="icon" title={t("Sửa tài liệu", "Edit source")} onClick={() => setDraft(c)}><Pencil className="w-4 h-4" /></Button></td></tr>)}</tbody></table></div>
    {!filtered.length && <p className="py-8 text-center text-muted-foreground">{t("Chưa có tài liệu phù hợp.", "No matching sources.")}</p>}
  </div>;
}