import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";
import { motion } from "framer-motion";
import { useState } from "react";
import { Brain, FileText, Mic, Send, Loader2, AlertCircle, BookOpen, ChevronDown, ChevronUp, Download, Copy, Check } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { supabase } from "@/integrations/supabase/client";
import SpeakingGrader from "@/components/SpeakingGrader";
import ReactMarkdown from "react-markdown";

interface CriteriaDetail {
  score: number;
  label: string;
  strengths: string[];
  weaknesses: string[];
  suggestions: string[];
}

interface GradingResult {
  overall: number;
  criteria: CriteriaDetail[];
  errors: { error: string; correction: string; category: string }[];
  upgraded: string;
  advice: string;
}

const AIGrading = () => {
  const { t } = useLanguage();
  const [mode, setMode] = useState<"writing" | "speaking">("writing");
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<GradingResult | null>(null);
  const [expandedCriteria, setExpandedCriteria] = useState<number | null>(null);
  const [showFullUpgraded, setShowFullUpgraded] = useState(false);
  const [copied, setCopied] = useState(false);

  // Upgraded essay is now provided by AI and always in English

  const handleGrade = async () => {
    if (!text.trim()) return;
    setLoading(true);

    try {
      const { data, error } = await supabase.functions.invoke("grade-writing", {
        body: { essay: text },
      });
      if (error) throw error;
      setResult(data as GradingResult);
    } catch (e) {
      console.error("Grading error:", e);
      // Keep a minimal fallback
      setResult({
        overall: 6.0,
        criteria: [
          { score: 6.0, label: "Task Achievement", strengths: ["Addresses the topic"], weaknesses: ["Needs more depth"], suggestions: ["Add specific examples"] },
          { score: 6.0, label: "Coherence & Cohesion", strengths: ["Basic structure present"], weaknesses: ["Limited linking words"], suggestions: ["Use Furthermore, Moreover, Nevertheless"] },
          { score: 6.0, label: "Lexical Resource", strengths: ["Adequate vocabulary"], weaknesses: ["Repetitive words"], suggestions: ["Replace 'good' with 'beneficial'"] },
          { score: 6.0, label: "Grammatical Range & Accuracy", strengths: ["Basic grammar correct"], weaknesses: ["Limited complex sentences"], suggestions: ["Practice conditionals and relative clauses"] },
        ],
        errors: [{ error: "very good", correction: "highly beneficial", category: "Vocab" }],
        upgraded: "Please try again when AI service is available.",
        advice: "Focus on expanding vocabulary and sentence variety.",
      });
    }

    setLoading(false);
    setExpandedCriteria(null);
    setShowFullUpgraded(false);
  };

  const handleDownloadPDF = () => {
    if (!result) return;

    // Build HTML for PDF-like rendering
    const html = `
<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>IELTS Writing Report - HaiEduTech</title>
<style>
  body { font-family: Georgia, serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
  h1 { color: #0d7377; border-bottom: 3px solid #0d7377; padding-bottom: 10px; }
  h2 { color: #0d7377; margin-top: 30px; }
  .score-box { background: #f0fdf4; border: 2px solid #0d7377; border-radius: 12px; padding: 20px; text-align: center; margin: 20px 0; }
  .score-box .number { font-size: 48px; font-weight: bold; color: #0d7377; }
  .criteria { background: #f8fafc; border-radius: 8px; padding: 16px; margin: 12px 0; }
  .criteria h3 { margin: 0 0 8px 0; display: flex; justify-content: space-between; }
  .criteria h3 span { color: #0d7377; }
  .strength { color: #16a34a; } .weakness { color: #dc2626; } .suggestion { color: #2563eb; }
  .error-row { display: flex; gap: 8px; align-items: center; padding: 6px 0; border-bottom: 1px solid #e5e7eb; }
  .error-cat { background: #fee2e2; color: #dc2626; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }
  .error-cat.vocab { background: #fef3c7; color: #d97706; }
  .error-cat.cohesion { background: #dbeafe; color: #2563eb; }
  .upgraded { background: #f0fdf4; border-left: 4px solid #0d7377; padding: 20px; margin: 16px 0; line-height: 1.8; }
  .upgraded strong, .upgraded b { color: #0d7377; background: #e0f7fa; padding: 1px 4px; border-radius: 3px; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 12px; }
</style></head><body>
<h1>📝 IELTS Writing Report</h1>
<p style="color:#6b7280;">Generated by HaiEduTech Smart IELTS Grading</p>

<div class="score-box">
  <div>Overall Band Score</div>
  <div class="number">${result.overall}</div>
</div>

<h2>📊 Criteria Breakdown</h2>
${result.criteria.map(c => `
<div class="criteria">
  <h3>${c.label} <span>${c.score}</span></h3>
  <p class="strength">✅ Strengths:</p>
  <ul>${c.strengths.map(s => `<li>${s}</li>`).join("")}</ul>
  <p class="weakness">❌ Weaknesses:</p>
  <ul>${c.weaknesses.map(w => `<li>${w}</li>`).join("")}</ul>
  <p class="suggestion">💡 Suggestions:</p>
  <ul>${c.suggestions.map(s => `<li>${s}</li>`).join("")}</ul>
</div>`).join("")}

<h2>🔍 Error Highlights</h2>
${result.errors.map(e => `
<div class="error-row">
  <span class="error-cat ${e.category.toLowerCase()}">${e.category}</span>
  <span><s style="color:#dc2626">"${e.error}"</s> → <b style="color:#16a34a">"${e.correction}"</b></span>
</div>`).join("")}

<h2>✨ Band 8.0+ Upgraded Version</h2>
<div class="upgraded">${result.upgraded.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>')}</div>

<h2>🎯 Next Steps</h2>
<p>${result.advice}</p>

<div class="footer">
  <p>© ${new Date().getFullYear()} HaiEduTech - Smart IELTS Grading | Generated on ${new Date().toLocaleDateString()}</p>
</div>
</body></html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (win) {
      setTimeout(() => {
        win.print();
        URL.revokeObjectURL(url);
      }, 500);
    } else {
      // Fallback: download as HTML
      const a = document.createElement("a");
      a.href = url;
      a.download = "IELTS_Writing_Report.html";
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  const handleCopyUpgraded = () => {
    if (!result) return;
    navigator.clipboard.writeText(result.upgraded);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getScoreColor = (score: number) => {
    if (score >= 7.5) return "text-green-600";
    if (score >= 6.5) return "text-primary";
    if (score >= 5.5) return "text-yellow-600";
    return "text-destructive";
  };

  return (
    <div className="min-h-screen bg-background">
      <SEO title="AI Chấm IELTS Writing & Speaking Theo 4 Tiêu Chí | HaiEduTech" description="Smart IELTS Grading: AI chấm Writing & Speaking theo 4 tiêu chí chuẩn (TR/CC, LR, GRA, ...). Điểm số dạng decimal (6.5, 7.0), feedback chi tiết, xuất PDF." path="/ai-grading" />
      <Navbar />
      <div className="pt-6 pb-16">
        <div className="container mx-auto px-6">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="max-w-6xl mx-auto">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-primary/30 bg-primary/5 text-primary text-sm font-semibold mb-4">
              <Brain className="w-4 h-4" /> {t("Hệ thống chấm điểm", "Expert Scoring System")}
            </div>
            <h1 className="text-5xl font-display font-bold mb-4 text-foreground">
              Smart{" "}
              <span className="text-gradient">IELTS Grading</span>
            </h1>
            <p className="text-lg text-muted-foreground mb-10">
              {t(
                "Nộp bài viết hoặc nói để nhận phản hồi cấp giám khảo ngay lập tức.",
                "Submit your writing or speaking sample for instant examiner-level feedback."
              )}
            </p>

            {/* Link to Writing Practice */}
            <div className="mb-6 p-4 bg-primary/5 border border-primary/20 rounded-xl flex flex-col sm:flex-row items-start sm:items-center gap-3">
              <BookOpen className="w-5 h-5 text-primary shrink-0" />
              <div className="flex-1">
                <p className="text-sm font-medium text-foreground">
                  {t("Muốn luyện viết với đề bài + hướng dẫn chi tiết?", "Want guided writing practice with prompts & vocabulary?")}
                </p>
                <p className="text-xs text-muted-foreground">
                  {t("Thử tính năng Luyện viết IELTS mới với hệ thống tạo đề, hướng dẫn từng bước và bộ từ vựng.", "Try IELTS Writing Practice with system-generated prompts, step-by-step guides, and vocabulary banks.")}
                </p>
              </div>
              <a href="/ielts-writing-practice" className="inline-flex items-center gap-1 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 transition-colors shrink-0">
                {t("Luyện viết ngay", "Start Practice")} →
              </a>
            </div>

            <div className="flex gap-3 mb-8">
              <button
                onClick={() => setMode("writing")}
                className={`flex items-center gap-2 px-6 py-3 rounded-xl text-base font-semibold transition-all ${
                  mode === "writing" ? "bg-primary text-primary-foreground shadow-lg" : "bg-secondary text-secondary-foreground hover:bg-primary/10"
                }`}
              >
                <FileText className="w-5 h-5" /> Writing
              </button>
              <button
                onClick={() => setMode("speaking")}
                className={`flex items-center gap-2 px-6 py-3 rounded-xl text-base font-semibold transition-all ${
                  mode === "speaking" ? "bg-primary text-primary-foreground shadow-lg" : "bg-secondary text-secondary-foreground hover:bg-primary/10"
                }`}
              >
                <Mic className="w-5 h-5" /> Speaking
              </button>
            </div>

            {mode === "speaking" ? (
              <SpeakingGrader />
            ) : (
              <div className="grid lg:grid-cols-2 gap-8">
                {/* Input panel */}
                <div className="glass-card rounded-2xl p-8">
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-lg font-bold text-foreground">{t("Bài viết của bạn", "Your Essay")}</h3>
                    <span className="text-sm text-muted-foreground font-mono">{text.split(/\s+/).filter(Boolean).length} {t("từ", "words")}</span>
                  </div>
                  <textarea
                    value={text}
                    onChange={(e) => setText(e.target.value)}
                    placeholder={t("Dán bài IELTS Writing Task 2 của bạn tại đây...", "Paste your IELTS Writing Task 2 essay here...")}
                    className="w-full h-80 bg-secondary rounded-xl p-5 text-base text-foreground placeholder:text-muted-foreground resize-none border border-border focus:border-primary/50 focus:outline-none transition-colors leading-relaxed"
                  />
                  <button
                    onClick={handleGrade}
                    disabled={loading || !text.trim()}
                    className="w-full mt-5 flex items-center justify-center gap-2 px-6 py-3.5 rounded-xl bg-primary text-primary-foreground text-base font-bold disabled:opacity-50 hover:brightness-110 transition-all shadow-lg"
                  >
                    {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Send className="w-5 h-5" />}
                    {loading ? t("Đang phân tích...", "Analyzing...") : t("Chấm bài của tôi", "Grade My Essay")}
                  </button>
                </div>

                {/* Result panel */}
                <div className="glass-card rounded-2xl p-8">
                  {!result && !loading && (
                    <div className="flex flex-col items-center justify-center h-full text-center py-16">
                      <Brain className="w-16 h-16 text-muted-foreground/30 mb-6" />
                      <p className="text-base text-muted-foreground">{t("Nộp bài viết để xem phản hồi của hệ thống", "Submit your essay to see scoring feedback")}</p>
                    </div>
                  )}

                  {loading && (
                    <div className="flex flex-col items-center justify-center h-full text-center py-16">
                      <Loader2 className="w-12 h-12 text-primary animate-spin mb-6" />
                      <p className="text-base text-muted-foreground">{t("Hệ thống đang phân tích bài viết...", "System is analyzing your essay...")}</p>
                    </div>
                  )}

                  {result && !loading && (
                    <div className="space-y-5 overflow-y-auto max-h-[800px]">
                      {/* Overall score */}
                      <div className="bg-secondary rounded-2xl p-6">
                        <div className="flex items-center justify-between mb-4">
                          <span className="text-base font-bold text-foreground">{t("Điểm tổng", "Overall Band Score")}</span>
                          <div className="flex items-center gap-3">
                            <button
                              onClick={handleDownloadPDF}
                              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary/10 text-primary text-sm font-semibold hover:bg-primary/20 transition-colors"
                            >
                              <Download className="w-4 h-4" />
                              {t("Tải báo cáo", "Download")}
                            </button>
                            <span className={`text-5xl font-display font-bold ${getScoreColor(result.overall)}`}>{result.overall}</span>
                          </div>
                        </div>
                        <div className="grid grid-cols-2 gap-3">
                          {result.criteria.map((c) => (
                            <div key={c.label} className="flex justify-between text-sm bg-background rounded-lg p-2.5">
                              <span className="text-muted-foreground">{c.label}</span>
                              <span className={`font-mono font-bold ${getScoreColor(c.score)}`}>{c.score}</span>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Detailed criteria */}
                      <div className="space-y-3">
                        {result.criteria.map((c, i) => (
                          <div key={c.label} className="bg-secondary rounded-2xl overflow-hidden">
                            <button
                              onClick={() => setExpandedCriteria(expandedCriteria === i ? null : i)}
                              className="w-full flex items-center justify-between p-4 text-left hover:bg-primary/5 transition-colors"
                            >
                              <div className="flex items-center gap-3">
                                <span className={`text-lg font-bold font-mono ${getScoreColor(c.score)}`}>{c.score}</span>
                                <span className="text-base font-semibold text-foreground">{c.label}</span>
                              </div>
                              {expandedCriteria === i ? <ChevronUp className="w-5 h-5 text-muted-foreground" /> : <ChevronDown className="w-5 h-5 text-muted-foreground" />}
                            </button>
                            {expandedCriteria === i && (
                              <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} className="px-5 pb-5 space-y-4">
                                <div>
                                  <p className="text-xs uppercase font-bold text-green-600 mb-2 tracking-wider">{t("Điểm mạnh", "Strengths")}</p>
                                  {c.strengths.map((s, j) => (
                                    <p key={j} className="text-sm text-secondary-foreground flex items-start gap-2 mb-1.5"><span className="text-green-500 mt-0.5">✓</span> {s}</p>
                                  ))}
                                </div>
                                <div>
                                  <p className="text-xs uppercase font-bold text-destructive mb-2 tracking-wider">{t("Điểm yếu", "Weaknesses")}</p>
                                  {c.weaknesses.map((w, j) => (
                                    <p key={j} className="text-sm text-secondary-foreground flex items-start gap-2 mb-1.5"><span className="text-destructive mt-0.5">✗</span> {w}</p>
                                  ))}
                                </div>
                                <div>
                                  <p className="text-xs uppercase font-bold text-primary mb-2 tracking-wider">{t("Gợi ý cải thiện", "Suggestions")}</p>
                                  {c.suggestions.map((s, j) => (
                                    <p key={j} className="text-sm text-secondary-foreground flex items-start gap-2 mb-1.5"><span className="text-primary mt-0.5">→</span> {s}</p>
                                  ))}
                                </div>
                              </motion.div>
                            )}
                          </div>
                        ))}
                      </div>

                      {/* Error highlights */}
                      <div className="bg-secondary rounded-2xl p-6">
                        <h4 className="text-base font-bold text-foreground mb-4 flex items-center gap-2">
                          <AlertCircle className="w-5 h-5 text-destructive" /> {t("Lỗi nổi bật", "Error Highlights")}
                        </h4>
                        <div className="space-y-3">
                          {result.errors.map((e, i) => (
                            <div key={i} className="flex items-start gap-3 text-sm">
                              <span className={`px-2 py-1 rounded-md font-semibold text-xs shrink-0 ${
                                e.category === "Grammar" ? "bg-destructive/20 text-destructive" :
                                e.category === "Vocab" ? "bg-yellow-500/20 text-yellow-600" :
                                "bg-sky-500/20 text-sky-600"
                              }`}>{e.category}</span>
                              <span className="text-secondary-foreground">
                                <span className="line-through text-destructive/70">"{e.error}"</span>
                                {" → "}
                                <span className="text-green-600 font-medium">"{e.correction}"</span>
                              </span>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Upgraded version */}
                      <div className="bg-secondary rounded-2xl p-6">
                        <div className="flex items-center justify-between mb-4">
                          <h4 className="text-base font-bold text-foreground flex items-center gap-2">
                            <Check className="w-5 h-5 text-primary" /> {t("Phiên bản Band 8.0+", "Band 8.0+ Version")}
                          </h4>
                          <div className="flex gap-2">
                            <button
                              onClick={handleCopyUpgraded}
                              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary/10 text-primary text-sm font-semibold hover:bg-primary/20 transition-colors"
                            >
                              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                              {copied ? t("Đã sao chép", "Copied") : t("Sao chép", "Copy")}
                            </button>
                            <button
                              onClick={() => setShowFullUpgraded(!showFullUpgraded)}
                              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary/10 text-primary text-sm font-semibold hover:bg-primary/20 transition-colors"
                            >
                              {showFullUpgraded ? t("Thu gọn", "Collapse") : t("Xem đầy đủ", "View Full")}
                            </button>
                          </div>
                        </div>
                        <div className={`text-sm text-secondary-foreground leading-relaxed ${!showFullUpgraded ? "max-h-40 overflow-hidden relative" : ""}`}>
                          <div className="prose prose-sm max-w-none dark:prose-invert">
                            <ReactMarkdown>{result.upgraded}</ReactMarkdown>
                          </div>
                          {!showFullUpgraded && (
                            <div className="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t from-secondary to-transparent" />
                          )}
                        </div>
                      </div>

                      {/* Advice */}
                      <div className="bg-primary/5 border border-primary/20 rounded-2xl p-6">
                        <h4 className="text-base font-bold text-primary mb-2">{t("Bước tiếp theo", "Next Steps")}</h4>
                        <p className="text-sm text-secondary-foreground leading-relaxed">{result.advice}</p>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}
          </motion.div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default AIGrading;
