// TOEIC Lecture Detail View — Strategy, Practice & Quiz
import { useState, useMemo } from "react";
import { logStudentActivity } from "@/hooks/useActivityLogger";
import { useParams, useNavigate, Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  ArrowLeft, ChevronRight, AlertTriangle, BookOpen, Target, Lightbulb,
  Zap, Download, CheckCircle, XCircle, Briefcase, Clock, Timer
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useLanguage } from "@/contexts/LanguageContext";
import { allToeicLectures } from "@/data/toeicLecturesData";
import ToeicLectureDiagram from "@/components/toeic/ToeicLectureDiagram";

const LEVEL_LABELS: Record<string, { label: string; labelVi: string }> = {
  foundation: { label: "Foundation", labelVi: "Nền tảng" },
  intermediate: { label: "Intermediate", labelVi: "Trung cấp" },
  advanced: { label: "Advanced", labelVi: "Nâng cao" },
};

const ToeicLectureView = () => {
  const { lectureId } = useParams();
  const navigate = useNavigate();
  const { t } = useLanguage();

  const lecture = useMemo(() => allToeicLectures.find(l => l.id === lectureId), [lectureId]);
  const lectureIndex = useMemo(() => allToeicLectures.findIndex(l => l.id === lectureId), [lectureId]);
  const nextLecture = lectureIndex >= 0 && lectureIndex < allToeicLectures.length - 1 ? allToeicLectures[lectureIndex + 1] : null;

  // Quiz state
  const [quizAnswers, setQuizAnswers] = useState<Record<number, number>>({});
  const [quizSubmitted, setQuizSubmitted] = useState(false);

  // Practice state
  const [practiceAnswers, setPracticeAnswers] = useState<Record<number, number>>({});
  const [practiceRevealed, setPracticeRevealed] = useState<Set<number>>(new Set());

  // Speed timer state
  const [timerActive, setTimerActive] = useState(false);
  const [timerSeconds, setTimerSeconds] = useState(0);

  if (!lecture) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4">
          <BookOpen className="w-16 h-16 text-muted-foreground" />
          <h2 className="text-xl font-semibold text-foreground">{t("Không tìm thấy bài giảng", "Lecture not found")}</h2>
          <Button onClick={() => navigate("/toeic-lectures")} variant="outline">
            <ArrowLeft className="w-4 h-4 mr-2" /> {t("Quay lại", "Go back")}
          </Button>
        </div>
        <Footer />
      </div>
    );
  }

  const quizScore = quizSubmitted ? Object.entries(quizAnswers).filter(([i, a]) => a === lecture.quiz[Number(i)]?.answer).length : 0;

  const handleQuizSubmit = () => {
    setQuizSubmitted(true);
    const score = Object.entries(quizAnswers).filter(([i, a]) => a === lecture.quiz[Number(i)]?.answer).length;
    logStudentActivity({
      activityType: "toeic_lecture_quiz",
      activityId: lecture.id,
      score,
      maxScore: lecture.quiz.length,
      domain: "english",
    });
  };
  const handleQuizReset = () => { setQuizAnswers({}); setQuizSubmitted(false); };

  const revealPractice = (idx: number) => setPracticeRevealed(prev => new Set(prev).add(idx));

  const downloadCheatSheet = () => {
    const content = [
      `📋 TOEIC CHEAT SHEET: ${lecture.title}`,
      `${"=".repeat(50)}`,
      "",
      ...lecture.cheatSheetPoints.map((p, i) => `${i + 1}. ${p}`),
      "",
      `⚡ Teacher Hai's Pro-Speed Tip:`,
      lecture.proSpeedTip,
      "",
      `🎯 Target Score: ${lecture.targetScore}`,
      "",
      "— Generated by HaiEduTech.com —",
    ].join("\n");
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `TOEIC-CheatSheet-${lecture.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const levelInfo = LEVEL_LABELS[lecture.level];

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="pt-24 pb-16">
        {/* Header */}
        <section className="relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-blue-950/80 via-slate-900/60 to-indigo-950/80" />
          <div className="relative container mx-auto px-4 py-10">
            {/* Breadcrumb */}
            <div className="flex items-center gap-2 text-sm text-blue-300/70 mb-6">
              <Link to="/toeic-lectures" className="hover:text-blue-300 transition-colors">
                {t("TOEIC Lectures", "TOEIC Lectures")}
              </Link>
              <ChevronRight className="w-4 h-4" />
              <span className="text-white/80 truncate">{t(lecture.titleVi, lecture.title)}</span>
            </div>

            <div className="flex flex-wrap items-center gap-3 mb-4">
              <span className="text-3xl">{lecture.icon}</span>
              {lecture.parts.map(p => (
                <Badge key={p} className="bg-blue-500/20 text-blue-300 border-blue-500/30">{p}</Badge>
              ))}
              <Badge className="bg-white/10 text-white/80">{t(levelInfo.labelVi, levelInfo.label)}</Badge>
              <Badge className="bg-amber-500/20 text-amber-300 border-amber-500/30">
                <Target className="w-3 h-3 mr-1" /> {lecture.targetScore}
              </Badge>
              <div className="flex items-center gap-1 text-sm text-muted-foreground">
                <Clock className="w-4 h-4" /> {lecture.duration}
              </div>
            </div>

            <h1 className="text-2xl md:text-3xl lg:text-4xl font-display font-bold text-white mb-3" style={{ lineHeight: "1.4" }}>
              {t(lecture.titleVi, lecture.title)}
            </h1>
            <p className="text-blue-200/70 max-w-2xl" style={{ fontSize: "20px", lineHeight: "1.8" }}>
              {t(lecture.descriptionVi, lecture.description)}
            </p>
          </div>
        </section>

        {/* Content Tabs */}
        <section className="container mx-auto px-4 py-8">
          <Tabs defaultValue="traps" className="space-y-6">
            <TabsList className="bg-white/5 border border-white/10 p-1 flex-wrap h-auto gap-1">
              <TabsTrigger value="traps" className="data-[state=active]:bg-red-500/20 data-[state=active]:text-red-300">
                <AlertTriangle className="w-4 h-4 mr-1.5" /> {t("Cảnh báo bẫy", "Trap Alerts")}
              </TabsTrigger>
              <TabsTrigger value="technique" className="data-[state=active]:bg-blue-500/20 data-[state=active]:text-blue-300">
                <BookOpen className="w-4 h-4 mr-1.5" /> {t("Kỹ thuật", "Technique")}
              </TabsTrigger>
              <TabsTrigger value="practice" className="data-[state=active]:bg-emerald-500/20 data-[state=active]:text-emerald-300">
                <Target className="w-4 h-4 mr-1.5" /> {t("Luyện tập", "Practice")}
              </TabsTrigger>
              <TabsTrigger value="vocab" className="data-[state=active]:bg-amber-500/20 data-[state=active]:text-amber-300">
                <Briefcase className="w-4 h-4 mr-1.5" /> {t("Từ vựng", "Vocabulary")}
              </TabsTrigger>
              <TabsTrigger value="quiz" className="data-[state=active]:bg-purple-500/20 data-[state=active]:text-purple-300">
                <Zap className="w-4 h-4 mr-1.5" /> Quiz
              </TabsTrigger>
            </TabsList>

            {/* Trap Alerts Tab */}
            <TabsContent value="traps" className="space-y-4">
              <h2 className="text-xl font-bold text-red-300 flex items-center gap-2">
                <AlertTriangle className="w-5 h-5" /> {t("🚨 Cảnh báo bẫy thường gặp", "🚨 Common Trap Alerts")}
              </h2>
              {lecture.trapAlerts.map((trap, i) => (
                <motion.div key={i} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.1 }}
                  className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                  <h3 className="text-lg font-semibold text-red-300 mb-2" style={{ fontSize: "20px", lineHeight: "1.8" }}>
                    ⚠️ {t(trap.trapVi, trap.trap)}
                  </h3>
                  <p className="text-muted-foreground" style={{ fontSize: "20px", lineHeight: "1.8" }}>
                    {t(trap.whyVi, trap.why)}
                  </p>
                </motion.div>
              ))}

              {/* Business context */}
              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 mt-6">
                <h3 className="text-lg font-semibold text-blue-300 flex items-center gap-2 mb-2">
                  <Briefcase className="w-5 h-5" /> {t("Bối cảnh kinh doanh", "Business Context")}
                </h3>
                <p className="text-muted-foreground" style={{ fontSize: "20px", lineHeight: "1.8" }}>
                  {t(lecture.businessContextVi, lecture.businessContext)}
                </p>
              </div>
            </TabsContent>

            {/* Core Technique Tab */}
            <TabsContent value="technique" className="space-y-4">
              <h2 className="text-xl font-bold text-blue-300 flex items-center gap-2">
                <BookOpen className="w-5 h-5" /> {t("Kỹ thuật cốt lõi", "Core Technique")}
              </h2>

              {/* === SVG diagram minh họa (nếu có) === */}
              <ToeicLectureDiagram lectureId={lecture.id} />

              {lecture.coreTechnique.map((step, i) => (
                <motion.div key={i} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }}
                  className="rounded-xl border border-blue-500/15 bg-white/5 p-5">
                  <div className="flex items-start gap-4">
                    <div className="w-10 h-10 rounded-full bg-blue-500/20 text-blue-300 flex items-center justify-center font-bold text-lg shrink-0">
                      {step.step}
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-white mb-1" style={{ fontSize: "20px", lineHeight: "1.8" }}>
                        {t(step.titleVi, step.title)}
                      </h3>
                      <p className="text-muted-foreground mb-2" style={{ fontSize: "20px", lineHeight: "1.8" }}>
                        {t(step.descriptionVi, step.description)}
                      </p>
                      {step.example && (
                        <div className="bg-blue-500/10 rounded-lg p-3 mt-2 text-sm text-blue-200 border border-blue-500/20">
                          💡 {step.example}
                        </div>
                      )}
                    </div>
                  </div>
                </motion.div>
              ))}

              {/* Pro Speed Tip */}
              <div className="rounded-xl border border-amber-500/20 bg-gradient-to-r from-amber-500/10 to-orange-500/10 p-5 mt-6">
                <h3 className="text-lg font-semibold text-amber-300 flex items-center gap-2 mb-2">
                  <Zap className="w-5 h-5" /> Teacher Hai's Pro-Speed Tip
                </h3>
                <p className="text-amber-100/80" style={{ fontSize: "20px", lineHeight: "1.8" }}>
                  {t(lecture.proSpeedTipVi, lecture.proSpeedTip)}
                </p>
              </div>
            </TabsContent>

            {/* Practice Tab */}
            <TabsContent value="practice" className="space-y-4">
              <h2 className="text-xl font-bold text-emerald-300 flex items-center gap-2">
                <Target className="w-5 h-5" /> {t("Bài tập thực hành", "Practice Set")}
              </h2>
              {lecture.practiceSet.map((q, i) => (
                <motion.div key={i} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }}
                  className="rounded-xl border border-white/10 bg-white/5 p-5">
                  <p className="text-sm text-blue-300/80 mb-2 italic">{t(q.contextVi, q.context)}</p>
                  <p className="text-white font-medium mb-3" style={{ fontSize: "20px", lineHeight: "1.8" }}>{q.question}</p>
                  <div className="space-y-2 mb-3">
                    {q.options.map((opt, oi) => {
                      const selected = practiceAnswers[i] === oi;
                      const revealed = practiceRevealed.has(i);
                      const isCorrect = oi === q.answer;
                      return (
                        <button
                          key={oi}
                          onClick={() => { if (!revealed) setPracticeAnswers(prev => ({ ...prev, [i]: oi })); }}
                          className={`w-full text-left px-4 py-2.5 rounded-lg border transition-all text-sm ${
                            revealed && isCorrect ? "border-emerald-500/40 bg-emerald-500/15 text-emerald-300" :
                            revealed && selected && !isCorrect ? "border-red-500/40 bg-red-500/15 text-red-300" :
                            selected ? "border-blue-500/40 bg-blue-500/15 text-blue-300" :
                            "border-white/10 bg-white/5 text-foreground hover:bg-white/10"
                          }`}
                          disabled={revealed}
                        >
                          <span className="font-medium mr-2">{String.fromCharCode(65 + oi)}.</span>
                          {opt}
                          {revealed && isCorrect && <CheckCircle className="w-4 h-4 inline ml-2 text-emerald-400" />}
                          {revealed && selected && !isCorrect && <XCircle className="w-4 h-4 inline ml-2 text-red-400" />}
                        </button>
                      );
                    })}
                  </div>
                  {practiceAnswers[i] !== undefined && !practiceRevealed.has(i) && (
                    <Button size="sm" onClick={() => revealPractice(i)} className="bg-blue-500/20 text-blue-300 hover:bg-blue-500/30">
                      {t("Kiểm tra", "Check Answer")}
                    </Button>
                  )}
                  {practiceRevealed.has(i) && (
                    <div className="mt-3 p-3 rounded-lg bg-blue-500/10 border border-blue-500/20 text-sm text-blue-200">
                      💡 {t(q.explanationVi, q.explanation)}
                    </div>
                  )}
                </motion.div>
              ))}
            </TabsContent>

            {/* Vocabulary Tab */}
            <TabsContent value="vocab" className="space-y-4">
              <h2 className="text-xl font-bold text-amber-300 flex items-center gap-2">
                <Briefcase className="w-5 h-5" /> {t("Từ vựng kinh doanh", "Business Vocabulary")}
              </h2>
              {lecture.vocabHighlights.length === 0 ? (
                <p className="text-muted-foreground">{t("Bài này tập trung vào chiến lược, không có từ vựng riêng.", "This lesson focuses on strategy, no dedicated vocabulary.")}</p>
              ) : (
                <div className="grid gap-3">
                  {lecture.vocabHighlights.map((v, i) => (
                    <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.05 }}
                      className="rounded-xl border border-amber-500/15 bg-white/5 p-4">
                      <div className="flex flex-wrap items-center gap-2 mb-2">
                        <span className="text-lg font-bold text-amber-300">{v.word}</span>
                        {v.businessContext && (
                          <Badge variant="outline" className="text-xs bg-blue-500/10 text-blue-300 border-blue-500/20">{v.businessContext}</Badge>
                        )}
                      </div>
                      <p className="text-sm text-foreground mb-1">{v.definition} — <span className="text-muted-foreground">{v.definitionVi}</span></p>
                      <p className="text-sm text-muted-foreground italic">📝 {v.example}</p>
                    </motion.div>
                  ))}
                </div>
              )}
            </TabsContent>

            {/* Quiz Tab */}
            <TabsContent value="quiz" className="space-y-4">
              <div className="flex items-center justify-between">
                <h2 className="text-xl font-bold text-purple-300 flex items-center gap-2">
                  <Zap className="w-5 h-5" /> {t("Kiểm tra nhanh", "Quick Quiz")}
                </h2>
                {quizSubmitted && (
                  <div className="flex items-center gap-3">
                    <Badge className={`text-sm px-3 py-1 ${quizScore === lecture.quiz.length ? "bg-emerald-500/20 text-emerald-300" : quizScore >= lecture.quiz.length / 2 ? "bg-amber-500/20 text-amber-300" : "bg-red-500/20 text-red-300"}`}>
                      {quizScore}/{lecture.quiz.length} {t("đúng", "correct")}
                    </Badge>
                    <Button size="sm" variant="outline" onClick={handleQuizReset} className="border-white/10">
                      {t("Làm lại", "Retry")}
                    </Button>
                  </div>
                )}
              </div>

              {lecture.quiz.map((q, qi) => (
                <motion.div key={qi} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: qi * 0.05 }}
                  className="rounded-xl border border-white/10 bg-white/5 p-5">
                  <p className="text-white font-medium mb-3" style={{ fontSize: "20px", lineHeight: "1.8" }}>
                    {qi + 1}. {q.question}
                  </p>
                  <div className="space-y-2">
                    {q.options.map((opt, oi) => {
                      const selected = quizAnswers[qi] === oi;
                      const isCorrect = oi === q.answer;
                      return (
                        <button
                          key={oi}
                          onClick={() => { if (!quizSubmitted) setQuizAnswers(prev => ({ ...prev, [qi]: oi })); }}
                          className={`w-full text-left px-4 py-2.5 rounded-lg border transition-all text-sm ${
                            quizSubmitted && isCorrect ? "border-emerald-500/40 bg-emerald-500/15 text-emerald-300" :
                            quizSubmitted && selected && !isCorrect ? "border-red-500/40 bg-red-500/15 text-red-300" :
                            selected ? "border-blue-500/40 bg-blue-500/15 text-blue-300" :
                            "border-white/10 bg-white/5 text-foreground hover:bg-white/10"
                          }`}
                          disabled={quizSubmitted}
                        >
                          {opt}
                          {quizSubmitted && isCorrect && <CheckCircle className="w-4 h-4 inline ml-2" />}
                          {quizSubmitted && selected && !isCorrect && <XCircle className="w-4 h-4 inline ml-2" />}
                        </button>
                      );
                    })}
                  </div>
                  {quizSubmitted && (
                    <p className="mt-2 text-sm text-blue-200/80 bg-blue-500/10 rounded-lg p-3 border border-blue-500/20">
                      💡 {q.explanation}
                    </p>
                  )}
                </motion.div>
              ))}

              {!quizSubmitted && Object.keys(quizAnswers).length > 0 && (
                <Button onClick={handleQuizSubmit} className="bg-purple-500/20 text-purple-300 hover:bg-purple-500/30 border border-purple-500/30">
                  {t("Nộp bài", "Submit Quiz")}
                </Button>
              )}
            </TabsContent>
          </Tabs>

          {/* Bottom actions */}
          <div className="flex flex-wrap gap-3 mt-8 pt-6 border-t border-white/10">
            <Button variant="outline" onClick={downloadCheatSheet} className="border-white/10 text-muted-foreground hover:text-white">
              <Download className="w-4 h-4 mr-2" /> {t("Tải Cheat Sheet", "Download Cheat Sheet")}
            </Button>
            {nextLecture && (
              <Button asChild className="bg-blue-500/20 text-blue-300 hover:bg-blue-500/30 border border-blue-500/30">
                <Link to={`/toeic-lectures/${nextLecture.id}`}>
                  {t("Bài tiếp theo", "Next Lesson")} <ChevronRight className="w-4 h-4 ml-1" />
                </Link>
              </Button>
            )}
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default ToeicLectureView;
