import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_lib  # noqa: E402
import spec_a, spec_b, spec_c  # noqa: E402,F401

HEADER = '''// Generated by scripts/python_challenges/build.py from the spec files - edit those, not this file.
// Challenges follow "Python by Example: Learning to Program in 150 Challenges" (Nichola Lacey).
import type { TurtleCheck } from "@/lib/pythonChallengeHarness";

export interface TestCase {
  /** Values typed into input(), one per line. */
  input: string;
  expected: string;
  description: string;
  /** Values that must appear (in order) when wording may differ. "a|b" = either, "re:" = regex. */
  keywords?: string[];
  /** The program may keep asking for input (e.g. a game) - running out of input is fine. */
  allowEof?: boolean;
}

export interface PythonChallenge {
  id: string;
  number: number;
  title: string;
  titleVi: string;
  difficulty: "easy" | "medium" | "hard";
  section: string;
  description: string;
  descriptionVi: string;
  expectedOutput: string;
  hints: string[];
  starterCode: string;
  solution: string;
  testCases: TestCase[];
  tags: string[];
  /** Runs before the learner code (creates files the book assumes already exist). */
  setupCode?: string;
  /** Random seed used when grading (default 7). */
  seed?: number;
  /** Turtle challenges are graded on the drawing instead of printed text. */
  turtle?: TurtleCheck;
  /** Explains how a Tkinter/desktop task is done on the web page. */
  webNote?: string;
  webNoteVi?: string;
}

export const pythonChallenges: PythonChallenge[] = '''

if __name__ == "__main__":
    data, problems = build_lib.build()
    if problems:
        print("BUILD FAILED:\n" + "\n".join(problems))
        sys.exit(1)
    target = os.path.join(build_lib.ROOT, "src/data/pythonChallenges.ts")
    with open(target, "w", encoding="utf-8") as f:
        f.write(HEADER + json.dumps(data, ensure_ascii=False, indent=2) + ";\n")
    tests = sum(len(c["testCases"]) for c in data)
    print(f"OK: {len(data)} challenges, {tests} tests, all reference answers pass.")
