import { CAMBRIDGE_KIDS_WORDS_DEDUPED } from "../src/data/cambridgeKidsVocabMaster";
import { getCategory, type KidsCategory } from "../src/data/cambridgeKidsCategories";

const rules: { cat: KidsCategory; words: string[] }[] = [
  { cat: "Animals", words: [
    "alligator","baby cat","bat","caterpillar","chick","crab","crow","deer","dove","flamingo","goldfish",
    "hamster","jellyfish","kitten","koala","lamb","lobster","pigeon","polar bear","seahorse","seal",
    "shrimp","sparrow","starfish","swan","worm","beetle","bull","calf","cheetah","cockroach","crane",
    "cricket","earthworm","falcon","fawn","ferret","flock","gerbil","gerbils","gibbon","goose","grasshopper",
    "hare","herd","heron","hornet","jaguar","joey","leopard","lemur","llama","mole","moth","ostrich",
    "oyster","panther","piglet","pony","porcupine","puffin","puma","quail","reindeer","robin","rooster",
    "salamander","scorpion","seahorses","skunk","slug","stallion","stork","swallow","tadpole","termite",
    "toad","trout","turkey","vulture","wasp","weasel","wildebeest","woodpecker","yak","gorilla","crocodile",
    "octopuses","insect","mammal","reptile","predator","prey","pet",
  ]},
  { cat: "Food & Drink", words: [
    "almond","apricot","avocado","bean","beef","beetroot","blueberry","bottle","cashew","cereal","coconut",
    "corn","cracker","date","doughnut","dumpling","fig","grapefruit","ham","hamburger","hot dog","kebab",
    "kiwi","lettuce","lime","lollipop","milkshake","muffin","nut","olive","omelette","pancake","papaya",
    "peach","peanut","pickle","pie","pistachio","plum","pomegranate","porridge","radish","stew","taco",
    "tangerine","toast","waffle","walnut","burrito","carrot","ham","bacon","barbecue","beer","biscuit",
    "broth","brownie","cocoa","crepe","cuisine","curry","custard","dessert","dim sum","drink","filling",
    "flour","grain","gravy","gum","ingredient","jelly","lasagna","lemonade","liquid","loaf","margarine",
    "mayonnaise","menu","mince","mushroom","mustard","oat","pastry","peas","pepper","pita","pork","pretzel",
    "pumpkin","quiche","ravioli","sauce","scone","seafood","seaweed","sherbet","slice","smoothie","snack",
    "soda","spice","squash","steak","syrup","taste","toffee","tofu","tortilla","tropical","truffle","turnip",
    "vanilla","vinegar","wheat","whip","yolk","zucchini","raisin","ramen","sushi","wasabi","sake","kimchi",
    "spinach","apple","banana",
  ]},
  { cat: "Body, Health & Feelings", words: [
    "belly","toe","acne","allergy","amazed","antibiotic","appendix","arthritis","asthma","blood pressure",
    "bored","cast","bandage","brain","cheek","chest","chin","crutch","diet","dizzy","elbow","eyebrow",
    "eyelash","feverish","gland","gum","gym","headache","hip","jaw","knee","kneel","lung","muscle","nail",
    "organ","pain","palm","pulse","rash","rib","scar","scratch","skeleton","spine","sprain","stretcher",
    "surgeon","surgery","sweat","swallow","symptom","syringe","temperature","therapy","throat","thumb",
    "vaccine","virus","vitamin","waist","wrist","xray","yawn","blister","bruise","bump","burp","cough",
    "diabetes","disability","disease","flu","gasp","germ","grin","heartbeat","hiccup","infection","injury",
    "joint","limp","liver","measles","mucus","nostril","pharmacy","plaster","posture","prescription","pulse",
    "saliva","sneeze","sob","sore","stitch","tear","tear drop","ulcer","vein","vomit","wheeze","whisker",
    "wink","wound","yawn",
    // feelings
    "frustrating","frustration","grateful","guilty","optimistic","pessimistic","sensitive","sincere",
    "patience","satisfaction","intense","intention","amazed","ashamed","awesome","bored","comfort",
    "confidence","confusion","cosy","crying","delight","disappointed","emotional","encouragement","envious",
    "exhausted","fear","fondness","fury","grief","hope","horror","irritated","laughter","longing","mood",
    "panic","passion","peaceful","reassuring","regret","relief","sentiment","shock","sorrow","stress","sympathy",
    "tense","terrified","thrilled","trust",
  ]},
  { cat: "People & Jobs", words: [
    "acrobat","archaeologist","barber","backpacker","freelancer","leader","politician","podcast-host",
    "victim","witness","accountant","ambassador","apprentice","assistant","attorney","author",
    "babysitter","biologist","bishop","blogger","bodyguard","botanist","builder","businessman","businesswoman",
    "carpenter","cartoonist","cashier","celebrity","ceo","chairman","clerk","coach","comedian","composer",
    "conductor","consultant","craftsman","critic","customer","dancer","dietitian","diplomat","director",
    "economist","editor","educator","electrician","employee","employer","entrepreneur","explorer","expert",
    "fan","fisherman","gardener","geographer","geologist","goalkeeper","governor","guard","historian","hunter",
    "illustrator","inspector","instructor","intern","interpreter","inventor","investor","janitor","jockey",
    "knight","landlord","librarian","linguist","lyricist","magician","mayor","midwife","minister","monk",
    "musician","navigator","novelist","operator","optician","orphan","owner","peasant","performer",
    "pharmacist","philosopher","physician","physicist","plumber","poet","president","prince","princess",
    "principal","priest","professor","programmer","psychologist","publisher","que
