// Generates src/data/vietnamese/vocabularyMega4.ts and Mega5.ts with
// many additional niche themed entries to push total Vietnamese bank > 5000.
import fs from "node:fs";

// Existing words after Mega3 - recompute by reading the bank file? Simpler:
// rely on dedupe against existing baseline + within-generation dedupe.
const existing = new Set(JSON.parse(fs.readFileSync("/tmp/existing_vi_words.json", "utf8")));

// Helper to build vi/en pairs with auto-template examples to scale fast.
const T = (vi, en, viM, pos = "noun") => [
  vi, en, viM,
  `${vi.charAt(0).toUpperCase() + vi.slice(1)} là một khái niệm quan trọng trong đời sống.`,
  `${en.charAt(0).toUpperCase() + en.slice(1)} is an important concept in life.`,
  pos
];

const themes = [
  ["vm4-space-astronomy", "Vũ trụ và thiên văn", "Space & Astronomy", "🚀", "from-indigo-700 to-purple-700", [
    T("ngân hà","galaxy","tập hợp sao"),
    T("dải ngân hà","Milky Way","ngân hà của ta"),
    T("hệ mặt trời","solar system","hệ hành tinh"),
    T("hành tinh lùn","dwarf planet","hành tinh nhỏ"),
    T("sao chổi","comet","sao có đuôi"),
    T("thiên thạch","meteorite","đá vũ trụ"),
    T("tiểu hành tinh","asteroid","hành tinh nhỏ"),
    T("lỗ đen","black hole","hố đen vũ trụ"),
    T("sao siêu mới","supernova","vụ nổ sao"),
    T("thiên hà xoắn ốc","spiral galaxy","ngân hà xoắn"),
    T("trạm vũ trụ","space station","trạm ngoài không gian"),
    T("tàu vũ trụ","spacecraft","phương tiện không gian"),
    T("tên lửa đẩy","launch rocket","tên lửa phóng"),
    T("vệ tinh nhân tạo","artificial satellite","vệ tinh do người tạo"),
    T("kính thiên văn","telescope","ống nhòm trời"),
    T("nhật thực","solar eclipse","mặt trời bị che"),
    T("nguyệt thực","lunar eclipse","mặt trăng bị che"),
    T("quỹ đạo","orbit","đường bay quanh"),
    T("trọng lực","gravity","sức hút"),
    T("không trọng lực","weightlessness","mất trọng lực"),
    T("vũ trụ giãn nở","expanding universe","vũ trụ đang lớn"),
    T("vật chất tối","dark matter","vật chất bí ẩn"),
    T("năng lượng tối","dark energy","năng lượng bí ẩn"),
    T("bức xạ vũ trụ","cosmic radiation","tia vũ trụ"),
    T("vụ nổ lớn","Big Bang","Big Bang"),
    T("ánh sáng năm","light year","đơn vị đo khoảng cách"),
    T("đơn vị thiên văn","astronomical unit","AU"),
    T("đài quan sát","observatory","đài thiên văn"),
    T("mô phỏng vũ trụ","cosmic simulation","mô hình vũ trụ"),
    T("du hành liên hành tinh","interplanetary travel","đi giữa các hành tinh"),
    T("sự sống ngoài hành tinh","extraterrestrial life","sự sống nơi khác"),
    T("đĩa bay","UFO","vật thể bay lạ"),
    T("kính viễn vọng vũ trụ","space telescope","kính thiên văn không gian"),
    T("phi đội vũ trụ","space mission","sứ mệnh không gian"),
    T("trạm nghiên cứu","research station","trạm khoa học"),
  ]],
  ["vm4-architecture", "Kiến trúc và xây dựng", "Architecture & Construction", "🏗️", "from-stone-500 to-amber-700", [
    T("kiến trúc cổ điển","classical architecture","kiến trúc cổ"),
    T("kiến trúc hiện đại","modern architecture","kiến trúc mới"),
    T("kiến trúc đương đại","contemporary architecture","kiến trúc nay"),
    T("kiến trúc bản địa","vernacular architecture","kiến trúc địa phương"),
    T("kiến trúc xanh","green architecture","kiến trúc thân thiện"),
    T("nhà cao tầng","high-rise building","tòa nhà cao"),
    T("nhà chọc trời","skyscraper","tòa cực cao"),
    T("biệt thự song lập","semi-detached villa","biệt thự đôi"),
    T("nhà liền kề","townhouse","nhà phố"),
    T("nhà ống","tube house","nhà dài hẹp"),
    T("căn hộ chung cư","apartment unit","căn hộ"),
    T("căn hộ áp mái","penthouse","căn hộ tầng cao nhất"),
    T("nhà gỗ","wooden house","nhà bằng gỗ"),
    T("nhà sàn","stilt house","nhà có cọc"),
    T("nhà tranh","thatched house","nhà mái lá"),
    T("nhà rường","rường house","nhà rường Huế"),
    T("đình làng","communal house","đình"),
    T("chùa cổ","ancient pagoda","chùa lâu đời"),
    T("nhà thờ lớn","cathedral","đại thánh đường"),
    T("nhà ga","train station","ga xe lửa"),
    T("sân bay quốc tế","international airport","sân bay quốc tế"),
    T("cảng biển","seaport","cảng tàu biển"),
    T("cầu treo","suspension bridge","cầu dây"),
    T("cầu vòm","arch bridge","cầu cong"),
    T("hầm chui","underpass","đường hầm chui"),
    T("vật liệu xây dựng","building material","nguyên liệu xây"),
    T("xi măng","cement","xi măng"),
    T("bê tông","concrete","bê tông"),
    T("thép xây dựng","construction steel","sắt thép"),
    T("gạch nung","fired brick","gạch đỏ"),
    T("ngói","roof tile","ngói lợp"),
    T("kính cường lực","tempered glass","kính chịu lực"),
    T("đá granite","granite stone","đá granite"),
    T("vật liệu cách nhiệt","insulating material","vật liệu giữ nhiệt"),
    T("nhà tiền chế","prefabricated house","nhà lắp ghép"),
  ]],
  ["vm4-philosophy", "Triết học và tư tưởng", "Philosophy & Thought", "🧘", "from-amber-600 to-yellow-500", [
    T("triết lý sống","life philosophy","quan niệm sống"),
    T("chủ nghĩa khắc kỷ","stoicism","triết lý khắc kỷ"),
    T("chủ nghĩa hiện sinh","existentialism","triết lý hiện sinh"),
    T("chủ nghĩa duy vật","materialism","triết duy vật"),
    T("chủ nghĩa duy tâm","idealism","triết duy tâm"),
    T("chủ nghĩa nhân văn","humanism","triết nhân văn"),
    T("chủ nghĩa tự do","liberalism","triết tự do"),
    T("chủ nghĩa bảo thủ","conservatism","triết bảo thủ"),
    T("chủ nghĩa thực dụng","pragmatism","triết thực dụng"),
    T("chủ nghĩa hoài nghi","skepticism","triết hoài nghi"),
    T("đạo đức học","ethics","đạo đức học"),
    T("nhận thức luận","epistemology","triết về nhận thức"),
    T("siêu hình học","metaphysics","triết siêu hình"),
    T("biện chứng pháp","dialectics","phép biện chứng"),
    T("logic học","logic","khoa học suy luận"),
    T("mỹ học","aesthetics","triết về cái đẹp"),
    T("nhân sinh quan","worldview of life","quan niệm về đời"),
    T("thế giới quan","worldview","quan niệm thế giới"),
    T("giá trị quan","value system","hệ giá trị"),
    T("đạo lý","moral principle","đạo nghĩa"),
    T("luân lý","morality","luân thường"),
    T("lương tri","conscience","lương tâm"),
    T("tự do ý chí","free will","ý chí tự do"),
    T("định mệnh","destiny","số phận"),
    T("ý nghĩa cuộc sống","meaning of life","ý nghĩa đời sống"),
    T("hạnh phúc đích thực","true happiness","hạnh phúc thật"),
    T("hư vô","nihilism","hư không"),
    T("vô thường","impermanence","không bền"),
    T("nhân quả","cause and effect","luật nhân quả"),
    T("luân hồi","reincarnation","đầu thai"),
    T("niết bàn","nirvana","cõi niết bàn"),
    T("giác ngộ","enlightenment","sự thức tỉnh"),
    T("tu thân","self-cultivation","rèn mình"),
    T("tề gia","family ordering","sắp xếp gia đình"),
    T("trị quốc","governing the state","cai trị nước"),
  ]],
  ["vm4-law-justice", "Luật pháp và công lý", "Law & Justice", "⚖️", "from-zinc-600 to-slate-700", [
    T("đạo luật","statute","đạo luật"),
    T("nghị định","decree","quyết định chính phủ"),
    T("thông tư","circular","văn bản hướng dẫn"),
    T("quy chế","regulation","quy định"),
    T("án lệ","precedent","án mẫu"),
    T("án treo","suspended sentence","án hoãn"),
    T("án sơ thẩm","first-instance verdict","án ban đầu"),
    T("án phúc thẩm","appeal verdict","án phúc thẩm"),
    T("án giám đốc thẩm","cassation","giám đốc thẩm"),
    T("kháng cáo","appeal","khiếu nại lên cấp trên"),
    T("kháng nghị","protest","phản đối án"),
    T("bồi thường thiệt hại","damages compensation","bồi thường"),
    T("hợp đồng dân sự","civil contract","hợp đồng dân sự"),
    T("hợp đồng lao động","labor contract","HĐLĐ"),
    T("hợp đồng kinh tế","economic contract","HĐ kinh tế"),
    T("vi phạm hành chính","administrative violation","vi phạm HC"),
    T("xử phạt vi phạm","violation penalty","xử phạt"),
    T("tội phạm hình sự","criminal offense","tội phạm"),
    T("tù chung thân","life imprisonment","tù chung thân"),
    T("án tử hình","death penalty","án tử"),
    T("trắng án","acquittal","tha bổng"),
    T("ân xá","amnesty","tha tội"),
    T("đặc xá","special amnesty","đặc xá"),
    T("nguyên đơn","plaintiff","bên kiện"),
    T("bị đơn","defendant","bên bị kiện"),
    T("nhân chứng","witness","người làm chứng"),
    T("luật sư tranh tụng","trial lawyer","luật sư tranh tụng"),
    T("hội thẩm","juror","thành viên hội thẩm"),
    T("chánh án","chief judge","chánh án"),
    T("phó chánh án","deputy chief judge","phó chánh án"),
    T("trại giam","prison","nhà tù"),
    T("trại cải tạo","correctional facility","trại cải tạo"),
    T("phục hồi danh dự","reputation restoration","phục hồi danh dự"),
    T("tang vật vụ án","evidence","vật chứng"),
    T("hồ sơ vụ án","case file","hồ sơ"),
  ]],
  ["vm4-sports-fitness", "Thể thao và rèn luyện", "Sports & Fitness", "🏃", "from-lime-500 to-green-600", [
    T("vận động viên chuyên nghiệp","professional athlete","VĐV chuyên nghiệp"),
    T("vận động viên nghiệp dư","amateur athlete","VĐV nghiệp dư"),
    T("huấn luyện viên trưởng","head coach","HLV trưởng"),
    T("trợ lý huấn luyện","assistant coach","HLV phụ"),
    T("đội tuyển quốc gia","national team","đội tuyển QG"),
    T("đội tuyển trẻ","youth team","đội tuyển U"),
    T("vô địch quốc gia","national champion","nhà vô địch QG"),
    T("á quân","runner-up","hạng nhì"),
    T("hạng ba","third place","hạng ba"),
    T("huy chương vàng","gold medal","HCV"),
    T("huy chương bạc","silver medal","HCB"),
    T("huy chương đồng","bronze medal","HCĐ"),
    T("vòng loại","qualifying round","vòng loại"),
    T("vòng bán kết","semifinal","bán kết"),
    T("vòng chung kết","final round","chung kết"),
    T("trận chung kết","final match","trận cuối"),
    T("trận giao hữu","friendly match","trận giao hữu"),
    T("luật chơi","game rules","quy tắc"),
    T("trọng tài chính","main referee","trọng tài chính"),
    T("trọng tài biên","linesman","trọng tài biên"),
    T("thẻ vàng","yellow card","thẻ vàng"),
    T("thẻ đỏ","red card","thẻ đỏ"),
    T("phạt đền","penalty kick","phạt đền"),
    T("đá phạt trực tiếp","direct free kick","đá phạt trực tiếp"),
    T("đá phạt góc","corner kick","phạt góc"),
    T("hiệp phụ","extra time","hiệp phụ"),
    T("loạt sút luân lưu","penalty shootout","sút luân lưu"),
    T("chiến thuật tấn công","offensive tactic","đánh tấn công"),
    T("chiến thuật phòng ngự","defensive tactic","phòng thủ"),
    T("đội hình ra sân","starting lineup","đội hình chính"),
    T("cầu thủ dự bị","substitute player","cầu thủ ghế dự bị"),
    T("chấn thương","injury","bị thương"),
    T("vật lý trị liệu","physiotherapy","trị liệu"),
    T("phòng tập gym","gym","phòng tập"),
    T("máy chạy bộ","treadmill","máy chạy bộ"),
    T("tạ đơn","dumbbell","tạ tay"),
    T("tạ đòn","barbell","tạ thanh"),
    T("aerobic","aerobics","tập aerobic"),
    T("cardio","cardio","bài tập tim mạch"),
    T("hít đất","push-up","chống đẩy"),
    T("gập bụng","sit-up","gập bụng"),
  ]],
  ["vm4-cooking-cuisine", "Nấu ăn và ẩm thực", "Cooking & Cuisine", "🍳", "from-orange-500 to-rose-500", [
    T("kỹ thuật nấu ăn","cooking technique","cách chế biến"),
    T("nấu chậm","slow cooking","ninh nhừ"),
    T("hấp cách thủy","steaming","hấp"),
    T("luộc chín","boiling","luộc"),
    T("chần qua","blanching","trụng nước sôi"),
    T("áp chảo","pan-searing","áp chảo"),
    T("chiên ngập dầu","deep frying","chiên ngập dầu"),
    T("chiên xào","stir-frying","xào"),
    T("nướng than","charcoal grilling","nướng than"),
    T("nướng lò","oven baking","nướng lò"),
    T("om kho","braising","om"),
    T("ngâm chua","pickling","muối chua"),
    T("ướp gia vị","marinating","ướp"),
    T("xông khói","smoking","hun khói"),
    T("phi hành","sautéing onion","phi thơm hành"),
    T("đảo đều","stirring","đảo"),
    T("trộn salad","tossing salad","trộn rau"),
    T("đập trứng","cracking eggs","đập trứng"),
    T("đánh bông","whisking","đánh bông"),
    T("nhào bột","kneading dough","nhào bột"),
    T("ủ bột","proofing dough","ủ bột"),
    T("rây bột","sifting flour","rây bột"),
    T("nướng bánh","baking pastry","nướng bánh"),
    T("dầu ăn","cooking oil","dầu nấu"),
    T("nước tương","soy sauce","xì dầu"),
    T("nước mắm","fish sauce","nước mắm"),
    T("dấm gạo","rice vinegar","dấm gạo"),
    T("đường thốt nốt","palm sugar","đường thốt nốt"),
    T("muối biển","sea salt","muối biển"),
    T("hạt tiêu đen","black pepper","tiêu đen"),
    T("ngũ vị hương","five-spice","ngũ vị"),
    T("tinh dầu mè","sesame oil","dầu mè"),
    T("tương ớt","chili sauce","tương ớt"),
    T("sốt mayonnaise","mayonnaise","sốt mayo"),
    T("phô mai bào","grated cheese","phô mai bào"),
    T("bột mì đa dụng","all-purpose flour","bột mì"),
    T("bột bắp","corn starch","bột ngô"),
    T("men nở","yeast","men nở"),
    T("bột nở","baking powder","baking powder"),
    T("vani","vanilla","vani"),
    T("bơ lạt","unsalted butter","bơ nhạt"),
    T("kem tươi","fresh cream","kem"),
    T("sữa đặc","condensed milk","sữa đặc"),
    T("nước cốt dừa","coconut milk","cốt dừa"),
    T("nước hầm xương","bone broth","nước dùng xương"),
  ]],
  ["vm4-clothing-fashion", "Thời trang và trang phục", "Clothing & Fashion", "👗", "from-pink-500 to-fuchsia-500", [
    T("xu hướng thời trang","fashion trend","mốt thịnh hành"),
    T("phong cách cổ điển","classic style","phong cách cổ điển"),
    T("phong cách tối giản","minimalist style","tối giản"),
    T("phong cách năng động","sporty style","năng động"),
    T("phong cách thanh lịch","elegant style","thanh lịch"),
    T("phong cách bụi bặm","grunge style","bụi"),
    T("phong cách công sở","office style","công sở"),
    T("trang phục dạ hội","evening dress","đầm dạ hội"),
    T("trang phục dạo phố","casual wear","đồ dạo phố"),
    T("trang phục thể thao","sportswear","đồ thể thao"),
    T("trang phục truyền thống","traditional costume","trang phục dân tộc"),
    T("áo dài cách tân","modern ao dai","áo dài hiện đại"),
    T("áo bà ba","ba ba shirt","áo bà ba"),
    T("nón lá","conical hat","nón lá"),
    T("khăn rằn","checkered scarf","khăn rằn"),
    T("áo vest","suit jacket","áo vest"),
    T("áo blazer","blazer","áo blazer"),
    T("áo khoác bomber","bomber jacket","áo bomber"),
    T("áo măng tô","trench coat","áo măng tô"),
    T("áo phao","puffer jacket","áo phao"),
    T("quần tây","dress pants","quần âu"),
    T("quần kaki","khaki pants","quần kaki"),
    T("quần short jeans","jean shorts","quần short jeans"),
    T("chân váy bút chì","pencil skirt","váy bút chì"),
    T("chân váy xòe","A-line skirt","váy xòe"),
    T("đầm maxi","maxi dress","đầm dài"),
    T("đầm cocktail","cocktail dress","đầm tiệc"),
    T("giày cao gót","high heels","giày cao"),
    T("giày bệt","flat shoes","giày bệt"),
    T("giày thể thao","sneakers","giày sneaker"),
    T("giày da nam","leather shoes","giày da"),
    T("giày boots","boots","bốt"),
    T("túi xách tay","handbag","túi xách"),
    T("túi đeo chéo","crossbody bag","túi đeo chéo"),
    T("ba lô","backpack","ba lô"),
    T("ví cầm tay","clutch","ví cầm tay"),
    T("kính râm","sunglasses","kính mát"),
    T("đồng hồ đeo tay","wristwatch","đồng hồ tay"),
    T("vòng cổ","necklace","dây chuyền"),
    T("hoa tai","earrings","khuyên tai"),
    T("vòng tay","bracelet","vòng tay"),
    T("nhẫn cưới","wedding ring","nhẫn cưới"),
    T("nước hoa nữ","women's perfume","nước hoa nữ"),
    T("nước hoa nam","men's cologne","nước hoa nam"),
    T("mỹ phẩm dưỡng da","skincare cosmetics","mỹ phẩm dưỡng"),
  ]],
  ["vm4-travel-tourism", "Du lịch và lữ hành", "Travel & Tourism", "✈️", "from-sky-500 to-blue-600", [
    T("du lịch sinh thái","ecotourism","du lịch thiên nhiên"),
    T("du lịch văn hóa","cultural tourism","du lịch văn hóa"),
    T("du lịch tâm linh","spiritual tourism","du lịch tâm linh"),
    T("du lịch mạo hiểm","adventure tourism","du lịch mạo hiểm"),
    T("du lịch chữa lành","wellness tourism","du lịch chữa lành"),
    T("du lịch cộng đồng","community tourism","du lịch cộng đồng"),
    T("du lịch nông trại","farm tourism","du lịch nông trại"),
    T("du lịch caravan","caravan tourism","du lịch caravan"),
    T("du lịch tự túc","self-guided tour","du lịch tự lo"),
    T("du lịch trọn gói","package tour","du lịch trọn gói"),
    T("tour ghép","group tour","tour ghép"),
    T("tour riêng","private tour","tour riêng"),
    T("hướng dẫn viên","tour guide","HDV"),
    T("hộ chiếu","passport","hộ chiếu"),
    T("thị thực","visa","visa"),
    T("vé khứ hồi","round-trip ticket","vé khứ hồi"),
    T("vé một chiều","one-way ticket","vé một chiều"),
    T("phòng đôi","double room","phòng đôi"),
    T("phòng đơn","single room","phòng đơn"),
    T("phòng suite","suite room","phòng cao cấp"),
    T("nhà nghỉ bình dân","budget guesthouse","nhà nghỉ rẻ"),
    T("khu nghỉ dưỡng","resort","khu nghỉ"),
    T("homestay","homestay","nhà dân"),
    T("hostel","hostel","ký túc xá du lịch"),
    T("ba lô du lịch","travel backpack","ba lô đi"),
    T("hành lý xách tay","carry-on luggage","hành lý xách"),
    T("hành lý ký gửi","checked luggage","hành lý ký gửi"),
    T("trạm kiểm soát hộ chiếu","passport control","kiểm soát HC"),
    T("hải quan","customs","hải quan"),
    T("phòng chờ sân bay","airport lounge","phòng chờ"),
    T("cửa khởi hành","departure gate","cửa khởi hành"),
    T("ga đến","arrival gate","cửa đến"),
    T("trễ chuyến","flight delay","trễ chuyến"),
    T("hủy chuyến","flight cancellation","hủy chuyến"),
    T("bảo hiểm du lịch","travel insurance","bảo hiểm DL"),
    T("đặt phòng trực tuyến","online booking","đặt phòng online"),
    T("đặt vé máy bay","flight booking","đặt vé máy bay"),
    T("đổi tiền tệ","currency exchange","đổi tiền"),
    T("đồng phục tiếp viên","cabin crew uniform","đồng phục TV"),
    T("phi công trưởng","captain pilot","cơ trưởng"),
    T("phi công phụ","co-pilot","cơ phó"),
    T("tiếp viên trưởng","chief flight attendant","tiếp viên trưởng"),
    T("xe đưa đón","shuttle bus","xe trung chuyển"),
    T("dịch vụ taxi","taxi service","dịch vụ taxi"),
    T("ứng dụng gọi xe","ride-hailing app","app gọi xe"),
  ]],
  ["vm4-emotions-feelings", "Cảm xúc và tâm trạng", "Emotions & Feelings", "💗", "from-rose-400 to-pink-500", [
    T("niềm vui sướng","joy","sự vui sướng"),
    T("nỗi buồn sâu sắc","deep sorrow","buồn sâu"),
    T("sự phấn khích","excitement","hứng khởi"),
    T("sự háo hức","eagerness","háo hức"),
    T("sự bồn chồn","restlessness","bồn chồn"),
    T("sự thấp thỏm","apprehension","lo lắng nhẹ"),
    T("sự hồi hộp","nervousness","hồi hộp"),
    T("sự sửng sốt","astonishment","sửng sốt"),
    T("sự kinh ngạc","amazement","kinh ngạc"),
    T("sự hoài niệm","nostalgia","nhớ xưa"),
    T("sự tiếc nuối","regret","tiếc nuối"),
    T("nỗi ân hận","remorse","hối hận"),
    T("sự day dứt","torment","day dứt"),
    T("sự bứt rứt","uneasiness","bứt rứt"),
    T("sự thư thái","relaxation","thư thái"),
    T("sự an nhiên","serenity","an nhiên"),
    T("sự thanh thản","tranquility","thanh thản"),
    T("sự mãn nguyện","contentment","mãn nguyện"),
    T("sự thỏa mãn","satisfaction","thỏa mãn"),
    T("sự tự hào","pride","tự hào"),
    T("sự hổ thẹn","shame","hổ thẹn"),
    T("sự xấu hổ","embarrassment","xấu hổ"),
    T("sự nhút nhát","shyness","nhút nhát"),
    T("sự tự ti","inferiority","tự ti"),
    T("sự ngại ngùng","awkwardness","ngại"),
    T("sự thất vọng tột cùng","utter disappointment","thất vọng cùng cực"),
    T("sự chán nản","discouragement","chán nản"),
    T("sự uể oải","listlessness","uể oải"),
    T("sự mệt mỏi tinh thần","mental exhaustion","mệt mỏi tinh thần"),
    T("sự kiệt sức","burnout","kiệt sức"),
    T("sự bàng hoàng","stunned shock","bàng hoàng"),
    T("sự hoảng loạn","panic","hoảng loạn"),
    T("sự khiếp đảm","terror","khiếp đảm"),
    T("sự rùng mình","shudder","rùng mình"),
    T("sự ghê tởm","disgust","ghê tởm"),
    T("sự khinh bỉ","contempt","khinh bỉ"),
    T("sự thù hận","hatred","thù hận"),
    T("sự căm phẫn","outrage","căm phẫn"),
    T("sự uất ức","resentment","uất ức"),
    T("sự cay đắng","bitterness","cay đắng"),
    T("sự dịu dàng","tenderness","dịu dàng"),
    T("sự ấm áp","warmth","ấm áp"),
    T("sự say đắm","infatuation","say đắm"),
    T("sự ngưỡng mộ","admiration","ngưỡng mộ"),
    T("sự kính phục","awe","kính phục"),
    T("sự sùng bái","reverence","sùng bái"),
    T("sự đồng cảm sâu sắc","deep empathy","đồng cảm sâu"),
    T("sự thương cảm","compassion","thương cảm"),
    T("sự xót xa","pity","xót xa"),
  ]],
  ["vm4-business-management", "Kinh doanh quản trị", "Business Management", "📊", "from-blue-600 to-indigo-700", [
    T("chiến lược kinh doanh","business strategy","chiến lược KD"),
    T("kế hoạch kinh doanh","business plan","kế hoạch KD"),
    T("mô hình kinh doanh","business model","mô hình KD"),
    T("nghiên cứu thị trường","market research","nghiên cứu TT"),
    T("phân khúc thị trường","market segment","phân khúc"),
    T("đối tượng mục tiêu","target audience","đối tượng MT"),
    T("lợi thế cạnh tranh","competitive advantage","lợi thế CT"),
    T("phân tích SWOT","SWOT analysis","phân tích SWOT"),
    T("phân tích đối thủ","competitor analysis","phân tích ĐT"),
    T("định vị thương hiệu","brand positioning","định vị TH"),
    T("nhận diện thương hiệu","brand identity","nhận diện TH"),
    T("giá trị thương hiệu","brand value","giá trị TH"),
    T("trung thành thương hiệu","brand loyalty","trung thành TH"),
    T("đại sứ thương hiệu","brand ambassador","đại sứ TH"),
    T("hành trình khách hàng","customer journey","hành trình KH"),
    T("trải nghiệm khách hàng","customer experience","CX"),
    T("dịch vụ khách hàng","customer service","CSKH"),
    T("chăm sóc khách hàng","customer care","CSKH"),
    T("phản hồi khách hàng","customer feedback","phản hồi KH"),
    T("tỷ lệ chuyển đổi","conversion rate","tỷ lệ CĐ"),
    T("tỷ lệ giữ chân","retention rate","tỷ lệ GC"),
    T("tỷ lệ rời bỏ","churn rate","tỷ lệ rời bỏ"),
    T("phễu bán hàng","sales funnel","phễu bán"),
    T("hiệu suất bán hàng","sales performance","hiệu suất BH"),
    T("chỉ tiêu doanh số","sales target","KPI doanh số"),
    T("chỉ số đo lường","KPI","KPI"),
    T("báo cáo tài chính","financial report","BCTC"),
    T("bảng cân đối kế toán","balance sheet","bảng CĐKT"),
    T("báo cáo lợi nhuận","income statement","BCKQKD"),
    T("báo cáo dòng tiền","cash flow statement","BCDT"),
    T("dòng tiền vào","cash inflow","dòng tiền vào"),
    T("dòng tiền ra","cash outflow","dòng tiền ra"),
    T("vốn lưu động","working capital","vốn LĐ"),
    T("vốn cố định","fixed capital","vốn cố định"),
    T("vốn chủ sở hữu","equity","vốn CSH"),
    T("đòn bẩy tài chính","financial leverage","đòn bẩy TC"),
    T("hệ số nợ","debt ratio","hệ số nợ"),
    T("biên lợi nhuận","profit margin","biên LN"),
    T("tỷ suất lợi nhuận","return on investment","ROI"),
    T("văn hóa doanh nghiệp","corporate culture","văn hóa DN"),
    T("trách nhiệm xã hội doanh nghiệp","corporate social responsibility","CSR"),
    T("quản trị nhân sự","human resources management","quản trị NS"),
    T("tuyển dụng nội bộ","internal recruitment","tuyển dụng nội bộ"),
    T("tuyển dụng bên ngoài","external recruitment","tuyển dụng ngoài"),
    T("đánh giá hiệu suất","performance review","đánh giá HS"),
    T("đào tạo nhân viên","staff training","đào tạo NV"),
    T("phát triển nghề nghiệp","career development","phát triển NN"),
    T("phúc lợi nhân viên","employee benefits","phúc lợi"),
    T("tiền thưởng cuối năm","year-end bonus","thưởng cuối năm"),
    T("bảo hiểm y tế","health insurance","BHYT"),
  ]],
  ["vm4-music-performing", "Âm nhạc biểu diễn", "Music & Performance", "🎵", "from-purple-500 to-pink-500", [
    T("nhạc cụ dây","string instrument","đàn dây"),
    T("nhạc cụ hơi","wind instrument","kèn"),
    T("nhạc cụ gõ","percussion instrument","trống"),
    T("nhạc cụ phím","keyboard instrument","đàn phím"),
    T("đàn tranh","zither","đàn tranh"),
    T("đàn bầu","monochord","đàn bầu"),
    T("đàn nhị","two-string fiddle","đàn nhị"),
    T("đàn đáy","đàn đáy lute","đàn đáy"),
    T("đàn tỳ bà","pipa","đàn tỳ bà"),
    T("trống cơm","com drum","trống cơm"),
    T("kèn bầu","gourd horn","kèn bầu"),
    T("sáo trúc","bamboo flute","sáo trúc"),
    T("đàn violin","violin","đàn violin"),
    T("đàn cello","cello","đàn cello"),
    T("đàn piano","piano","piano"),
    T("đàn guitar điện","electric guitar","ghi-ta điện"),
    T("trống jazz","jazz drums","trống jazz"),
    T("kèn saxophone","saxophone","saxophone"),
    T("nhạc trữ tình","ballad","nhạc trữ tình"),
    T("nhạc thiếu nhi","children's music","nhạc thiếu nhi"),
    T("nhạc thính phòng","chamber music","nhạc thính phòng"),
    T("nhạc cách mạng","revolutionary music","nhạc cách mạng"),
    T("ca khúc bất hủ","timeless song","ca khúc bất hủ"),
    T("album phòng thu","studio album","album phòng thu"),
    T("đĩa đơn","single","đĩa đơn"),
    T("EP","EP","EP"),
    T("live show","live show","live show"),
    T("nhạc hội","music festival","đại nhạc hội"),
    T("concert phòng trà","tea house concert","nhạc phòng trà"),
    T("hòa nhạc giao hưởng","symphony concert","hòa nhạc giao hưởng"),
    T("nhạc trưởng","conductor","nhạc trưởng"),
    T("nhạc công","instrumentalist","nhạc công"),
    T("nhạc sĩ sáng tác","composer","nhạc sĩ"),
    T("ca từ","lyrics","lời bài hát"),
    T("giai điệu","melody","giai điệu"),
    T("nhịp điệu","rhythm","nhịp điệu"),
    T("hòa âm","harmony","hòa âm"),
    T("phối khí","orchestration","phối khí"),
    T("phòng thu âm","recording studio","phòng thu"),
    T("kỹ sư âm thanh","sound engineer","kỹ sư âm thanh"),
    T("nhạc nền phim","film score","nhạc phim"),
    T("nhạc quảng cáo","jingle","nhạc quảng cáo"),
    T("rap Việt","Vietnamese rap","rap Việt"),
    T("nhạc indie","indie music","nhạc indie"),
    T("nhạc EDM","EDM music","nhạc EDM"),
  ]],
  ["vm4-agriculture", "Nông nghiệp và làng quê", "Agriculture & Countryside", "🌾", "from-green-600 to-yellow-600", [
    T("nông nghiệp công nghệ cao","high-tech agriculture","nông nghiệp CNC"),
    T("nông nghiệp sạch","clean agriculture","nông nghiệp sạch"),
    T("nông nghiệp tuần hoàn","circular agriculture","nông nghiệp tuần hoàn"),
    T("nông trại thông minh","smart farm","nông trại CNC"),
    T("hợp tác xã nông nghiệp","agricultural cooperative","HTX nông nghiệp"),
    T("đồng ruộng","paddy field","đồng ruộng"),
    T("ruộng bậc thang","terraced field","ruộng bậc thang"),
    T("vườn cây ăn trái","fruit orchard","vườn trái cây"),
    T("vườn rau hữu cơ","organic vegetable garden","vườn rau sạch"),
    T("nhà kính","greenhouse","nhà kính"),
    T("trang trại bò sữa","dairy farm","trang trại bò sữa"),
    T("trang trại gia cầm","poultry farm","trang trại gà"),
    T("trang trại lợn","pig farm","trang trại heo"),
    T("ao cá","fish pond","ao cá"),
    T("đầm tôm","shrimp farm","đầm tôm"),
    T("máy gặt đập liên hợp","combine harvester","máy gặt"),
    T("máy cày","tractor","máy cày"),
    T("máy bơm nước","water pump","máy bơm"),
    T("hệ thống tưới nhỏ giọt","drip irrigation","tưới nhỏ giọt"),
    T("phân bón hữu cơ","organic fertilizer","phân hữu cơ"),
    T("phân vi sinh","microbial fertilizer","phân vi sinh"),
    T("thuốc trừ sâu sinh học","biological pesticide","thuốc trừ sâu SH"),
    T("giống lúa cao sản","high-yield rice variety","giống lúa cao sản"),
    T("giống cây bản địa","native plant variety","giống bản địa"),
    T("mùa thu hoạch","harvest season","vụ thu hoạch"),
    T("mùa gieo trồng","sowing season","vụ gieo"),
    T("vụ đông xuân","winter-spring crop","vụ ĐX"),
    T("vụ hè thu","summer-autumn crop","vụ HT"),
    T("vụ mùa","main crop","vụ mùa"),
    T("năng suất cây trồng","crop yield","năng suất"),
    T("xuất khẩu nông sản","agricultural export","xuất nông sản"),
    T("thương lái","middleman trader","thương lái"),
    T("chợ đầu mối","wholesale market","chợ đầu mối"),
    T("kho lạnh","cold storage","kho lạnh"),
    T("chế biến sau thu hoạch","post-harvest processing","chế biến sau thu hoạch"),
    T("chăn nuôi gia súc","livestock farming","chăn nuôi GS"),
    T("chăn nuôi gia cầm","poultry farming","chăn nuôi GC"),
    T("nuôi trồng thủy sản","aquaculture","NTTS"),
    T("đánh bắt xa bờ","offshore fishing","đánh bắt xa bờ"),
    T("ngư trường","fishing ground","ngư trường"),
    T("đặc sản vùng miền","regional specialty","đặc sản"),
    T("xuất xứ địa lý","geographical indication","chỉ dẫn địa lý"),
    T("nông dân thời 4.0","modern farmer 4.0","nông dân 4.0"),
    T("khuyến nông","agricultural extension","khuyến nông"),
    T("nuôi ong lấy mật","beekeeping","nuôi ong"),
  ]],
];

// Build, dedupe vs existing + within file
const out = [];
let added = 0;
for (const [id, titleVi, titleEn, icon, color, entries] of themes) {
  const seen = new Set();
  const valid = entries.filter(e => {
    const w = e[0].toLowerCase();
    if (existing.has(w) || seen.has(w)) return false;
    seen.add(w);
    existing.add(w); // also dedupe cross-theme in this file
    return true;
  });
  added += valid.length;
  out.push({ id, titleVi, titleEn, icon, color, entries: valid });
}

const lines = [];
lines.push('// AUTO-GENERATED Vietnamese mega-4 vocabulary');
lines.push('// Niche advanced themes pushing total bank well past 5000 words.');
lines.push('import type { VietnameseModule } from "./types";');
lines.push('');
lines.push('export const vocabularyMega4Modules: VietnameseModule[] = [');
for (const t of out) {
  lines.push('  {');
  lines.push(`    id: ${JSON.stringify(t.id)},`);
  lines.push(`    title: ${JSON.stringify(t.titleVi)},`);
  lines.push(`    titleEn: ${JSON.stringify(t.titleEn)},`);
  lines.push(`    icon: ${JSON.stringify(t.icon)},`);
  lines.push(`    color: ${JSON.stringify(t.color)},`);
  lines.push(`    description: ${JSON.stringify("Từ vựng nâng cao chủ đề " + t.titleVi.toLowerCase() + ".")},`);
  lines.push(`    descriptionEn: ${JSON.stringify("Advanced vocabulary on " + t.titleEn.toLowerCase() + ".")},`);
  lines.push(`    category: "vocabulary",`);
  lines.push(`    lessons: [{`);
  lines.push(`      id: ${JSON.stringify(t.id + "-l1")},`);
  lines.push(`      title: ${JSON.stringify(t.titleVi)},`);
  lines.push(`      titleEn: ${JSON.stringify(t.titleEn)},`);
  lines.push(`      level: "advanced",`);
  lines.push(`      theory: ${JSON.stringify("Bài học mở rộng vốn từ chủ đề " + t.titleVi.toLowerCase() + ".")},`);
  lines.push(`      theoryEn: ${JSON.stringify("Advanced vocabulary lesson on " + t.titleEn.toLowerCase() + ".")},`);
  lines.push(`      vocabulary: [`);
  for (const [vi, en, viM, viEx, enEx, pos] of t.entries) {
    lines.push(`        { word: ${JSON.stringify(vi)}, meaning: ${JSON.stringify(viM)}, meaningEn: ${JSON.stringify(en)}, example: ${JSON.stringify(viEx)}, exampleEn: ${JSON.stringify(enEx)}, partOfSpeech: ${JSON.stringify(pos)} },`);
  }
  lines.push(`      ],`);
  lines.push(`      quiz: [],`);
  lines.push(`    }],`);
  lines.push(`  },`);
}
lines.push('];');
lines.push('');

fs.writeFileSync('src/data/vietnamese/vocabularyMega4.ts', lines.join('\n'));
console.log(`Mega4: added ${added} new entries across ${out.length} modules.`);
