// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful for verifying connectivity to the HaiEduTech MCP server.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var COURSES = [
  { id: "ielts", title: "IELTS Preparation", url: "/ielts", description: "Full IELTS coaching: reading, listening, speaking, writing, vocab bank." },
  { id: "toeic", title: "TOEIC Masterclass", url: "/toeic", description: "TOEIC Parts 1-7 with trap alerts and business vocabulary." },
  { id: "hsk", title: "HSK Chinese", url: "/hsk", description: "HSK 1-6 grammar, vocabulary and mock tests with stroke animations." },
  { id: "cambridge", title: "Cambridge YLE", url: "/cambridge", description: "Starters to PET lectures and 10 mock exams." },
  { id: "sat", title: "SAT Prep", url: "/sat", description: "SAT roadmap, exercises, exams, and daily warmups." },
  { id: "pte", title: "PTE Academic", url: "/pte", description: "PTE listening, reading, writing modules with scoring." },
  { id: "thpt", title: "Vietnamese National Exam (THPT)", url: "/national-exam-prep", description: "20 mock exams and 5 tactical modules for THPT English." },
  { id: "vietnamese-foreigners", title: "Vietnamese for Foreigners (VFF)", url: "/learn-vietnamese/for-foreigners", description: "A1-B1 CEFR track with AI roleplay, writing grader, video immersion." },
  { id: "vietnamese-kids", title: "Learn Vietnamese", url: "/learn-vietnamese", description: "Alphabet, poetry, folklore, dictation, cuisine, culture, films." },
  { id: "finnish", title: "Finnish / YKI", url: "/finnish", description: "Finnish beginner + YKI A2/B1 prep with speaking coach." },
  { id: "swedish", title: "Swedish / Svenskfinland", url: "/swedish", description: "Swedish beginner + YKI A2/B1 modules." },
  { id: "english-grammar", title: "English Grammar", url: "/english-grammar", description: "9 modules, 30 lessons of interactive grammar." },
  { id: "conversational-english", title: "Conversational English", url: "/conversational", description: "38 lessons with dual-speed TTS." },
  { id: "conversational-chinese", title: "Conversational Chinese", url: "/chinese-conversational", description: "18 lessons with Hanzi + Pinyin + VI." },
  { id: "programming", title: "Programming Lab", url: "/programming", description: "Scratch, Python, SQL, ML, Spark - taught in Vietnamese." },
  { id: "scholarships", title: "Global Scholarship Hub", url: "/scholarships", description: "60+ ICT/EdTech scholarships with AI advisor." },
  { id: "counseling", title: "Counseling Hub", url: "/dashboard", description: "Compass AI career/mood/IKIGAI/MBTI/Holland counseling." }
];
var list_courses_default = defineTool2({
  name: "list_courses",
  title: "List HaiEduTech courses",
  description: "List all learning tracks available on HaiEduTech (IELTS, TOEIC, HSK, Vietnamese, Finnish, Swedish, programming, scholarships, etc.) with URLs and short descriptions.",
  inputSchema: {
    filter: z2.string().optional().describe("Optional substring to filter course id / title / description (case-insensitive).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ filter }) => {
    const f = filter?.toLowerCase().trim();
    const items = f ? COURSES.filter((c) => `${c.id} ${c.title} ${c.description}`.toLowerCase().includes(f)) : COURSES;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { courses: items, count: items.length }
    };
  }
});

// src/lib/mcp/tools/vff-curriculum.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var VFF = {
  hubUrl: "/learn-vietnamese/for-foreigners",
  levels: [
    { key: "a1", cefr: "A1", title: "Beginner", topics: ["Greetings", "Numbers", "Family", "Food basics", "Directions"] },
    { key: "a2", cefr: "A2", title: "Elementary", topics: ["Restaurant", "Grab/Taxi", "Shopping", "Directions", "Health", "Weather"] },
    { key: "b1", cefr: "B1", title: "Intermediate", topics: ["Work", "Travel", "Opinions", "News", "Culture"] }
  ],
  labs: [
    { id: "pronunciation", url: "/learn-vietnamese/for-foreigners/lab/pronunciation", title: "Pronunciation Lab (tones + minimal pairs)" },
    { id: "listening", url: "/learn-vietnamese/for-foreigners/lab/listening", title: "Listening Lab (3-speed dialogues)" },
    { id: "reading", url: "/learn-vietnamese/for-foreigners/lab/reading", title: "Reading Lab (graded passages)" },
    { id: "writing", url: "/learn-vietnamese/for-foreigners/lab/writing", title: "Writing Lab + AI Grader" },
    { id: "roleplay-ai", url: "/learn-vietnamese/for-foreigners/lab/roleplay-ai", title: "AI Roleplay (voice with NPCs)" },
    { id: "flashcards", url: "/learn-vietnamese/for-foreigners/lab/flashcards", title: "SRS Flashcards" },
    { id: "video", url: "/learn-vietnamese/for-foreigners/lab/video", title: "Video Immersion Lounge" },
    { id: "culture", url: "/learn-vietnamese/for-foreigners/lab/culture", title: "Culture Hub" },
    { id: "placement-adaptive", url: "/learn-vietnamese/for-foreigners/placement-adaptive", title: "Adaptive Placement Test" },
    { id: "analytics", url: "/learn-vietnamese/for-foreigners/analytics", title: "Skill Analytics Radar" },
    { id: "certificate", url: "/learn-vietnamese/for-foreigners/certificate", title: "Course Certificate" }
  ]
};
var vff_curriculum_default = defineTool3({
  name: "get_vff_curriculum",
  title: "Vietnamese for Foreigners curriculum",
  description: "Return the Vietnamese for Foreigners (VFF) curriculum overview: CEFR levels A1/A2/B1 with topics, plus all skill labs (pronunciation, listening, reading, writing, roleplay AI, flashcards, culture, video, placement, analytics).",
  inputSchema: {
    level: z3.enum(["a1", "a2", "b1"]).optional().describe("Optional: return only one CEFR level.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ level }) => {
    const data = level ? { ...VFF, levels: VFF.levels.filter((l) => l.key === level) } : VFF;
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "haiedutech-mcp",
  title: "HaiEduTech MCP",
  version: "0.1.0",
  instructions: "Tools for HaiEduTech - a multi-language learning platform (IELTS, TOEIC, HSK, Cambridge, SAT, PTE, THPT, Vietnamese for Foreigners, Finnish/YKI, Swedish, programming). Use `list_courses` to discover tracks, `get_vff_curriculum` for the Vietnamese-for-Foreigners program, and `echo` to verify connectivity.",
  tools: [echo_default, list_courses_default, vff_curriculum_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
