-- Add more public-domain / classic songs to language_songs for English, Chinese, Vietnamese, Finnish
INSERT INTO public.language_songs (language, title, artist, difficulty, youtube_id, cultural_note, cultural_note_en, is_public_domain, lyrics, core_vocab, blanks_quiz, display_order, is_published)
VALUES
-- ============ ENGLISH ============
('english', 'If You''re Happy and You Know It', 'Traditional',
  'easy', 'l4WNrvVjiTw',
  'Bài hát thiếu nhi cổ điển dạy biểu lộ cảm xúc qua hành động.',
  'Classic children''s song teaching emotional expression through actions.',
  true,
  '[{"original":"If you''re happy and you know it, clap your hands","translation":"Nếu bạn vui và bạn biết điều đó, hãy vỗ tay"},
    {"original":"If you''re happy and you know it, clap your hands","translation":"Nếu bạn vui và bạn biết điều đó, hãy vỗ tay"},
    {"original":"If you''re happy and you know it, then your face will surely show it","translation":"Nếu vui và biết điều đó, gương mặt bạn sẽ thể hiện"},
    {"original":"If you''re happy and you know it, clap your hands","translation":"Nếu bạn vui và bạn biết điều đó, hãy vỗ tay"},
    {"original":"If you''re happy and you know it, stomp your feet","translation":"Nếu vui, hãy giậm chân"},
    {"original":"If you''re happy and you know it, shout hooray","translation":"Nếu vui, hãy hô hooray"}]'::jsonb,
  '[{"word":"happy","ipa":"/ˈhæp.i/","meaning":"vui vẻ","example":"I am happy today."},
    {"word":"know","ipa":"/noʊ/","meaning":"biết","example":"I know the answer."},
    {"word":"clap","ipa":"/klæp/","meaning":"vỗ tay","example":"Clap your hands together."},
    {"word":"feet","ipa":"/fiːt/","meaning":"bàn chân","example":"My feet are cold."},
    {"word":"shout","ipa":"/ʃaʊt/","meaning":"hô to","example":"Don''t shout in the library."}]'::jsonb,
  '[{"lineIndex":0,"blanks":[{"wordIndex":2,"answer":"happy"}]},
    {"lineIndex":4,"blanks":[{"wordIndex":7,"answer":"feet"}]}]'::jsonb,
  20, true),

('english', 'The Wheels on the Bus', 'Traditional',
  'easy', 'e_04ZrNroTo',
  'Bài hát nổi tiếng cho trẻ em với các hành động lặp lại - tuyệt vời cho người mới học.',
  'Famous children''s song with repetitive actions - great for beginners.',
  true,
  '[{"original":"The wheels on the bus go round and round","translation":"Bánh xe buýt quay tròn và quay tròn"},
    {"original":"Round and round, round and round","translation":"Tròn và tròn, tròn và tròn"},
    {"original":"The wheels on the bus go round and round","translation":"Bánh xe buýt quay tròn và quay tròn"},
    {"original":"All through the town","translation":"Khắp cả thành phố"},
    {"original":"The wipers on the bus go swish swish swish","translation":"Cần gạt nước trên xe buýt swish swish swish"},
    {"original":"The horn on the bus goes beep beep beep","translation":"Còi xe buýt kêu beep beep beep"}]'::jsonb,
  '[{"word":"wheel","ipa":"/wiːl/","meaning":"bánh xe","example":"A car has four wheels."},
    {"word":"bus","ipa":"/bʌs/","meaning":"xe buýt","example":"I take the bus to school."},
    {"word":"round","ipa":"/raʊnd/","meaning":"tròn","example":"The ball is round."},
    {"word":"town","ipa":"/taʊn/","meaning":"thị trấn","example":"I live in a small town."},
    {"word":"horn","ipa":"/hɔːrn/","meaning":"còi","example":"The driver honked the horn."}]'::jsonb,
  '[{"lineIndex":0,"blanks":[{"wordIndex":2,"answer":"bus"}]},
    {"lineIndex":3,"blanks":[{"wordIndex":2,"answer":"town"}]}]'::jsonb,
  21, true),

('english', 'Mary Had a Little Lamb', 'Traditional',
  'easy', 'CuI_p7a9VGs',
  'Một trong những bài đồng dao tiếng Anh đầu tiên - cấu trúc câu rõ ràng cho người mới.',
  'One of the first English nursery rhymes - clear sentence structure for beginners.',
  true,
  '[{"original":"Mary had a little lamb","translation":"Mary có một chú cừu nhỏ"},
    {"original":"Little lamb, little lamb","translation":"Cừu nhỏ, cừu nhỏ"},
    {"original":"Mary had a little lamb","translation":"Mary có một chú cừu nhỏ"},
    {"original":"Its fleece was white as snow","translation":"Lông nó trắng như tuyết"},
    {"original":"And everywhere that Mary went","translation":"Và bất cứ nơi nào Mary đi"},
    {"original":"The lamb was sure to go","translation":"Chú cừu chắc chắn cũng đi theo"}]'::jsonb,
  '[{"word":"little","ipa":"/ˈlɪt.l/","meaning":"nhỏ","example":"She has a little dog."},
    {"word":"lamb","ipa":"/læm/","meaning":"cừu non","example":"The lamb is white."},
    {"word":"fleece","ipa":"/fliːs/","meaning":"bộ lông cừu","example":"The fleece is soft."},
    {"word":"snow","ipa":"/snoʊ/","meaning":"tuyết","example":"The snow is cold."},
    {"word":"everywhere","ipa":"/ˈev.ri.wer/","meaning":"khắp nơi","example":"I looked everywhere for my keys."}]'::jsonb,
  '[{"lineIndex":0,"blanks":[{"wordIndex":4,"answer":"lamb"}]},
    {"lineIndex":3,"blanks":[{"wordIndex":3,"answer":"white"}]}]'::jsonb,
  22, true),

-- ============ CHINESE ============
('chinese', '生日快乐 (Sinh nhật vui vẻ)', '传统 / Traditional',
  'easy', 'inS9gAgSENE',
  'Phiên bản tiếng Trung của "Happy Birthday" - bài hát chúc mừng sinh nhật phổ biến nhất.',
  'The Chinese version of "Happy Birthday" - the most universal birthday song.',
  true,
  '[{"original":"祝你生日快乐","translation":"Chúc bạn sinh nhật vui vẻ","words":[{"w":"祝","pinyin":"zhù","meaning":"chúc"},{"w":"你","pinyin":"nǐ","meaning":"bạn"},{"w":"生日","pinyin":"shēngrì","meaning":"sinh nhật"},{"w":"快乐","pinyin":"kuàilè","meaning":"vui vẻ"}]},
    {"original":"祝你生日快乐","translation":"Chúc bạn sinh nhật vui vẻ"},
    {"original":"祝你生日快乐","translation":"Chúc bạn sinh nhật vui vẻ"},
    {"original":"祝你生日快乐","translation":"Chúc bạn sinh nhật vui vẻ"}]'::jsonb,
  '[{"word":"生日","pinyin":"shēngrì","meaning":"sinh nhật","example":"今天是我的生日。"},
    {"word":"快乐","pinyin":"kuàilè","meaning":"vui vẻ","example":"祝你快乐！"},
    {"word":"祝","pinyin":"zhù","meaning":"chúc","example":"祝你成功。"},
    {"word":"你","pinyin":"nǐ","meaning":"bạn","example":"你好！"}]'::jsonb,
  '[{"lineIndex":0,"blanks":[{"wordIndex":2,"answer":"生日"}]}]'::jsonb,
  20, true),

('chinese', '世上只有妈妈好 (Trên đời chỉ có mẹ là tốt)', '传统 / Traditional',
  'intermediate', 'cBuxTrwZw8Q',
  'Bài hát kinh điển ca ngợi tình mẫu tử - được học sinh Trung Quốc thuộc nằm lòng.',
  'Classic song honoring mother''s love - cherished by every Chinese child.',
  true,
  '[{"original":"世上只有妈妈好","translation":"Trên đời chỉ có mẹ là tốt"},
    {"original":"有妈的孩子像块宝","translation":"Con có mẹ giống như có báu vật"},
    {"original":"投进妈妈的怀抱","translation":"Sà vào vòng tay mẹ"},
    {"original":"幸福享不了","translation":"Hạnh phúc không sao tả xiết"},
    {"original":"世上只有妈妈好","translation":"Trên đời chỉ có mẹ là tốt"},
    {"original":"没妈的孩子像根草","translation":"Con không mẹ giống như cọng cỏ"}]'::jsonb,
  '[{"word":"世上","pinyin":"shìshàng","meaning":"trên đời","example":"世上无难事。"},
    {"word":"妈妈","pinyin":"māma","meaning":"mẹ","example":"妈妈很爱我。"},
    {"word":"孩子","pinyin":"háizi","meaning":"đứa trẻ","example":"孩子在玩。"},
    {"word":"宝","pinyin":"bǎo","meaning":"báu vật","example":"这是我的宝。"},
    {"word":"幸福","pinyin":"xìngfú","meaning":"hạnh phúc","example":"我很幸福。"}]'::jsonb,
  '[{"lineIndex":0,"blanks":[{"wordIndex":3,"answer":"妈妈"}]},
    {"lineIndex":4,"blanks":[{"wordIndex":3,"answer":"妈妈"}]}]'::jsonb,
  21, true),

('chinese', '上海滩 (Bến Thượng Hải)', '叶丽仪 / Frances Yip',
  'advanced', 'GbcADNI3Cg4',
  'Ca khúc chủ đề của bộ phim huyền thoại "Bến Thượng Hải" (1980) - biểu tượng văn hóa Hong Kong.',
  'Theme song of the legendary "Shanghai Bund" series (1980) - a Hong Kong cultural icon.',
  false,
  '[{"original":"浪奔 浪流","translation":"Sóng cuộn, sóng trôi"},
    {"original":"万里涛涛江水永不休","translation":"Vạn dặm sóng cuồn cuộn không ngừng"},
    {"original":"淘尽了世间事","translation":"Cuốn trôi mọi chuyện thế gian"},
    {"original":"混作滔滔一片潮流","translation":"Hòa thành dòng triều cuộn trào"},
    {"original":"是喜是愁 浪里分不清欢笑悲忧","translation":"Vui hay buồn, trong sóng khó phân biệt"},
    {"original":"成功失败 浪里看不出有未有","translation":"Thành công thất bại, trong sóng nào biết"}]'::jsonb,
  '[{"word":"浪","pinyin":"làng","meaning":"sóng","example":"海浪很大。"},
    {"word":"江水","pinyin":"jiāngshuǐ","meaning":"nước sông","example":"江水东流。"},
    {"word":"世间","pinyin":"shìjiān","meaning":"thế gian","example":"世间百态。"},
    {"word":"成功","pinyin":"chénggōng","meaning":"thành công","example":"祝你成功。"},
    {"word":"失败","pinyin":"shībài","meaning":"thất bại","example":"失败是成功之母。"}]'::jsonb,
  '[{"lineIndex":4,"blanks":[{"wordIndex":2,"answer":"浪"}]}]'::jsonb,
  22, true),

-- ============ VIETNAMESE ============
('vietnamese', 'Cả nhà thương nhau', 'Phan Văn Minh',
  'easy', 'EmRRQOFZJF8',
  'Bài hát thiếu nhi quen thuộc về tình cảm gia đình - được hát ở mọi mẫu giáo Việt Nam.',
  'Classic Vietnamese children''s song about family love - sung in every kindergarten.',
  false,
  '[{"original":"Ba thương con vì con giống mẹ","translation":"Dad loves child because child looks like mom"},
    {"original":"Mẹ thương con vì con giống ba","translation":"Mom loves child because child looks like dad"},
    {"original":"Cả nhà ta cùng thương yêu nhau","translation":"Our whole family loves each other"},
    {"original":"Xa là nhớ gần nhau là cười","translation":"Apart we miss, together we smile"}]'::jsonb,
  '[{"word":"ba","meaning":"father","example":"Ba ơi, con yêu ba."},
    {"word":"mẹ","meaning":"mother","example":"Mẹ rất hiền."},
    {"word":"thương","meaning":"to love","example":"Con thương mẹ."},
    {"word":"nhà","meaning":"home","example":"Nhà em ở Hà Nội."},
    {"word":"cười","meaning":"to smile","example":"Em bé cười tươi."}]'::jsonb,
  '[{"lineIndex":0,"blanks":[{"wordIndex":1,"answer":"thương"}]},
    {"lineIndex":2,"blanks":[{"wordIndex":1,"answer":"nhà"}]}]'::jsonb,
  20, true),

('vietnamese', 'Em là bông hồng nhỏ', 'Trịnh Công Sơn',
  'intermediate', 'aTl4cD8b5K8',
  'Sáng tác của Trịnh Công Sơn - bài hát tuổi thơ trong sáng được nhiều thế hệ yêu thích.',
  'A Trịnh Công Sơn composition - beloved childhood song across generations.',
  false,
  '[{"original":"Em sẽ là mùa xuân của mẹ","translation":"I''ll be mother''s spring"},
    {"original":"Em sẽ là màu nắng của cha","translation":"I''ll be father''s sunlight"},
    {"original":"Em đến trường học bao điều lạ","translation":"I go to school to learn new things"},
    {"original":"Môi mỉm cười là những nụ hoa","translation":"My smile is like blooming flowers"},
    {"original":"Trang sách hồng nằm mơ màng ngủ","translation":"Pink pages dream gently"},
    {"original":"Em gối đầu lên những vần thơ","translation":"I rest my head on verses"}]'::jsonb,
  '[{"word":"mùa xuân","meaning":"spring","example":"Mùa xuân đến rồi."},
    {"word":"nắng","meaning":"sunshine","example":"Trời nắng đẹp."},
    {"word":"trường","meaning":"school","example":"Em đi học ở trường."},
    {"word":"hoa","meaning":"flower","example":"Hoa hồng rất đẹp."},
    {"word":"sách","meaning":"book","example":"Em đọc sách mỗi ngày."}]'::jsonb,
  '[{"lineIndex":0,"blanks":[{"wordIndex":3,"answer":"xuân"}]},
    {"lineIndex":2,"blanks":[{"wordIndex":2,"answer":"trường"}]}]'::jsonb,
  21, true),

('vietnamese', 'Hà Nội mùa thu', 'Vũ Thanh',
  'advanced', 'rH1IF_x7p4M',
  'Bản tình ca bất hủ về vẻ đẹp mùa thu Hà Nội - biểu tượng văn học của thủ đô.',
  'Timeless ballad about Hanoi autumn beauty - a literary icon of the capital.',
  false,
  '[{"original":"Hà Nội mùa thu, cây cơm nguội vàng","translation":"Hanoi autumn, yellow cơm nguội trees"},
    {"original":"Cây bàng lá đỏ nằm kề bên nhau","translation":"Red bàng leaves lying side by side"},
    {"original":"Phố xưa nhà cổ, mái ngói thâm nâu","translation":"Old streets, ancient houses, dark brown tiled roofs"},
    {"original":"Hà Nội mùa thu, mùa thu Hà Nội","translation":"Hanoi autumn, autumn of Hanoi"},
    {"original":"Mùa hoa sữa về thơm từng cơn gió","translation":"Milkwood season, fragrant in every breeze"},
    {"original":"Mùa cốm xanh về thơm bàn tay nhỏ","translation":"Green cốm season fragrant on little hands"}]'::jsonb,
  '[{"word":"mùa thu","meaning":"autumn","example":"Mùa thu rất đẹp."},
    {"word":"cây","meaning":"tree","example":"Cây cao bóng mát."},
    {"word":"phố","meaning":"street","example":"Phố cổ Hà Nội."},
    {"word":"hoa sữa","meaning":"milkwood flower","example":"Hoa sữa nở thơm ngát."},
    {"word":"cốm","meaning":"green sticky rice","example":"Cốm làng Vòng nổi tiếng."}]'::jsonb,
  '[{"lineIndex":0,"blanks":[{"wordIndex":2,"answer":"thu"}]},
    {"lineIndex":4,"blanks":[{"wordIndex":1,"answer":"hoa"}]}]'::jsonb,
  22, true),

-- ============ FINNISH ============
('finnish', 'Päivänsäde ja Menninkäinen', 'Tapio Rautavaara',
  'intermediate', 'kZxKZ3O3MWk',
  'Câu chuyện kinh điển Phần Lan về tia nắng và yêu tinh - được mọi đứa trẻ Phần Lan biết.',
  'Classic Finnish tale about a sunbeam and goblin - known to every Finnish child.',
  true,
  '[{"original":"Aurinko kun päätti retkensä","translation":"Khi mặt trời kết thúc cuộc dạo chơi"},
    {"original":"Siskoset kotihin vei","translation":"Đưa các tia nắng về nhà"},
    {"original":"Päivänsäde viimeinen","translation":"Một tia nắng cuối cùng"},
    {"original":"Kohta jo metsähän eksyikin","translation":"Lạc vào trong rừng"},
    {"original":"Siellä on metsä syvä","translation":"Khu rừng nơi đây thật sâu"},
    {"original":"Siellä on yö ja päivä","translation":"Có cả ngày và đêm"}]'::jsonb,
  '[{"word":"aurinko","meaning":"mặt trời","example":"Aurinko paistaa."},
    {"word":"metsä","meaning":"rừng","example":"Menen metsään."},
    {"word":"päivä","meaning":"ngày","example":"Hyvää päivää."},
    {"word":"yö","meaning":"đêm","example":"Hyvää yötä."},
    {"word":"viimeinen","meaning":"cuối cùng","example":"Viimeinen kerta."}]'::jsonb,
  '[{"lineIndex":0,"blanks":[{"wordIndex":0,"answer":"Aurinko"}]},
    {"lineIndex":4,"blanks":[{"wordIndex":2,"answer":"metsä"}]}]'::jsonb,
  20, true),

('finnish', 'Ievan Polkka', 'Loituma',
  'advanced', 'ZqRpqp_LqFI',
  'Bài dân ca polka nổi tiếng toàn cầu nhờ Loituma - giai điệu vui tươi đặc trưng Phần Lan.',
  'Globally famous polka folk song by Loituma - quintessential cheerful Finnish melody.',
  false,
  '[{"original":"Nuapurista kuulu se polokan tahti","translation":"Từ hàng xóm vang lên nhịp polka"},
    {"original":"Jalakani pohjii kutkutti","translation":"Lòng bàn chân tôi cứ ngọ nguậy"},
    {"original":"Ievan äiti se tyttöösä vahti","translation":"Mẹ Ieva canh chừng con gái"},
    {"original":"Vaan kyllähän Ieva sen jutkutti","translation":"Nhưng Ieva đã lừa được bà"},
    {"original":"Sillä eihän se Ieva sit ollum mikkään","translation":"Bởi vì Ieva đâu phải kẻ"},
    {"original":"Joka olis ottanna jiätyräkkään","translation":"Có thể bị kéo lại ở yên"}]'::jsonb,
  '[{"word":"naapuri","meaning":"hàng xóm","example":"Naapuri on ystävällinen."},
    {"word":"äiti","meaning":"mẹ","example":"Äiti tekee ruokaa."},
    {"word":"tyttö","meaning":"con gái","example":"Tyttö on kaunis."},
    {"word":"jalka","meaning":"chân","example":"Jalka on kipeä."},
    {"word":"polkka","meaning":"điệu polka","example":"Tanssimme polkkaa."}]'::jsonb,
  '[{"lineIndex":2,"blanks":[{"wordIndex":1,"answer":"äiti"}]}]'::jsonb,
  21, true),

('finnish', 'Pikku Kakkonen', 'Lasten / Children',
  'easy', 'WvuQX_GLgZw',
  'Bài hát chủ đề chương trình thiếu nhi YLE huyền thoại - âm nhạc lớn lên cùng trẻ em Phần Lan.',
  'Theme song of the legendary YLE children''s show - the soundtrack of Finnish childhood.',
  true,
  '[{"original":"Pikku Kakkonen, tervetuloa","translation":"Pikku Kakkonen, chào mừng bạn"},
    {"original":"Tänne meidän luokse","translation":"Tới chỗ chúng tôi"},
    {"original":"Lapsia ja aikuisia","translation":"Trẻ em và người lớn"},
    {"original":"Yhdessä leikkimään","translation":"Cùng nhau vui chơi"},
    {"original":"Hyvää iltaa, hyvät ystävät","translation":"Chúc buổi tối tốt lành, các bạn tốt"},
    {"original":"Nyt on aika tarinan","translation":"Bây giờ là lúc kể chuyện"}]'::jsonb,
  '[{"word":"tervetuloa","meaning":"chào mừng","example":"Tervetuloa Suomeen!"},
    {"word":"lapsi","meaning":"trẻ em","example":"Lapsi nukkuu."},
    {"word":"aikuinen","meaning":"người lớn","example":"Olen aikuinen."},
    {"word":"ilta","meaning":"buổi tối","example":"Hyvää iltaa!"},
    {"word":"ystävä","meaning":"bạn bè","example":"Hän on hyvä ystävä."}]'::jsonb,
  '[{"lineIndex":2,"blanks":[{"wordIndex":0,"answer":"Lapsia"}]},
    {"lineIndex":4,"blanks":[{"wordIndex":1,"answer":"iltaa"}]}]'::jsonb,
  22, true);
