/**
 * Exam pictures for Cambridge Speaking Practice tasks.
 *
 * Every picture is assigned explicitly, task by task, in
 * `src/data/cambridgeSpeakingImageMap.ts` (generated by
 * scripts/gen_cambridge_speaking_image_map.ts). A task that is missing from
 * that map shows no picture at all, so a child never sees a photo that has
 * nothing to do with the question.
 *
 * The picture type always matches the exam format:
 *   - "Find the differences" tasks only get a two-picture (A/B) sheet
 *   - "Picture story" tasks only get a multi-panel story strip
 *   - Scene / object / photo tasks only get a single scene or photograph
 * @copyright 2026 HaiEduTech, ILC. All rights reserved.
 */
import { speakingImageMap } from "@/data/cambridgeSpeakingImageMap";

import stToys from "@/assets/cambridge-speaking/st-toys.jpg";
import stAnimals from "@/assets/cambridge-speaking/st-animals.jpg";
import stFood from "@/assets/cambridge-speaking/st-food.jpg";
import stFruit from "@/assets/cambridge-speaking/st-fruit.jpg";
import stClothes from "@/assets/cambridge-speaking/st-clothes.jpg";
import stBedroom from "@/assets/cambridge-speaking/st-bedroom.jpg";
import stSchoolbag from "@/assets/cambridge-speaking/st-schoolbag.jpg";
import stBalloons from "@/assets/cambridge-speaking/st-balloons.jpg";
import stBalls from "@/assets/cambridge-speaking/st-balls.jpg";
import stMonster from "@/assets/cambridge-speaking/st-monster.jpg";
import stPark from "@/assets/cambridge-speaking/st-park.jpg";
import stClassroom from "@/assets/cambridge-speaking/st-classroom.jpg";
import stFarm from "@/assets/cambridge-speaking/st-farm.jpg";
import stBeach from "@/assets/cambridge-speaking/st-beach.jpg";
import stHouse from "@/assets/cambridge-speaking/st-house.jpg";

import mvParkDiff from "@/assets/cambridge-speaking/mv-park-diff.jpg";
import mvClassroomDiff from "@/assets/cambridge-speaking/mv-classroom-diff.jpg";
import mvShopDiff from "@/assets/cambridge-speaking/mv-shop-diff.jpg";
import mvBedroomDiff from "@/assets/cambridge-speaking/mv-bedroom-diff.jpg";
import mvMarketDiff from "@/assets/cambridge-speaking/mv-market-diff.jpg";
import mvZooDiff from "@/assets/cambridge-speaking/mv-zoo-diff.jpg";
import flKitchenDiff from "@/assets/cambridge-speaking/fl-kitchen-diff.jpg";
import flMuseumDiff from "@/assets/cambridge-speaking/fl-museum-diff.jpg";
import flLibraryDiff from "@/assets/cambridge-speaking/fl-library-diff.jpg";
import flPartyDiff from "@/assets/cambridge-speaking/fl-party-diff.jpg";

import mvBeachStory from "@/assets/cambridge-speaking/mv-beach-story.jpg";
import mvLostCat from "@/assets/cambridge-speaking/mv-lost-cat.jpg";
import mvRainyStory from "@/assets/cambridge-speaking/mv-rainy-story.jpg";
import mvKiteStory from "@/assets/cambridge-speaking/mv-kite-story.jpg";
import mvCakeStory from "@/assets/cambridge-speaking/mv-cake-story.jpg";
import mvHelpingStory from "@/assets/cambridge-speaking/mv-helping-story.jpg";
import flCampingStory from "@/assets/cambridge-speaking/fl-camping-story.jpg";
import flSportsStory from "@/assets/cambridge-speaking/fl-sports-story.jpg";
import flKeysStory from "@/assets/cambridge-speaking/fl-keys-story.jpg";
import flPuppyStory from "@/assets/cambridge-speaking/fl-puppy-story.jpg";
import flNeighbourStory from "@/assets/cambridge-speaking/fl-neighbour-story.jpg";
import flVisitorStory from "@/assets/cambridge-speaking/fl-visitor-story.jpg";
import flTripStory from "@/assets/cambridge-speaking/fl-trip-story.jpg";

import flTownPlaces from "@/assets/cambridge-speaking/fl-town-places.jpg";
import keMarket from "@/assets/cambridge-speaking/ke-market.jpg";
import keSport from "@/assets/cambridge-speaking/ke-sport.jpg";
import keCelebration from "@/assets/cambridge-speaking/ke-celebration.jpg";
import keCafe from "@/assets/cambridge-speaking/ke-cafe.jpg";
import keBusstop from "@/assets/cambridge-speaking/ke-busstop.jpg";
import keLesson from "@/assets/cambridge-speaking/ke-lesson.jpg";
import keFamilyDinner from "@/assets/cambridge-speaking/ke-family-dinner.jpg";
import keCooking from "@/assets/cambridge-speaking/ke-cooking.jpg";
import kePhones from "@/assets/cambridge-speaking/ke-phones.jpg";
import keMusic from "@/assets/cambridge-speaking/ke-music.jpg";
import keWeather from "@/assets/cambridge-speaking/ke-weather.jpg";
import keJob from "@/assets/cambridge-speaking/ke-job.jpg";
import keParkSummer from "@/assets/cambridge-speaking/ke-park-summer.jpg";
import peStation from "@/assets/cambridge-speaking/pe-station.jpg";
import peFarm from "@/assets/cambridge-speaking/pe-farm.jpg";
import peLibrary from "@/assets/cambridge-speaking/pe-library.jpg";
import peTeamwork from "@/assets/cambridge-speaking/pe-teamwork.jpg";
import peTrain from "@/assets/cambridge-speaking/pe-train.jpg";
import peStudyGroup from "@/assets/cambridge-speaking/pe-study-group.jpg";
import peBeachClean from "@/assets/cambridge-speaking/pe-beach-clean.jpg";
import peMovingHome from "@/assets/cambridge-speaking/pe-moving-home.jpg";

export interface SpeakingImageTask {
  id: string;
  part: string;
  topic: string;
  prompt: string;
  level?: string;
}

/** Picture key -> bundled asset. Keys are the values stored in the task map. */
export const speakingImageAssets: Record<string, string> = {
  "st-toys": stToys,
  "st-animals": stAnimals,
  "st-food": stFood,
  "st-fruit": stFruit,
  "st-clothes": stClothes,
  "st-bedroom": stBedroom,
  "st-schoolbag": stSchoolbag,
  "st-balloons": stBalloons,
  "st-balls": stBalls,
  "st-monster": stMonster,
  "st-park": stPark,
  "st-classroom": stClassroom,
  "st-farm": stFarm,
  "st-beach": stBeach,
  "st-house": stHouse,
  "mv-park-diff": mvParkDiff,
  "mv-classroom-diff": mvClassroomDiff,
  "mv-shop-diff": mvShopDiff,
  "mv-bedroom-diff": mvBedroomDiff,
  "mv-market-diff": mvMarketDiff,
  "mv-zoo-diff": mvZooDiff,
  "fl-kitchen-diff": flKitchenDiff,
  "fl-museum-diff": flMuseumDiff,
  "fl-library-diff": flLibraryDiff,
  "fl-party-diff": flPartyDiff,
  "mv-beach-story": mvBeachStory,
  "mv-lost-cat": mvLostCat,
  "mv-rainy-story": mvRainyStory,
  "mv-kite-story": mvKiteStory,
  "mv-cake-story": mvCakeStory,
  "mv-helping-story": mvHelpingStory,
  "fl-camping-story": flCampingStory,
  "fl-sports-story": flSportsStory,
  "fl-keys-story": flKeysStory,
  "fl-puppy-story": flPuppyStory,
  "fl-neighbour-story": flNeighbourStory,
  "fl-visitor-story": flVisitorStory,
  "fl-trip-story": flTripStory,
  "fl-town-places": flTownPlaces,
  "ke-market": keMarket,
  "ke-sport": keSport,
  "ke-celebration": keCelebration,
  "ke-cafe": keCafe,
  "ke-busstop": keBusstop,
  "ke-lesson": keLesson,
  "ke-family-dinner": keFamilyDinner,
  "ke-cooking": keCooking,
  "ke-phones": kePhones,
  "ke-music": keMusic,
  "ke-weather": keWeather,
  "ke-job": keJob,
  "ke-park-summer": keParkSummer,
  "pe-station": peStation,
  "pe-farm": peFarm,
  "pe-library": peLibrary,
  "pe-teamwork": peTeamwork,
  "pe-train": peTrain,
  "pe-study-group": peStudyGroup,
  "pe-beach-clean": peBeachClean,
  "pe-moving-home": peMovingHome,
};

/** "Odd one out" cards list their four items in the prompt, so they never show a picture. */
const isOddOneOut = (task: SpeakingImageTask) =>
  /odd one out/i.test(task.part) || /which one is different|which one does not belong/i.test(task.prompt);

export const needsPicture = (task: SpeakingImageTask): boolean =>
  !isOddOneOut(task) && Boolean(speakingImageMap[task.id]);

export const imageForSpeakingTask = (task: SpeakingImageTask): string | undefined => {
  if (isOddOneOut(task)) return undefined;
  const key = speakingImageMap[task.id];
  return key ? speakingImageAssets[key] : undefined;
};

// Short instruction shown with the picture, per exam part.
export const pictureHint = (part: string): { vi: string; en: string } => {
  if (/differences/i.test(part)) return { vi: "So sánh hai tranh A và B rồi nói các điểm khác nhau.", en: "Compare pictures A and B and say what is different." };
  if (/story/i.test(part)) return { vi: "Nhìn các tranh theo thứ tự rồi kể lại câu chuyện.", en: "Look at the pictures in order, then tell the story." };
  if (/odd one out/i.test(part)) return { vi: "Nhìn nhóm tranh, chọn tranh khác loại và giải thích vì sao.", en: "Look at the set, choose the odd one out and say why." };
  if (/object cards/i.test(part)) return { vi: "Nhìn thẻ hình và nói về từng đồ vật.", en: "Look at the card and talk about each object." };
  if (/photo|Long turn/i.test(part)) return { vi: "Mô tả bức ảnh: người, nơi, hành động, cảm xúc.", en: "Describe the photo: people, place, actions, feelings." };
  return { vi: "Nhìn tranh và trả lời câu hỏi của giám thị.", en: "Look at the picture and answer the examiner." };
};
