/**
 * @file ieltsFullReadingExamsHard3.ts
 * @description Wave 7 - four additional high-difficulty IELTS Academic Reading
 *   passages (Cambridge "Passage 3" specification: 800-950 words of dense
 *   academic prose, answers deliberately out of passage order, full range of
 *   official task types).
 * @copyright 2026 HaiEduTech, ILC. All rights reserved.
 */
import type { ReadingExam } from "./ieltsFullReadingExams";

export const IELTS_FULL_READING_EXAMS_HARD3: ReadingExam[] = [
  // ============================================================
  // rx-hard-7 - The Sleeping Archive
  // ============================================================
  {
    id: "rx-hard-7",
    title: "Test 37 - The Sleeping Archive",
    level: "Hard",
    durationMinutes: 20,
    passageTitle: "The Sleeping Archive",
    passage:
`A. For most of the twentieth century sleep was treated as an interval in which the nervous system did very little. The electroencephalograph, introduced to sleep research in the 1930s, made that view untenable by revealing an architecture of stages that recur in cycles of roughly ninety minutes, each with its own electrical signature. What the instrument could not settle was the purpose of the arrangement. Two broad answers were proposed. The first held that sleep is restorative in a metabolic sense, allowing tissue repair and the clearance of waste products. The second, initially the less fashionable, held that sleep exists chiefly to process the previous day's experience, and that the price of a waking brain capable of learning is a sleeping brain obliged to file.

B. The filing hypothesis rests on a distinction between two forms of storage. Information acquired during the day is first held in the hippocampus, a structure well suited to rapid encoding but with limited capacity and a tendency to overwrite. Long-term retention depends on the gradual transfer of that information to the neocortex, where it is integrated with existing knowledge. Because the two structures cannot be trained simultaneously without interference, the transfer must happen when the hippocampus is not receiving new input, which is to say during sleep. The theory therefore predicts something specific and testable: the sequences of neural firing recorded while an animal learns a task should reappear, unprompted, while it sleeps.

C. They do. Recordings from rodents navigating a maze show that the place cells activated at each point on the route fire again during subsequent slow-wave sleep, in the same order but compressed to perhaps a twentieth of the original duration. The phenomenon, known as replay, is not a curiosity of rodent physiology; comparable patterns have since been detected in human recordings obtained during clinical monitoring. More telling is that the amount of replay predicts performance the following day, and that disrupting the electrical oscillations with which replay is coordinated impairs retention without shortening sleep at all. It is the structure of the sleep, rather than its quantity, that appears to matter.

D. Different stages of sleep have proved to serve different kinds of memory, a finding that has survived a good deal of scepticism. Deep slow-wave sleep, concentrated in the first half of the night, favours declarative material: lists of words, pairs of names, the location of objects. Rapid eye movement sleep, which dominates the later hours, is associated instead with procedural skills and with emotional regulation. The practical consequence is uncomfortable for students. A night truncated at four hours removes a disproportionate share of REM sleep, while a late start followed by an early alarm cuts into the slow-wave phase that consolidates precisely the factual material an examination will test.

E. Selection is as important as storage. The sleeping brain does not preserve the day indiscriminately, and evidence from a series of experiments suggests that it privileges what the waking brain has marked as significant. Participants told before sleeping that they would be tested on one of two lists retained the designated list substantially better, although the instruction was given hours before sleep and never repeated. Reward has a similar effect: material associated with a small payment is consolidated more strongly than neutral material learned in the same session. What is discarded may matter as much as what is kept, since a memory system that retained everything would rapidly become unusable.

F. Consolidation also transforms. Sleep does not merely strengthen individual traces; it abstracts the regularity that connects them. In studies of artificial grammars, participants exposed to strings of syllables generated by a hidden rule are able, after sleep, to classify new strings they have never encountered, an ability that does not emerge after an equivalent period of quiet wakefulness. Similar results have been reported for arithmetic shortcuts and for the insight required to solve certain puzzles. The interpretation favoured by most researchers is that replay strips away the incidental detail of each episode, leaving the structure common to all of them, which is close to what psychologists mean by understanding.

G. The clinical implications are still being worked out, and the field has learned caution. Attempts to enhance consolidation artificially, whether by acoustic stimulation timed to slow-wave oscillations or by cueing memories with odours reintroduced during sleep, produce reliable effects in the laboratory that have so far been modest and short-lived outside it. Enthusiasm for sleep-based learning devices has consequently outrun the evidence. What is no longer in doubt is the negative case: chronic restriction of sleep degrades the acquisition of new material and accelerates the loss of old material, and it does so in ways that the person affected consistently fails to notice. The archive is assembled at night, and its curator does not report on its work.`,
    questions: [
      { number: 1, type: "matching-headings", prompt: "Choose the best heading for Paragraph E.",
        instruction: "Choose the correct heading from the list below. There are more headings than paragraphs, so some headings will not be used.",
        headings: [
          { label: "i", text: "Choosing what deserves to be kept" },
          { label: "ii", text: "Two competing accounts of why we sleep" },
          { label: "iii", text: "Evidence from animals running a maze" },
          { label: "iv", text: "The disappointing record of enhancement" },
        ], answer: "i",
        explanation: "Paragraph E argues the sleeping brain privileges material the waking brain has marked as significant, and that discarding matters too." },
      { number: 2, type: "matching-headings", prompt: "Choose the best heading for Paragraph F.",
        headings: [
          { label: "i", text: "From episodes to rules" },
          { label: "ii", text: "Choosing what deserves to be kept" },
          { label: "iii", text: "How the instrument changed the question" },
          { label: "iv", text: "Two stores, one transfer" },
        ], answer: "i",
        explanation: "Paragraph F describes abstraction of hidden regularities from individual traces, illustrated by the artificial grammar studies." },
      { number: 3, type: "matching-headings", prompt: "Choose the best heading for Paragraph B.",
        headings: [
          { label: "i", text: "Two stores, one transfer" },
          { label: "ii", text: "From episodes to rules" },
          { label: "iii", text: "Consequences for the student" },
          { label: "iv", text: "Evidence from animals running a maze" },
        ], answer: "i",
        explanation: "Paragraph B sets out hippocampal encoding and gradual transfer to the neocortex as the basis of the filing hypothesis." },
      { number: 4, type: "matching-headings", prompt: "Choose the best heading for Paragraph D.",
        headings: [
          { label: "i", text: "A division of labour across the night" },
          { label: "ii", text: "Two stores, one transfer" },
          { label: "iii", text: "The limits of laboratory cueing" },
          { label: "iv", text: "Two competing accounts of why we sleep" },
        ], answer: "i",
        explanation: "Paragraph D contrasts what slow-wave sleep and REM sleep each consolidate, and the effect of cutting either short." },
      { number: 5, type: "matching-headings", prompt: "Choose the best heading for Paragraph G.",
        headings: [
          { label: "i", text: "Promise, caution and one settled finding" },
          { label: "ii", text: "A division of labour across the night" },
          { label: "iii", text: "Rodent recordings in detail" },
          { label: "iv", text: "The metabolic account" },
        ], answer: "i",
        explanation: "Paragraph G reports modest enhancement results, urges caution, and states the negative case as no longer in doubt." },

      { number: 6, type: "tfng", prompt: "Replay sequences recorded during sleep unfold at a slower rate than the original experience.",
        instruction: "Do the following statements agree with the information given in the passage? Write TRUE, FALSE or NOT GIVEN.",
        answer: "False",
        explanation: "Paragraph C states replay occurs 'in the same order but compressed to perhaps a twentieth of the original duration', so it is faster, not slower." },
      { number: 7, type: "tfng", prompt: "Interfering with the oscillations that organise replay reduces memory even when total sleep time is unchanged.",
        answer: "True",
        explanation: "Paragraph C: disrupting the oscillations 'impairs retention without shortening sleep at all'." },
      { number: 8, type: "tfng", prompt: "Replay has been observed in more species of mammal than in birds.",
        answer: "Not Given",
        explanation: "The passage mentions rodents and humans only; no comparison with birds is made." },
      { number: 9, type: "tfng", prompt: "People whose sleep is chronically restricted are usually aware of the resulting decline in their learning.",
        answer: "False",
        explanation: "Paragraph G says the effects occur 'in ways that the person affected consistently fails to notice'." },

      { number: 10, type: "matching-features", prompt: "Material learned as a list of word pairs is consolidated mainly during this stage.",
        instruction: "Match each item with the correct stage of sleep, A-D. You may use any letter once only.",
        features: [
          { label: "A", text: "Slow-wave sleep" },
          { label: "B", text: "Rapid eye movement sleep" },
          { label: "C", text: "Quiet wakefulness" },
          { label: "D", text: "The transition to waking" },
        ], answer: "A",
        explanation: "Paragraph D links deep slow-wave sleep with declarative material such as lists and pairs." },
      { number: 11, type: "matching-features", prompt: "Motor skills and the handling of emotional material are associated with this stage.",
        features: [
          { label: "A", text: "Slow-wave sleep" },
          { label: "B", text: "Rapid eye movement sleep" },
          { label: "C", text: "Quiet wakefulness" },
          { label: "D", text: "The transition to waking" },
        ], answer: "B",
        explanation: "Paragraph D: REM sleep 'is associated instead with procedural skills and with emotional regulation'." },

      { number: 12, type: "fill-blank", prompt: "The reappearance of learning-related firing patterns during sleep is known as ___.",
        instruction: "Complete the sentences with ONE WORD ONLY from the passage.",
        answer: "replay",
        explanation: "Paragraph C names the phenomenon 'replay'." },
      { number: 13, type: "fill-blank", prompt: "Long-term retention requires that information be moved from the hippocampus to the ___.",
        answer: "neocortex",
        explanation: "Paragraph B: retention depends on transfer 'to the neocortex, where it is integrated with existing knowledge'." },
      { number: 14, type: "mcq-multi", prompt: "Which TWO findings does the writer present as evidence that consolidation is selective?",
        instruction: "Choose TWO letters, A-E.",
        options: [
          "A. Participants warned that one list would be tested remembered that list better.",
          "B. Material linked to a small payment was retained more strongly.",
          "C. Replay occurs in compressed sequences.",
          "D. REM sleep dominates the second half of the night.",
          "E. Acoustic stimulation produces short-lived gains.",
        ],
        answers: ["A", "B"], answer: "A",
        explanation: "Paragraph E offers the instruction experiment and the reward experiment as evidence of selection; the other options concern different points." },
    ],
  },

  // ============================================================
  // rx-hard-8 - Salt in the Furrows
  // ============================================================
  {
    id: "rx-hard-8",
    title: "Test 38 - Salt in the Furrows",
    level: "Hard",
    durationMinutes: 20,
    passageTitle: "Salt in the Furrows",
    passage:
`A. The southern plain of Mesopotamia produced the earliest cities, the earliest written archives and, by most reckonings, the earliest bureaucratic state. It is an improbable setting for any of these achievements. Rainfall on the lower Euphrates is too slight and too erratic to support a cereal crop, and the summer heat is severe. Agriculture there was possible only because the two rivers carried water from mountains far to the north and could be diverted, in a season of high flow, along channels cut through soft alluvium. Everything that followed, including the temple economy and the accounting tablets that record it, rested on the maintenance of those channels.

B. Irrigation of this kind imposes obligations that rain-fed farming does not. Channels silt up within a few years and must be cleared by gangs whose work has to be organised, fed and supervised. Because a canal serves many fields, the timing of water release cannot be left to individual cultivators, and disputes over it require an authority capable of enforcing a decision. Historians once presented this necessity as the direct cause of centralised government, an argument associated with the mid-twentieth-century notion of the hydraulic state. The current view is more guarded. Small irrigation systems were managed for centuries by local agreement in several regions, so scale, not irrigation as such, appears to be the relevant variable, and causation may well have run in both directions.

C. The archives themselves record a problem that the earliest excavators did not anticipate. Tablets from the third millennium BC list yields of barley and of wheat side by side; over several centuries the proportion of wheat declines steadily until it almost disappears, leaving barley as effectively the only crop of the southern fields. Recorded yields fall in the same period, in some districts by more than half. No invasion, epidemic or climatic event of the required timing accounts for the pattern, and the decline is too gradual and too consistent for any single catastrophe.

D. The explanation now generally accepted is salinisation. River water carries dissolved salts, in small concentrations but continuously. Where the water is applied to fields in a hot climate and much of it evaporates rather than draining away, the salts remain and accumulate in the upper soil. Two conditions make the process rapid. The first is a high water table, which in a flat plain with poorly drained subsoil rises whenever irrigation is intensive, drawing salt upward towards the roots by capillary action. The second is the absence of a fallow period long enough for the accumulated salt to be flushed below the root zone. The pattern preserved in the tablets is exactly what salinisation would produce, because wheat is markedly less tolerant of salt than barley: as concentrations rise, wheat fails first, and the ratio of the two crops becomes a record of the soil's condition.

E. The response of the administration can be traced in the same documents, and it was not passive. Texts refer to the practice of leaving land in weeds for a season, a form of long fallow that lowers the water table and permits leaching. There are records of fields being taken out of cultivation altogether and of new land being opened at the margins of the system. What the archives do not show is a sustained reduction in the area under irrigation, which is what the underlying problem required. The obligations of the state, including rations for dependent labour and the provisioning of temples, made a deliberate contraction of the cultivated area politically very difficult, and each new canal extension postponed the reckoning while enlarging its eventual scale.

F. It would be a mistake to compress several centuries into a simple morality tale, and specialists have resisted doing so. The southern plain was not abandoned; population and political weight shifted gradually northwards, towards Babylon and the middle Euphrates, where soils drained more freely and where the same techniques could be applied for longer without penalty. Nor was the technology at fault. The same methods, in different hydrological conditions, sustained cultivation for millennia elsewhere. The failure lay in the combination of a particular soil, a particular climate and an institutional arrangement that measured success by the area sown and the quantity delivered, while the variable that mattered most was invisible to the accounting system.

G. That last point explains why the case is still discussed outside archaeology. Roughly a fifth of the world's irrigated land is now affected by salinity to some degree, and the areas at greatest risk, in Pakistan, in Central Asia and in parts of Australia, share the features that made southern Mesopotamia vulnerable: flat terrain, high evaporation, restricted drainage and a strong administrative incentive to keep the water flowing. Modern engineering can address the physical problem, chiefly through subsurface drainage, at a cost that is high but calculable. The harder difficulty is the one the tablets illustrate, which is that a slow, cumulative and largely unmeasured loss will always compete for attention with an urgent and clearly quantified demand, and will usually lose.`,
    questions: [
      { number: 1, type: "matching-headings", prompt: "Choose the best heading for Paragraph D.",
        instruction: "Choose the correct heading from the list below. There are more headings than paragraphs, so some headings will not be used.",
        headings: [
          { label: "i", text: "How salt accumulates and which crop reveals it" },
          { label: "ii", text: "An unlikely place for the first cities" },
          { label: "iii", text: "A pattern in the barley and wheat figures" },
          { label: "iv", text: "Modern land at similar risk" },
        ], answer: "i",
        explanation: "Paragraph D explains the mechanism of salinisation and why the wheat-to-barley ratio records soil condition." },
      { number: 2, type: "matching-headings", prompt: "Choose the best heading for Paragraph F.",
        headings: [
          { label: "i", text: "Against the simple moral" },
          { label: "ii", text: "How salt accumulates and which crop reveals it" },
          { label: "iii", text: "The demands of canal maintenance" },
          { label: "iv", text: "Measures taken by the administration" },
        ], answer: "i",
        explanation: "Paragraph F resists the morality tale, noting the northward shift and that the technology itself was not at fault." },
      { number: 3, type: "matching-headings", prompt: "Choose the best heading for Paragraph B.",
        headings: [
          { label: "i", text: "Obligations created by canals" },
          { label: "ii", text: "Against the simple moral" },
          { label: "iii", text: "An unlikely place for the first cities" },
          { label: "iv", text: "Two conditions for rapid loss" },
        ], answer: "i",
        explanation: "Paragraph B describes silt clearance, water scheduling and dispute settlement as obligations irrigation imposes." },
      { number: 4, type: "matching-headings", prompt: "Choose the best heading for Paragraph E.",
        headings: [
          { label: "i", text: "What the state did, and what it could not do" },
          { label: "ii", text: "Obligations created by canals" },
          { label: "iii", text: "The hydraulic state debate" },
          { label: "iv", text: "A pattern in the crop figures" },
        ], answer: "i",
        explanation: "Paragraph E records fallowing and new land, but notes no sustained reduction in irrigated area was politically possible." },
      { number: 5, type: "matching-headings", prompt: "Choose the best heading for Paragraph G.",
        headings: [
          { label: "i", text: "Why the case still matters" },
          { label: "ii", text: "What the state did, and what it could not do" },
          { label: "iii", text: "Reading the archives" },
          { label: "iv", text: "Obligations created by canals" },
        ], answer: "i",
        explanation: "Paragraph G applies the case to modern irrigated land and to the problem of unmeasured cumulative loss." },

      { number: 6, type: "ynng", prompt: "The writer accepts the mid-twentieth-century view that irrigation by itself produced centralised government.",
        instruction: "Do the following statements agree with the views of the writer? Write YES, NO or NOT GIVEN.",
        answer: "No",
        explanation: "Paragraph B calls the current view 'more guarded' and identifies scale rather than irrigation as the relevant variable." },
      { number: 7, type: "ynng", prompt: "The writer regards the irrigation techniques used on the southern plain as inherently defective.",
        answer: "No",
        explanation: "Paragraph F states 'nor was the technology at fault', since the same methods worked elsewhere for millennia." },
      { number: 8, type: "ynng", prompt: "The writer thinks the institutional incentives of the period made the underlying problem harder to address than the physical conditions did.",
        answer: "Yes",
        explanation: "Paragraphs E and G attribute the failure to accounting and incentives, calling that 'the harder difficulty'." },

      { number: 9, type: "matching-endings", prompt: "The steady decline of wheat in the tablet records",
        instruction: "Complete each sentence with the correct ending, A-E.",
        endings: [
          { label: "A", text: "indicates rising salt concentrations in the upper soil." },
          { label: "B", text: "followed a documented epidemic in the southern cities." },
          { label: "C", text: "was caused by a change in temple dietary preferences." },
          { label: "D", text: "shows that canals had been abandoned entirely." },
          { label: "E", text: "resulted from a sudden shift in the river's course." },
        ], answer: "A",
        explanation: "Paragraph D: wheat is less salt-tolerant than barley, so its decline records the soil's deterioration." },
      { number: 10, type: "matching-endings", prompt: "Opening new land at the edges of the system",
        endings: [
          { label: "A", text: "delayed the crisis while making it larger." },
          { label: "B", text: "reduced the total area under irrigation." },
          { label: "C", text: "lowered the water table across the plain." },
          { label: "D", text: "eliminated the need for fallow periods." },
          { label: "E", text: "was forbidden by the temple archives." },
        ], answer: "A",
        explanation: "Paragraph E: 'each new canal extension postponed the reckoning while enlarging its eventual scale'." },

      { number: 11, type: "fill-blank", prompt: "Salt is drawn towards the root zone by ___ action when the water table is high.",
        instruction: "Complete the sentences with ONE WORD ONLY from the passage.",
        answer: "capillary",
        explanation: "Paragraph D: a high water table draws salt upward 'by capillary action'." },
      { number: 12, type: "fill-blank", prompt: "Political and economic weight moved gradually towards ___ and the middle Euphrates.",
        answer: "Babylon",
        explanation: "Paragraph F: the shift was 'northwards, towards Babylon and the middle Euphrates'." },
      { number: 13, type: "multiple-choice", prompt: "According to the passage, what proportion of irrigated land worldwide is now affected by salinity to some degree?",
        options: ["About a twentieth", "About a tenth", "About a fifth", "About a half"],
        answer: "About a fifth",
        explanation: "Paragraph G: 'roughly a fifth of the world's irrigated land is now affected by salinity to some degree'." },
      { number: 14, type: "multiple-choice", prompt: "Which feature is NOT listed as shared by modern high-risk regions and southern Mesopotamia?",
        options: ["Flat terrain", "High evaporation", "Restricted drainage", "Heavy seasonal rainfall"],
        answer: "Heavy seasonal rainfall",
        explanation: "Paragraph G lists flat terrain, high evaporation, restricted drainage and administrative incentives, not rainfall." },
    ],
  },

  // ============================================================
  // rx-hard-9 - The City as a Stone
  // ============================================================
  {
    id: "rx-hard-9",
    title: "Test 39 - The City as a Stone",
    level: "Hard",
    durationMinutes: 20,
    passageTitle: "The City as a Stone",
    passage:
`A. In 1818 the chemist Luke Howard published a study of London's climate based on a decade of readings taken inside the city and in the surrounding countryside. He found that the urban thermometer stood consistently higher, and that the difference was greatest not at noon but in the hours before dawn. Howard had no term for what he had discovered and no theory adequate to explain it, but his measurements were sound, and the phenomenon he described has since been documented in cities on every inhabited continent. It is now called the urban heat island, and the modern interest in it is less climatological than actuarial: heat is the deadliest of the common weather hazards in most temperate countries, and it is a hazard that construction largely creates.

B. The effect has four principal causes, and their relative weight is often misunderstood. The most important is thermal mass. Brick, asphalt and concrete store far more heat than vegetation or soil and release it slowly through the night, which is why the urban-rural difference peaks in darkness rather than in the afternoon sun. The second is the loss of evaporative cooling. A mature tree moves hundreds of litres of water a day from soil to atmosphere, and the energy consumed in that change of state does not go into raising the air temperature; paving a surface removes this mechanism entirely. The third is geometry: streets flanked by tall buildings trap radiation in repeated reflections and restrict the sky view through which heat escapes at night. The fourth, waste heat from engines, machinery and air conditioning, is real but usually the smallest contributor except in dense commercial districts in winter.

C. Because the causes are physical rather than meteorological, the size of the effect varies enormously between cities of similar climate and similar population. Compact European cities with narrow streets and little vegetation record night-time differences of two to four degrees; a low-density North American city with extensive tree cover may record less than one. Within a single city the range is often larger than between cities. Surveys using vehicle-mounted sensors in Los Angeles and in Melbourne have found differences of six or seven degrees between neighbourhoods a few kilometres apart, and those differences correlate strongly with tree canopy and, through it, with income. Heat exposure is thus distributed with the same inequality as shade.

D. The consequences are measured chiefly in mortality, and the accounting is not straightforward. Deaths during a heatwave are rarely certified as heat deaths; they appear as cardiac or respiratory events in people whose reserve capacity was already marginal. Epidemiologists therefore estimate excess mortality by comparing observed deaths with the number expected in the same weeks of unexceptional years. On that basis the European heatwave of 2003 is credited with more than seventy thousand additional deaths. The same method shows that night-time temperature is the better predictor of mortality, because the body's tolerance of daytime heat depends on the opportunity to cool down after dark, and it is precisely the night that the urban heat island warms most.

E. Remedies fall into three groups, of which the simplest is the alteration of surfaces. A white or pale roof reflects most of the radiation that a dark one absorbs, and large-scale programmes in Ahmedabad and New York have lowered indoor temperatures in unconditioned buildings by several degrees at trivial cost. The limitation is that reflective surfaces do nothing for the pedestrian, and may on some street geometries increase the radiation reaching people at ground level. Vegetation, the second group, acts on both air temperature and radiant load, but demands water in the season when water is scarcest and, in the case of street trees, a fifteen-year wait before the canopy is useful. The third group is design: orienting streets to catch prevailing winds, opening corridors to allow night air to drain from higher ground, and restoring watercourses that were culverted in the nineteenth century.

F. Air conditioning occupies an awkward position in this literature. It is unambiguously effective for the individual and has reduced heat mortality wherever it has become widespread. It also warms the street it stands on, consumes electricity at exactly the moment when the grid is most stressed, and protects only those able to pay for it, so that a city which adapts through cooling equipment alone concentrates risk on the households least able to bear it. Most researchers now treat it as necessary and insufficient, arguing that the useful comparison is not between cooling and shade but between a city that requires continuous cooling to be habitable and one that does not.

G. The lesson drawn from three decades of measurement is that the urban heat island is a design outcome, not a climatic fact. Two districts in the same city, subject to the same synoptic weather, can differ in night-time temperature by more than the total warming projected for the century, and the difference is explained by materials, canopy and street width. That is an unusual position for a climate problem to be in, because it means the principal instruments are municipal rather than international: planning codes, tree budgets, surface albedo standards and the protection of ventilation corridors. Howard's readings suggested as much two centuries ago, in a city that had not yet begun to build the surfaces which now hold its heat.`,
    questions: [
      { number: 1, type: "matching-headings", prompt: "Choose the best heading for Paragraph B.",
        instruction: "Choose the correct heading from the list below. There are more headings than paragraphs, so some headings will not be used.",
        headings: [
          { label: "i", text: "Four mechanisms, unequally weighted" },
          { label: "ii", text: "An early observation in London" },
          { label: "iii", text: "Counting the deaths" },
          { label: "iv", text: "Three families of remedy" },
        ], answer: "i",
        explanation: "Paragraph B sets out thermal mass, lost evaporation, street geometry and waste heat, noting their relative weight." },
      { number: 2, type: "matching-headings", prompt: "Choose the best heading for Paragraph C.",
        headings: [
          { label: "i", text: "Wide variation, and who bears it" },
          { label: "ii", text: "Four mechanisms, unequally weighted" },
          { label: "iii", text: "The ambiguous role of cooling equipment" },
          { label: "iv", text: "A problem of design, not climate" },
        ], answer: "i",
        explanation: "Paragraph C reports differences between and within cities and their correlation with canopy and income." },
      { number: 3, type: "matching-headings", prompt: "Choose the best heading for Paragraph E.",
        headings: [
          { label: "i", text: "Three families of remedy" },
          { label: "ii", text: "Wide variation, and who bears it" },
          { label: "iii", text: "An early observation in London" },
          { label: "iv", text: "Why nights matter most" },
        ], answer: "i",
        explanation: "Paragraph E groups remedies into surfaces, vegetation and design, with the limits of each." },
      { number: 4, type: "matching-headings", prompt: "Choose the best heading for Paragraph F.",
        headings: [
          { label: "i", text: "The ambiguous role of cooling equipment" },
          { label: "ii", text: "Three families of remedy" },
          { label: "iii", text: "Counting the deaths" },
          { label: "iv", text: "Four mechanisms, unequally weighted" },
        ], answer: "i",
        explanation: "Paragraph F weighs the benefits of air conditioning against its street-level and distributional costs." },
      { number: 5, type: "matching-headings", prompt: "Choose the best heading for Paragraph G.",
        headings: [
          { label: "i", text: "A municipal problem after all" },
          { label: "ii", text: "The ambiguous role of cooling equipment" },
          { label: "iii", text: "Wide variation, and who bears it" },
          { label: "iv", text: "Measuring with vehicle sensors" },
        ], answer: "i",
        explanation: "Paragraph G argues the instruments are municipal: planning codes, tree budgets, albedo standards, ventilation corridors." },

      { number: 6, type: "tfng", prompt: "Howard was able to explain the temperature difference he recorded between London and its surroundings.",
        instruction: "Do the following statements agree with the information given in the passage? Write TRUE, FALSE or NOT GIVEN.",
        answer: "False",
        explanation: "Paragraph A: he 'had no term for what he had discovered and no theory adequate to explain it'." },
      { number: 7, type: "tfng", prompt: "Waste heat from machinery is generally the largest single cause of urban warming.",
        answer: "False",
        explanation: "Paragraph B calls waste heat 'usually the smallest contributor', with thermal mass the most important." },
      { number: 8, type: "tfng", prompt: "Differences in night-time temperature between neighbourhoods of one city can exceed the warming projected for this century.",
        answer: "True",
        explanation: "Paragraph G states two districts can differ 'by more than the total warming projected for the century'." },
      { number: 9, type: "tfng", prompt: "Pale roofs have been shown to reduce street-level temperatures for pedestrians.",
        answer: "False",
        explanation: "Paragraph E says reflective surfaces 'do nothing for the pedestrian' and may increase radiation at ground level." },

      { number: 10, type: "summary-completion", prompt: "Epidemiologists estimate the toll of a heatwave using ___ mortality, comparing observed deaths with those expected in ordinary years.",
        instruction: "Complete the summary using the list of words, A-F, below.",
        wordBank: [
          { label: "A", text: "excess" },
          { label: "B", text: "certified" },
          { label: "C", text: "reflected" },
          { label: "D", text: "seasonal" },
          { label: "E", text: "cardiac" },
          { label: "F", text: "projected" },
        ], answer: "A",
        explanation: "Paragraph D: they 'estimate excess mortality by comparing observed deaths with the number expected'." },
      { number: 11, type: "fill-blank", prompt: "Street trees need roughly a ___ wait before their canopy becomes useful.",
        instruction: "Complete the sentence with NO MORE THAN TWO WORDS from the passage.",
        answer: "fifteen-year",
        explanation: "Paragraph E refers to 'a fifteen-year wait before the canopy is useful'." },
      { number: 12, type: "fill-blank", prompt: "The energy used when a tree moves water into the air is lost to ___ cooling rather than heating the air.",
        answer: "evaporative",
        explanation: "Paragraph B describes the loss of 'evaporative cooling' when surfaces are paved." },
      { number: 13, type: "multiple-choice", prompt: "Why is night-time temperature the better predictor of heat mortality?",
        options: [
          "Because most deaths are recorded during the night.",
          "Because tolerance of daytime heat depends on cooling down after dark.",
          "Because waste heat is released mainly at night.",
          "Because measurements are more accurate at night.",
        ],
        answer: "Because tolerance of daytime heat depends on cooling down after dark.",
        explanation: "Paragraph D gives exactly this reason, adding that the heat island warms the night most." },
      { number: 14, type: "multiple-choice", prompt: "How do most researchers now regard air conditioning?",
        options: [
          "As the principal solution to urban heat",
          "As ineffective for individual households",
          "As necessary but not sufficient",
          "As irrelevant to mortality figures",
        ],
        answer: "As necessary but not sufficient",
        explanation: "Paragraph F: 'most researchers now treat it as necessary and insufficient'." },
    ],
  },

  // ============================================================
  // rx-hard-10 - Bringing Back the Dead
  // ============================================================
  {
    id: "rx-hard-10",
    title: "Test 40 - Bringing Back the Dead",
    level: "Hard",
    durationMinutes: 20,
    passageTitle: "Bringing Back the Dead",
    passage:
`A. In 2003 a team of Spanish and French scientists produced a living kid of the Pyrenean ibex, a subspecies whose last individual had been killed by a falling tree three years earlier. The animal died of a lung defect within minutes of birth. The experiment is usually reported as the first de-extinction, and it established both the technical plausibility of the enterprise and the pattern of its results: a single short-lived individual, a great deal of publicity, and no population. Two decades later the field remains in that condition, which has not prevented it from acquiring substantial private funding and a prominent place in public argument about the loss of species.

B. Three methods are under discussion, and they differ so much that treating them as one project obscures more than it reveals. Cloning, the method used with the ibex, requires an intact cell nucleus and is therefore restricted to animals that died recently enough for tissue to have been frozen. Selective back-breeding works with living relatives, choosing in each generation for the traits of the vanished form; it produces something that resembles the original without recovering its genome, and it is what the twentieth-century attempts to recreate the aurochs actually achieved. Genome editing, the current favourite, begins with a close living relative and alters the sequences that differ, so that the product is a modified elephant carrying mammoth traits rather than a mammoth. Proponents of the third method concede the point and argue that ecological function, not taxonomic identity, is what matters.

C. Function is the strongest version of the case. The argument holds that certain lost animals were keystone species whose removal reorganised whole systems, and that restoring the function would restore the system. Large grazers of the northern steppe are the standard example: by trampling snow they exposed ground to winter cold, kept the permafrost colder and suppressed the shrubs that now insulate it. An animal capable of doing that work again, whatever its ancestry, would arguably be worth creating on climate grounds alone. The counter-argument is that the ecosystems in question no longer exist in the form the animal inhabited, that the vegetation, the parasites and the human land use have all changed, and that a species reintroduced into a transformed system behaves unpredictably, as the history of ordinary reintroductions demonstrates.

D. The technical obstacles are also more serious than the coverage suggests. DNA degrades after death into fragments of a few hundred base pairs, and reconstructing a genome from them requires a reference sequence from a living relative, which means every recovered genome is partly a hypothesis. Cloning requires a surrogate mother of a compatible species, which for the mammoth means an Asian elephant with a twenty-two-month pregnancy and a poor record in captive breeding. Beyond the individual lies the harder problem of a founding population: enough animals, with enough genetic variation, and in the case of long-lived social species a transmitted culture of migration routes and feeding behaviour that no laboratory can supply. Nothing in the field so far has approached this stage.

E. Conservation biologists have raised a distinct objection that concerns money and attention rather than science. Budgets for protecting species are small and are contested annually; the sums spent on de-extinction, though modest by the standards of biotechnology, are large by the standards of a national park. One frequently cited analysis argued that the funds required to establish a single revived species would, if spent on habitat protection for existing threatened ones, secure a much larger number of them, and that the true cost of the glamorous project is therefore measured in the ordinary species not saved. Defenders reply that the money comes largely from private donors who would not otherwise fund conservation at all, an empirical claim that has not been tested.

F. A subtler worry concerns incentives. If extinction comes to be seen as reversible, the moral weight attached to preventing it may diminish, in the same way that the availability of a remedy tends to reduce the perceived urgency of prevention. Surveys of public attitudes give some support to this concern, though the effect is modest and the studies are few. Legislators, meanwhile, have an obvious interest in a technology that promises to convert an irreversible loss into a deferred expense, and the regulatory categories are not ready: it is unsettled whether an edited elephant would count as an endangered species, a genetically modified organism, or neither.

G. The most defensible conclusion is that the techniques matter more than the goal. Ancient DNA methods developed for de-extinction have transformed the study of population history, and the same editing tools are being applied to living species with encouraging results, from resistance to the fungal disease devastating amphibians to blight resistance in the American chestnut. That work rescues organisms that still exist and can still occupy their habitats, and it attracts a fraction of the attention. The mammoth, in other words, may turn out to have been useful mainly as a fundraising device for a laboratory whose serious products are directed at species that have not yet been lost.`,
    questions: [
      { number: 1, type: "matching-headings", prompt: "Choose the best heading for Paragraph B.",
        instruction: "Choose the correct heading from the list below. There are more headings than paragraphs, so some headings will not be used.",
        headings: [
          { label: "i", text: "Three unlike methods" },
          { label: "ii", text: "An experiment that lasted minutes" },
          { label: "iii", text: "The argument from ecological function" },
          { label: "iv", text: "Where the tools are genuinely useful" },
        ], answer: "i",
        explanation: "Paragraph B distinguishes cloning, back-breeding and genome editing and notes how different they are." },
      { number: 2, type: "matching-headings", prompt: "Choose the best heading for Paragraph D.",
        headings: [
          { label: "i", text: "From one animal to a viable population" },
          { label: "ii", text: "Three unlike methods" },
          { label: "iii", text: "Competing claims on a small budget" },
          { label: "iv", text: "Unsettled legal categories" },
        ], answer: "i",
        explanation: "Paragraph D moves from DNA fragments and surrogates to the harder problem of a founding population with culture." },
      { number: 3, type: "matching-headings", prompt: "Choose the best heading for Paragraph E.",
        headings: [
          { label: "i", text: "Competing claims on a small budget" },
          { label: "ii", text: "From one animal to a viable population" },
          { label: "iii", text: "The effect on public motivation" },
          { label: "iv", text: "Three unlike methods" },
        ], answer: "i",
        explanation: "Paragraph E is the opportunity-cost objection about conservation funding and attention." },
      { number: 4, type: "matching-headings", prompt: "Choose the best heading for Paragraph F.",
        headings: [
          { label: "i", text: "If loss looks reversible" },
          { label: "ii", text: "Competing claims on a small budget" },
          { label: "iii", text: "The argument from ecological function" },
          { label: "iv", text: "An experiment that lasted minutes" },
        ], answer: "i",
        explanation: "Paragraph F concerns weakened incentives to prevent extinction, plus unready regulation." },
      { number: 5, type: "matching-headings", prompt: "Choose the best heading for Paragraph G.",
        headings: [
          { label: "i", text: "Where the tools are genuinely useful" },
          { label: "ii", text: "If loss looks reversible" },
          { label: "iii", text: "Three unlike methods" },
          { label: "iv", text: "The steppe grazer example" },
        ], answer: "i",
        explanation: "Paragraph G concludes the techniques, applied to living species, are the serious product." },

      { number: 6, type: "ynng", prompt: "The writer accepts that a genome-edited animal would be the same species as the one that died out.",
        instruction: "Do the following statements agree with the views of the writer? Write YES, NO or NOT GIVEN.",
        answer: "No",
        explanation: "Paragraph B describes the product as 'a modified elephant carrying mammoth traits rather than a mammoth'." },
      { number: 7, type: "ynng", prompt: "The writer regards the claim that de-extinction money is additional to conservation funding as unproven.",
        answer: "Yes",
        explanation: "Paragraph E calls it 'an empirical claim that has not been tested'." },
      { number: 8, type: "ynng", prompt: "The writer believes the ecological function argument is the least persuasive part of the case.",
        answer: "No",
        explanation: "Paragraph C calls function 'the strongest version of the case'." },
      { number: 9, type: "ynng", prompt: "The writer thinks gene-editing work on living threatened species receives less notice than it deserves.",
        answer: "Yes",
        explanation: "Paragraph G notes such work 'attracts a fraction of the attention' while rescuing organisms that still exist." },

      { number: 10, type: "matching-features", prompt: "This method produced an animal resembling a lost form without recovering its genome.",
        instruction: "Match each statement with the correct method, A-D.",
        features: [
          { label: "A", text: "Cloning from frozen tissue" },
          { label: "B", text: "Selective back-breeding" },
          { label: "C", text: "Genome editing of a living relative" },
          { label: "D", text: "Captive breeding of surviving individuals" },
        ], answer: "B",
        explanation: "Paragraph B: back-breeding 'produces something that resembles the original without recovering its genome'." },
      { number: 11, type: "matching-features", prompt: "This method can only be used on species that disappeared recently enough for cells to be preserved.",
        features: [
          { label: "A", text: "Cloning from frozen tissue" },
          { label: "B", text: "Selective back-breeding" },
          { label: "C", text: "Genome editing of a living relative" },
          { label: "D", text: "Captive breeding of surviving individuals" },
        ], answer: "A",
        explanation: "Paragraph B: cloning 'requires an intact cell nucleus' and is restricted to recently dead animals." },

      { number: 12, type: "fill-blank", prompt: "Reconstruction of an ancient genome requires a ___ sequence taken from a living relative.",
        instruction: "Complete the sentences with ONE WORD ONLY from the passage.",
        answer: "reference",
        explanation: "Paragraph D: reconstruction 'requires a reference sequence from a living relative'." },
      { number: 13, type: "fill-blank", prompt: "Northern steppe grazers helped keep the ___ colder by trampling snow.",
        answer: "permafrost",
        explanation: "Paragraph C: trampling snow 'kept the permafrost colder'." },
      { number: 14, type: "mcq-multi", prompt: "Which TWO difficulties does the writer identify for a mammoth cloning attempt specifically?",
        instruction: "Choose TWO letters, A-E.",
        options: [
          "A. The long gestation period of the surrogate species",
          "B. The poor captive breeding record of Asian elephants",
          "C. A shortage of private funding",
          "D. Legal classification as a modified organism",
          "E. Public opposition to zoos",
        ],
        answers: ["A", "B"], answer: "A",
        explanation: "Paragraph D names the twenty-two-month pregnancy and the poor captive breeding record; the other options belong to different paragraphs or are absent." },
    ],
  },
];
