/**
 * @file swedishExampleNormalizer.ts
 * @description Generates natural, A1-friendly bilingual example sentences for
 *              Swedish vocabulary entries. Uses category + part-of-speech aware
 *              templates with deterministic per-word rotation so learners see
 *              varied, contextual examples instead of robotic auto-generated
 *              ones. Manually curated examples (non-generic) are preserved.
 * @copyright 2026 HaiEduTech, ILC. All rights reserved.
 */
import type { SwedishWord } from "./swedishVocabBank";

/* --------------------------- detection helpers --------------------------- */

const GENERIC_SV = [
  /^Jag gillar /,
  /^Jag vill /,
  /^Det är /,
  /^Hon arbetar /,
  /^Jag har \S+ vänner\./,
  /^Ordet ['"].+?['"] betyder /,
  /^(Verbet|Adjektivet|Adverbet|Uttrycket|Bindeordet|Prepositionen|Pronomenet|Talet) ['"]/,
];

const AWKWARD_EN = [
  /\bI want to (can|must|want|need|will|may|shall)\b/i,
  /\bI like (face|arm|shoulder|leg|finger|foot|throat|hand|head|hair|knee|stomach|mouth|nose|back|tooth|eye|ear)\b/i,
  /\bShe works (everyone|everything|also|to the right|to the left|straight ahead)\b/i,
  /\bIt is (old|new|clean|dirty|fast|slow|early|late)\b/i,
  /\bThe (verb|adjective|adverb|phrase|conjunction|preposition|pronoun|number|word) ['"]/i,
];

const AWKWARD_VI = [
  /Tôi muốn (có thể|phải|muốn|cần|sẽ)\.?$/i,
  /Cô ấy làm việc (tất cả|cũng|sang phải|sang trái|đi thẳng)\.?$/i,
  /Nó (cũ|mới|sạch|bẩn|nhanh|chậm|sớm|muộn)\.?$/i,
  /^(Động từ|Tính từ|Trạng từ|Cụm từ|Liên từ|Giới từ|Đại từ|Số|Từ) ['"]/i,
];

function isAutoGenerated(word: SwedishWord): boolean {
  const sv = (word.example || "").trim();
  const en = (word.exampleEn || "").trim();
  const vi = (word.exampleVi || "").trim();
  return (
    GENERIC_SV.some((r) => r.test(sv)) ||
    AWKWARD_EN.some((r) => r.test(en)) ||
    AWKWARD_VI.some((r) => r.test(vi))
  );
}

/* ------------------------------- utilities ------------------------------- */

const clean = (v: string) => (v || "").replace(/["“”]/g, "'").trim();

function hash(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h);
}

function pick<T>(arr: T[], seed: string): T {
  return arr[hash(seed) % arr.length];
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function stripTo(s: string): string {
  return s.replace(/^to\s+/i, "");
}

/* -------------------------- template definitions ------------------------- */

type Tmpl = { sv: string; vi: string; en: string };

/** Placeholders: {W}=Swedish word, {VI}=Vietnamese meaning, {EN}=English meaning,
 *  {ART}=en/ett article (with trailing space), {ARTVI}=một/ (VI indefinite),
 *  {ARTEN}=a / an / (EN indefinite),
 *  {MIN}/{SIN}/{NY}/{VIKTIG}/{VACKER}=adjective/possessive that agrees with en/ett gender. */

const NOUN_TEMPLATES: Record<string, Tmpl[]> = {
  food: [
    { sv: "Jag äter {ART}{W} till frukost.", vi: "Tôi ăn {ARTVI}{VI} vào bữa sáng.", en: "I eat {ARTEN}{EN} for breakfast." },
    { sv: "Vill du ha {ART}{W}?", vi: "Bạn có muốn {ARTVI}{VI} không?", en: "Would you like {ARTEN}{EN}?" },
    { sv: "Jag tycker om {W}.", vi: "Tôi thích {VI}.", en: "I like {EN}." },
  ],
  body: [
    { sv: "{MIN_C} {W} gör ont idag.", vi: "{VI_C} của tôi hôm nay bị đau.", en: "My {EN} hurts today." },
    { sv: "Hon pekar på {SIN} {W}.", vi: "Cô ấy chỉ vào {VI} của mình.", en: "She points at her {EN}." },
    { sv: "Barnet rör vid {SIN} {W}.", vi: "Đứa trẻ chạm vào {VI} của mình.", en: "The child touches its {EN}." },
  ],
  clothing: [
    { sv: "Hon har {ART}{W} på sig.", vi: "Cô ấy đang mặc {ARTVI}{VI}.", en: "She is wearing {ARTEN}{EN}." },
    { sv: "Jag köper {ART}{NY} {W}.", vi: "Tôi mua {ARTVI}{VI} mới.", en: "I am buying a new {EN}." },
    { sv: "{MIN_C} {W} är blå.", vi: "{VI_C} của tôi màu xanh.", en: "My {EN} is blue." },
  ],
  home: [
    { sv: "Vi har {ART}{W} hemma.", vi: "Chúng tôi có {ARTVI}{VI} ở nhà.", en: "We have {ARTEN}{EN} at home." },
    { sv: "{ART_C}{W} står i köket.", vi: "{ARTVI_C}{VI} ở trong bếp.", en: "The {EN} is in the kitchen." },
    { sv: "Jag städar {MIN} {W} varje vecka.", vi: "Tôi dọn {VI} của mình mỗi tuần.", en: "I clean my {EN} every week." },
  ],
  transport: [
    { sv: "Jag tar {ART}{W} till jobbet.", vi: "Tôi đi {ARTVI}{VI} đến chỗ làm.", en: "I take {ARTEN}{EN} to work." },
    { sv: "{ART_C}{W} kommer klockan åtta.", vi: "{ARTVI_C}{VI} đến lúc tám giờ.", en: "The {EN} arrives at eight o'clock." },
    { sv: "Det står {ART}{W} på gatan.", vi: "Có {ARTVI}{VI} trên đường.", en: "There is {ARTEN}{EN} on the street." },
  ],
  nature: [
    { sv: "Det finns {ART}{W} i parken.", vi: "Có {ARTVI}{VI} trong công viên.", en: "There is {ARTEN}{EN} in the park." },
    { sv: "Vi ser {ART}{W} i skogen.", vi: "Chúng tôi thấy {ARTVI}{VI} trong rừng.", en: "We see {ARTEN}{EN} in the forest." },
    { sv: "Jag tycker mycket om {W}.", vi: "Tôi rất thích {VI}.", en: "I like {EN} very much." },
  ],
  weather: [
    { sv: "Idag har vi {W}.", vi: "Hôm nay chúng ta có {VI}.", en: "Today we have {EN}." },
    { sv: "Jag tycker om {W}.", vi: "Tôi thích {VI}.", en: "I like {EN}." },
    { sv: "I morgon kommer {W}.", vi: "Ngày mai sẽ có {VI}.", en: "Tomorrow there will be {EN}." },
  ],
  tech: [
    { sv: "Jag använder {ART}{W} varje dag.", vi: "Tôi dùng {ARTVI}{VI} mỗi ngày.", en: "I use {ARTEN}{EN} every day." },
    { sv: "{MIN_C} {W} är {NY}.", vi: "{VI_C} của tôi mới.", en: "My {EN} is new." },
    { sv: "Han köper {ART}{W} online.", vi: "Anh ấy mua {ARTVI}{VI} trên mạng.", en: "He buys {ARTEN}{EN} online." },
  ],
  shopping: [
    { sv: "Jag går till {ART}{W} på lördag.", vi: "Tôi đi đến {ARTVI}{VI} vào thứ bảy.", en: "I go to {ARTEN}{EN} on Saturday." },
    { sv: "Det här är {ART}stor{ETT} {W}.", vi: "Đây là {ARTVI}{VI} lớn.", en: "This is a big {EN}." },
    { sv: "Jag behöver {ART}{W}.", vi: "Tôi cần {ARTVI}{VI}.", en: "I need {ARTEN}{EN}." },
  ],
  education: [
    { sv: "Vi lär oss om {W} i skolan.", vi: "Chúng tôi học về {VI} ở trường.", en: "We learn about {EN} at school." },
    { sv: "{MIN_C} {W} är intressant.", vi: "{VI_C} của tôi rất thú vị.", en: "My {EN} is interesting." },
    { sv: "Läraren förklarar {W}.", vi: "Giáo viên giải thích {VI}.", en: "The teacher explains {EN}." },
  ],
  work: [
    { sv: "Hon arbetar som {W}.", vi: "Cô ấy làm nghề {VI}.", en: "She works as {ARTEN}{EN}." },
    { sv: "Jag träffar {ART}{W} på kontoret.", vi: "Tôi gặp {ARTVI}{VI} ở văn phòng.", en: "I meet {ARTEN}{EN} at the office." },
    { sv: "Vi behöver {ART}{W} i teamet.", vi: "Chúng tôi cần {ARTVI}{VI} trong đội.", en: "We need {ARTEN}{EN} on the team." },
  ],
  family: [
    { sv: "{MIN_C} {W} bor i Sverige.", vi: "{VI_C} của tôi sống ở Thụy Điển.", en: "My {EN} lives in Sweden." },
    { sv: "Jag älskar {MIN} {W}.", vi: "Tôi yêu {VI} của tôi.", en: "I love my {EN}." },
    { sv: "Hennes {W} heter Anna.", vi: "{VI_C} của cô ấy tên là Anna.", en: "Her {EN} is named Anna." },
  ],
  numbers: [
    { sv: "Jag har {W} möten idag.", vi: "Hôm nay tôi có {VI} cuộc họp.", en: "I have {EN} meetings today." },
    { sv: "Vi ses snart igen.", vi: "Hẹn gặp lại sớm.", en: "See you again soon." },
    { sv: "Ordet '{W}' används ofta i vardagen.", vi: "Từ '{VI}' được dùng thường xuyên trong cuộc sống.", en: "The word '{EN}' is often used in daily life." },
  ],
  abstract: [
    { sv: "{W_C} är viktig{ETT} i livet.", vi: "{VI_C} rất quan trọng trong cuộc sống.", en: "{EN_C} is important in life." },
    { sv: "Vi pratar om {W}.", vi: "Chúng tôi nói về {VI}.", en: "We talk about {EN}." },
    { sv: "Hon tänker på {SIN} {W}.", vi: "Cô ấy nghĩ về {VI} của mình.", en: "She thinks about her {EN}." },
  ],
  society: [
    { sv: "Vi diskuterar {W} i klassen.", vi: "Chúng tôi thảo luận về {VI} ở lớp.", en: "We discuss {EN} in class." },
    { sv: "{W_C} är viktig{ETT} för alla.", vi: "{VI_C} quan trọng với mọi người.", en: "{EN_C} is important for everyone." },
    { sv: "Jag läser om {W} i tidningen.", vi: "Tôi đọc về {VI} trên báo.", en: "I read about {EN} in the newspaper." },
  ],
  environment: [
    { sv: "{W_C} finns överallt i naturen.", vi: "{VI_C} có ở khắp nơi trong tự nhiên.", en: "{EN_C} is found everywhere in nature." },
    { sv: "Vi måste skydda {W}.", vi: "Chúng ta phải bảo vệ {VI}.", en: "We must protect {EN}." },
    { sv: "{W_C} är viktig{ETT} för jorden.", vi: "{VI_C} rất quan trọng với trái đất.", en: "{EN_C} is important for the earth." },
  ],
  hobbies: [
    { sv: "Jag gillar {W} på fritiden.", vi: "Tôi thích {VI} vào lúc rảnh.", en: "I enjoy {EN} in my free time." },
    { sv: "Hon spelar {W} med vänner.", vi: "Cô ấy chơi {VI} với bạn bè.", en: "She plays {EN} with friends." },
    { sv: "Vi övar {W} varje vecka.", vi: "Chúng tôi luyện {VI} mỗi tuần.", en: "We practice {EN} every week." },
  ],
  default: [
    { sv: "Det här är {ART}{W}.", vi: "Đây là {ARTVI}{VI}.", en: "This is {ARTEN}{EN}." },
    { sv: "Jag ser {ART}{W} där.", vi: "Tôi thấy {ARTVI}{VI} ở đó.", en: "I see {ARTEN}{EN} over there." },
    { sv: "Vi har {ART}{W} här.", vi: "Chúng tôi có {ARTVI}{VI} ở đây.", en: "We have {ARTEN}{EN} here." },
  ],
};

const VERB_TEMPLATES: Tmpl[] = [
  { sv: "Det är viktigt att {W}.", vi: "Việc {VI} rất quan trọng.", en: "It is important to {EN}." },
  { sv: "Det är bra att {W} ofta.", vi: "Thường xuyên {VI} là điều tốt.", en: "It is good to {EN} often." },
  { sv: "Jag lär mig att {W} på svenska.", vi: "Tôi đang học cách {VI} bằng tiếng Thụy Điển.", en: "I am learning to {EN} in Swedish." },
  { sv: "På helgen brukar vi {W} tillsammans.", vi: "Cuối tuần chúng tôi thường {VI} cùng nhau.", en: "On weekends we usually {EN} together." },
];

const ADJ_TEMPLATES: Tmpl[] = [
  { sv: "Huset är {W}.", vi: "Ngôi nhà thì {VI}.", en: "The house is {EN}." },
  { sv: "Boken är mycket {W}.", vi: "Quyển sách rất {VI}.", en: "The book is very {EN}." },
  { sv: "Maten är {W} idag.", vi: "Hôm nay đồ ăn thì {VI}.", en: "The food is {EN} today." },
  { sv: "Min vän är {W}.", vi: "Bạn của tôi thì {VI}.", en: "My friend is {EN}." },
  { sv: "Vädret är {W} på morgonen.", vi: "Buổi sáng thời tiết thì {VI}.", en: "The weather is {EN} in the morning." },
];

const ADV_TEMPLATES: Tmpl[] = [
  { sv: "Hon gör det {W}.", vi: "Cô ấy làm điều đó một cách {VI}.", en: "She does it {EN}." },
  { sv: "Han pratar svenska {W}.", vi: "Anh ấy nói tiếng Thụy Điển {VI}.", en: "He speaks Swedish {EN}." },
  { sv: "Vi arbetar {W} på kontoret.", vi: "Chúng tôi làm việc {VI} ở văn phòng.", en: "We work {EN} at the office." },
];

const PREP_TEMPLATES: Tmpl[] = [
  { sv: "Boken ligger {W} bordet.", vi: "Quyển sách ở {VI} cái bàn.", en: "The book is {EN} the table." },
  { sv: "Vi går {W} skolan.", vi: "Chúng tôi đi {VI} trường.", en: "We go {EN} the school." },
];

const CONJ_TEMPLATES: Tmpl[] = [
  { sv: "Jag gillar te {W} jag gillar kaffe.", vi: "Tôi thích trà {VI} tôi thích cà phê.", en: "I like tea {EN} I like coffee." },
  { sv: "Hon stannar hemma {W} det regnar.", vi: "Cô ấy ở nhà {VI} trời mưa.", en: "She stays home {EN} it rains." },
];

/* --------------------------- article helpers ----------------------------- */

function artSV(word: SwedishWord): { full: string; capWord: string } {
  const a = word.article;
  if (a === "en") return { full: "en ", capWord: "En " };
  if (a === "ett") return { full: "ett ", capWord: "Ett " };
  return { full: "", capWord: "" };
}

function artVI(word: SwedishWord): { full: string; capWord: string } {
  if (word.article) return { full: "một ", capWord: "Một " };
  return { full: "", capWord: "" };
}

function artEN(en: string): { full: string; capWord: string } {
  const word = stripTo(en).trim();
  if (!word) return { full: "", capWord: "" };
  const useAn = /^[aeiouAEIOU]/.test(word);
  return useAn
    ? { full: "an ", capWord: "An " }
    : { full: "a ", capWord: "A " };
}

function fill(tmpl: Tmpl, w: SwedishWord): Tmpl {
  const W = clean(w.sv);
  const VI = clean(w.vi);
  const EN = stripTo(clean(w.en));
  const aSV = artSV(w);
  const aVI = artVI(w);
  const aEN = artEN(w.en);

  const replaceAll = (str: string, find: string, repl: string) =>
    str.split(find).join(repl);

  const sub = (s: string) => {
    let r = s;
    r = replaceAll(r, "{ART_C}", aSV.capWord);
    r = replaceAll(r, "{ART}", aSV.full);
    r = replaceAll(r, "{ARTVI_C}", aVI.capWord);
    r = replaceAll(r, "{ARTVI}", aVI.full);
    r = replaceAll(r, "{ARTEN}", aEN.full);
    r = replaceAll(r, "{W_C}", cap(W));
    r = replaceAll(r, "{W}", W);
    r = replaceAll(r, "{VI_C}", cap(VI));
    r = replaceAll(r, "{VI}", VI);
    r = replaceAll(r, "{EN_C}", cap(EN));
    r = replaceAll(r, "{EN}", EN);
    return r;
  };

  return { sv: sub(tmpl.sv), vi: sub(tmpl.vi), en: sub(tmpl.en) };
}

/* ------------------------ main normalization ----------------------------- */

function templatesFor(word: SwedishWord): Tmpl[] {
  const pos = word.pos.toLowerCase();
  if (pos.startsWith("v")) return VERB_TEMPLATES;
  if (pos.startsWith("adj")) return ADJ_TEMPLATES;
  if (pos.startsWith("adv")) return ADV_TEMPLATES;
  if (pos.startsWith("prep")) return PREP_TEMPLATES;
  if (pos.startsWith("conj")) return CONJ_TEMPLATES;
  // nouns, phrases, pronouns, numerals → noun-style by category
  const cat = (word.category || "default").toLowerCase();
  return NOUN_TEMPLATES[cat] || NOUN_TEMPLATES.default;
}

/** IDs of entries with hand-curated examples — preserved as-is. */
const CURATED_IDS = new Set<string>([
  "m802", "m751", "m750", "m706", "m356", "m24", "m77", "mm646", "mm641",
]);

// Exposed for potential future QA tooling.
export { isAutoGenerated };

export function normalizeSwedishWordExamples(word: SwedishWord): SwedishWord {
  if (CURATED_IDS.has(word.id)) return word;

  const tmpls = templatesFor(word);
  const chosen = pick(tmpls, `${word.id}|${word.sv}`);
  const filled = fill(chosen, word);

  return {
    ...word,
    example: filled.sv,
    exampleVi: filled.vi,
    exampleEn: filled.en,
  };
}
