/**
 * @file swedishExampleNormalizer.ts
 * @description Generates natural, A1-friendly bilingual example sentences for
 *              Swedish vocabulary entries. Uses category + part-of-speech aware
 *              templates with deterministic per-word rotation so learners see
 *              varied, contextual examples instead of robotic auto-generated
 *              ones. Manually curated examples (non-generic) are preserved.
 * @copyright 2026 HaiEduTech, ILC. All rights reserved.
 */
import type { SwedishWord } from "./swedishVocabBank";
import { getSwedishExampleOverride } from "./swedishExampleOverrides";

/* --------------------------- detection helpers --------------------------- */

const GENERIC_SV = [
  /^Jag gillar /,
  /^Jag vill /,
  /^Det är /,
  /^Hon arbetar /,
  /^Jag har \S+ vänner\./,
  /^Ordet ['"].+?['"] betyder /,
  /^(Verbet|Adjektivet|Adverbet|Uttrycket|Bindeordet|Prepositionen|Pronomenet|Talet) ['"]/,
];

const AWKWARD_EN = [
  /\bI want to (can|must|want|need|will|may|shall)\b/i,
  /\bI like (face|arm|shoulder|leg|finger|foot|throat|hand|head|hair|knee|stomach|mouth|nose|back|tooth|eye|ear)\b/i,
  /\bShe works (everyone|everything|also|to the right|to the left|straight ahead)\b/i,
  /\bIt is (old|new|clean|dirty|fast|slow|early|late)\b/i,
  /\bThe (verb|adjective|adverb|phrase|conjunction|preposition|pronoun|number|word) ['"]/i,
];

const AWKWARD_VI = [
  /Tôi muốn (có thể|phải|muốn|cần|sẽ)\.?$/i,
  /Cô ấy làm việc (tất cả|cũng|sang phải|sang trái|đi thẳng)\.?$/i,
  /Nó (cũ|mới|sạch|bẩn|nhanh|chậm|sớm|muộn)\.?$/i,
  /^(Động từ|Tính từ|Trạng từ|Cụm từ|Liên từ|Giới từ|Đại từ|Số|Từ) ['"]/i,
];

function isAutoGenerated(word: SwedishWord): boolean {
  const sv = (word.example || "").trim();
  const en = (word.exampleEn || "").trim();
  const vi = (word.exampleVi || "").trim();
  return (
    GENERIC_SV.some((r) => r.test(sv)) ||
    AWKWARD_EN.some((r) => r.test(en)) ||
    AWKWARD_VI.some((r) => r.test(vi))
  );
}

/* ------------------------------- utilities ------------------------------- */

const clean = (v: string) => (v || "").replace(/["“”]/g, "'").trim();

function hash(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h);
}

function pick<T>(arr: T[], seed: string): T {
  return arr[hash(seed) % arr.length];
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function stripTo(s: string): string {
  return s.replace(/^to\s+/i, "");
}

/* -------------------------- template definitions ------------------------- */

type Tmpl = { sv: string; vi: string; en: string };

/** Placeholders: {W}=Swedish word, {VI}=Vietnamese meaning, {EN}=English meaning,
 *  {ART}=en/ett article (with trailing space), {ARTVI}=một/ (VI indefinite),
 *  {ARTEN}=a / an / (EN indefinite),
 *  {MIN}/{SIN}/{NY}/{VIKTIG}/{VACKER}=adjective/possessive that agrees with en/ett gender. */

const NOUN_TEMPLATES: Record<string, Tmpl[]> = {
  food: [
    { sv: "Jag äter {ART}{W} till frukost.", vi: "Tôi ăn {ARTVI}{VI} vào bữa sáng.", en: "I eat {ARTEN}{EN} for breakfast." },
    { sv: "Vill du ha {ART}{W}?", vi: "Bạn có muốn {ARTVI}{VI} không?", en: "Would you like {ARTEN}{EN}?" },
    { sv: "Jag tycker om {W}.", vi: "Tôi thích {VI}.", en: "I like {EN}." },
  ],
  body: [
    { sv: "Jag har ont i {MIN} {W} idag.", vi: "Hôm nay tôi bị đau ở {VI}.", en: "I have pain in my {EN} today." },
    { sv: "Han rör vid {SIN} {W} försiktigt.", vi: "Anh ấy chạm nhẹ vào {VI} của mình.", en: "He touches his {EN} carefully." },
    { sv: "Läkaren undersöker {MIN} {W}.", vi: "Bác sĩ khám {VI} của tôi.", en: "The doctor examines my {EN}." },
  ],
  clothing: [
    { sv: "Hon har {ART}{W} på sig.", vi: "Cô ấy đang mặc {ARTVI}{VI}.", en: "She is wearing {ARTEN}{EN}." },
    { sv: "Jag köper {ART}{NY} {W}.", vi: "Tôi mua {ARTVI}{VI} mới.", en: "I am buying a new {EN}." },
    { sv: "{MIN_C} {W} är fin{ETT}.", vi: "{VI_C} của tôi rất đẹp.", en: "My {EN} is nice." },
  ],
  home: [
    { sv: "Jag lär mig ordet '{W}' i dag.", vi: "Hôm nay tôi học từ '{W}'.", en: "I am learning the word '{W}' today." },
    { sv: "Skriv ordet '{W}' i ordlistan.", vi: "Hãy ghi từ '{W}' vào danh sách từ vựng.", en: "Write the word '{W}' in the vocabulary list." },
    { sv: "Läraren ger ett exempel med ordet '{W}'.", vi: "Giáo viên đưa ra một ví dụ với từ '{W}'.", en: "The teacher gives an example with the word '{W}'." },
  ],
  transport: [
    { sv: "Jag tar {ART}{W} till jobbet.", vi: "Tôi đi {ARTVI}{VI} đến chỗ làm.", en: "I take {ARTEN}{EN} to work." },
    { sv: "{ART_C}{W} kommer klockan åtta.", vi: "{ARTVI_C}{VI} đến lúc tám giờ.", en: "The {EN} arrives at eight o'clock." },
    { sv: "Det står {ART}{W} på gatan.", vi: "Có {ARTVI}{VI} trên đường.", en: "There is {ARTEN}{EN} on the street." },
  ],
  nature: [
    { sv: "I skogen ser vi {ART}{W} på nära håll.", vi: "Trong rừng chúng tôi nhìn thấy {ARTVI}{VI} ở gần.", en: "In the forest we see {ARTEN}{EN} up close." },
    { sv: "Barnen tycker om att titta på {W} i naturen.", vi: "Bọn trẻ thích ngắm {VI} trong thiên nhiên.", en: "The children like watching {EN} in nature." },
    { sv: "Vi tar en bild av {ART}{W} på promenaden.", vi: "Chúng tôi chụp ảnh {ARTVI}{VI} khi đi dạo.", en: "We take a picture of the {EN} on our walk." },
  ],
  weather: [
    { sv: "I dag har vi {W} i Stockholm.", vi: "Hôm nay ở Stockholm có {VI}.", en: "Today we have {EN} in Stockholm." },
    { sv: "På hösten kommer det ofta {W}.", vi: "Vào mùa thu thường có {VI}.", en: "In autumn there is often {EN}." },
    { sv: "Ta med paraply om det blir {W}.", vi: "Nhớ mang ô nếu có {VI}.", en: "Bring an umbrella if there is {EN}." },
  ],
  tech: [
    { sv: "Ordet '{W}' är vanligt när vi pratar om teknik.", vi: "Từ '{W}' thường gặp khi nói về công nghệ.", en: "The word '{W}' is common when we talk about technology." },
    { sv: "På jobbet behöver vi förstå {W}.", vi: "Ở chỗ làm chúng tôi cần hiểu về {VI}.", en: "At work we need to understand {EN}." },
    { sv: "Läraren förklarar {W} på datorkursen.", vi: "Giáo viên giải thích {VI} trong khoá máy tính.", en: "The teacher explains {EN} in the computer course." },
  ],
  shopping: [
    { sv: "Jag skriver {W} på inköpslistan.", vi: "Tôi ghi {VI} vào danh sách mua sắm.", en: "I write {EN} on the shopping list." },
    { sv: "Vi letar efter {W} i affären.", vi: "Chúng tôi tìm {VI} trong cửa hàng.", en: "We look for {EN} in the shop." },
    { sv: "Jag behöver {ART}{W} i veckan.", vi: "Tuần này tôi cần {ARTVI}{VI}.", en: "I need {ARTEN}{EN} this week." },
  ],
  education: [
    { sv: "På lektionen pratar vi om {W}.", vi: "Trong tiết học chúng tôi nói về {VI}.", en: "In the lesson we talk about {EN}." },
    { sv: "Läraren skriver ordet '{W}' på tavlan.", vi: "Giáo viên viết từ '{W}' lên bảng.", en: "The teacher writes the word '{W}' on the board." },
    { sv: "Eleverna använder {W} i en skoluppgift.", vi: "Học sinh dùng {VI} trong một bài tập ở trường.", en: "The pupils use {EN} in a school assignment." },
  ],
  work: [
    { sv: "Vi pratar om {W} på jobbet.", vi: "Chúng tôi nói về {VI} ở chỗ làm.", en: "We talk about {EN} at work." },
    { sv: "{W_C} är viktig{ETT} i mitt arbete.", vi: "{VI_C} rất quan trọng trong công việc của tôi.", en: "{EN_C} is important in my work." },
    { sv: "På kontoret hör jag ofta ordet '{W}'.", vi: "Ở văn phòng tôi thường nghe từ '{W}' (nghĩa là {VI}).", en: "At the office I often hear the word '{W}' (meaning '{EN}')." },
  ],
  family: [
    { sv: "{MIN_C} {W} bor i Sverige.", vi: "{VI_C} của tôi sống ở Thụy Điển.", en: "My {EN} lives in Sweden." },
    { sv: "Jag älskar {MIN} {W}.", vi: "Tôi yêu {VI} của mình.", en: "I love my {EN}." },
    { sv: "Jag pratar ofta med {MIN} {W}.", vi: "Tôi thường nói chuyện với {VI} của mình.", en: "I often talk with my {EN}." },
  ],
  numbers: [
    { sv: "I uppgiften använder vi ordet '{W}'.", vi: "Trong bài tập, chúng tôi dùng từ '{W}'.", en: "In the exercise, we use the word '{W}'." },
    { sv: "Läraren skriver '{W}' på tavlan.", vi: "Giáo viên viết '{W}' lên bảng.", en: "The teacher writes '{W}' on the board." },
    { sv: "Kan du säga '{W}' på svenska?", vi: "Bạn có thể nói '{W}' bằng tiếng Thụy Điển không?", en: "Can you say '{W}' in Swedish?" },
  ],
  abstract: [
    { sv: "I texten används ordet '{W}' i ett tydligt sammanhang.", vi: "Trong bài đọc, từ '{W}' được dùng trong một ngữ cảnh rõ ràng.", en: "In the text, the word '{W}' is used in a clear context." },
    { sv: "Vi diskuterar {W} på ett tydligt sätt.", vi: "Chúng tôi thảo luận về {VI} một cách rõ ràng.", en: "We discuss {EN} in a clear way." },
    { sv: "Det är viktigt att förstå {W} i sammanhanget.", vi: "Điều quan trọng là hiểu {VI} trong ngữ cảnh.", en: "It is important to understand {EN} in context." },
  ],
  society: [
    { sv: "I nyheterna nämns {W} ofta.", vi: "Trong tin tức thường nhắc đến {VI}.", en: "The news often mentions {EN}." },
    { sv: "På samhällskunskapen pratar vi om {W}.", vi: "Trong môn xã hội học chúng tôi nói về {VI}.", en: "In civics class we talk about {EN}." },
    { sv: "Artikeln förklarar {W} med enkla ord.", vi: "Bài báo giải thích {VI} bằng từ ngữ đơn giản.", en: "The article explains {EN} in simple words." },
  ],
  environment: [
    { sv: "{W_C} finns överallt i naturen.", vi: "{VI_C} có ở khắp nơi trong tự nhiên.", en: "{EN_C} is found everywhere in nature." },
    { sv: "Vi måste skydda {W}.", vi: "Chúng ta phải bảo vệ {VI}.", en: "We must protect {EN}." },
    { sv: "{W_C} är viktig{ETT} för jorden.", vi: "{VI_C} rất quan trọng với trái đất.", en: "{EN_C} is important for the earth." },
  ],
  hobbies: [
    { sv: "På fritiden pratar vi om {W}.", vi: "Lúc rảnh chúng tôi nói về {VI}.", en: "In our free time, we talk about {EN}." },
    { sv: "I hobbygruppen lär vi oss ordet '{W}'.", vi: "Trong nhóm sở thích, chúng tôi học từ '{W}'.", en: "In the hobby group, we learn the word '{W}'." },
    { sv: "Läraren ger ett exempel med ordet '{W}'.", vi: "Giáo viên đưa ra một ví dụ với từ '{W}'.", en: "The teacher gives an example with the word '{W}'." },
  ],
  directions: [
    { sv: "Ursäkta, var ligger {ART}{W}?",              vi: "Xin lỗi, {ARTVI}{VI} nằm ở đâu?",              en: "Excuse me, where is the {EN}?" },
    { sv: "Vi tar {ART}{W} till centrum.",              vi: "Chúng tôi đi {ARTVI}{VI} vào trung tâm.",       en: "We take {ARTEN}{EN} to the city center." },
    { sv: "Kan du visa {ART}{W} på kartan?",            vi: "Bạn có thể chỉ {ARTVI}{VI} trên bản đồ không?", en: "Can you show me the {EN} on the map?" },
  ],
  travel: [
    { sv: "Vi pratar om {W} inför resan.",              vi: "Chúng tôi nói về {VI} trước chuyến đi.",         en: "We talk about {EN} before the trip." },
    { sv: "I kursen om resor och kultur lär vi oss ordet '{W}'.", vi: "Trong khoá học về du lịch và văn hoá, chúng tôi học từ '{W}'.", en: "In the course about travel and culture, we learn the word '{W}'." },
    { sv: "Skriv '{W}' i ordlistan inför resan.",       vi: "Hãy ghi '{W}' vào danh sách từ vựng trước chuyến đi.", en: "Write '{W}' in the vocabulary list before the trip." },
  ],
  health: [
    { sv: "Läkaren pratar om {W} med patienten.",       vi: "Bác sĩ nói về {VI} với bệnh nhân.",             en: "The doctor talks about {EN} with the patient." },
    { sv: "När vi pratar om hälsa nämner vi {W}.",      vi: "Khi nói về sức khỏe, chúng tôi nhắc đến {VI}.",  en: "When we talk about health, we mention {EN}." },
    { sv: "Tidningen skriver om {W} idag.",             vi: "Báo hôm nay viết về {VI}.",                      en: "The newspaper writes about {EN} today." },
  ],
  emotions: [
    { sv: "Hon känner mycket {W} idag.", vi: "Hôm nay cô ấy cảm thấy nhiều {VI}.", en: "She feels a lot of {EN} today." },
    { sv: "{W_C} är en naturlig del av livet.", vi: "{VI_C} là một phần tự nhiên của cuộc sống.", en: "{EN_C} is a natural part of life." },
    { sv: "Filmen väckte mycket {W} hos publiken.", vi: "Bộ phim khơi gợi nhiều {VI} nơi khán giả.", en: "The film stirred a lot of {EN} in the audience." },
  ],
  opinion: [
    { sv: "I en diskussion använder jag ordet '{W}'.",  vi: "Trong một cuộc thảo luận, tôi dùng từ '{W}'.",  en: "In a discussion, I use the word '{W}'." },
    { sv: "Frågan handlar om {W}.",                     vi: "Câu hỏi nói về {VI}.",                         en: "The question is about {EN}." },
    { sv: "Vi förklarar {W} med ett enkelt exempel.",   vi: "Chúng tôi giải thích {VI} bằng một ví dụ đơn giản.", en: "We explain {EN} with a simple example." },
  ],
  daily: [
    { sv: "Jag använder uttrycket '{W}' i vardagen.",   vi: "Tôi dùng cụm '{W}' trong đời sống hằng ngày.",   en: "I use the expression '{W}' in daily life." },
    { sv: "På morgonen passar uttrycket '{W}' bra.",    vi: "Vào buổi sáng, cụm '{W}' rất phù hợp.",          en: "In the morning, the expression '{W}' fits well." },
    { sv: "Vi övar på frasen '{W}' tillsammans.",       vi: "Chúng tôi cùng luyện cụm '{W}'.",                en: "We practise the phrase '{W}' together." },
  ],
  greetings: [
    { sv: "På svenska säger vi '{W}' när vi träffas.",  vi: "Trong tiếng Thụy Điển ta nói '{W}' khi gặp nhau (nghĩa là {VI}).", en: "In Swedish we say '{W}' when we meet (meaning '{EN}')." },
    { sv: "Han sa '{W}' med ett leende.",               vi: "Anh ấy nói '{W}' với một nụ cười.",              en: "He said '{W}' with a smile." },
  ],
  default: [
    { sv: "Jag lär mig ordet '{W}' i dag.", vi: "Hôm nay tôi học từ '{W}'.", en: "I am learning the word '{W}' today." },
    { sv: "Läraren förklarar ordet '{W}'.", vi: "Giáo viên giải thích từ '{W}'.", en: "The teacher explains the word '{W}'." },
    { sv: "Skriv ordet '{W}' i anteckningsboken.", vi: "Hãy ghi từ '{W}' vào vở ghi chú.", en: "Write the word '{W}' in the notebook." },
  ],
};

// Category aliases → point synonym keys at existing template buckets.
const CATEGORY_ALIAS: Record<string, string> = {
  technology: "tech",
  tech_devices: "tech",
  transportation: "transport",
  house: "home",
  living: "home",
  jobs: "work",
  study: "education",
  school: "education",
  numbers_time: "numbers",
  time: "numbers",
  nature_weather: "nature",
};

// Verb templates use modal + infinitive so any Swedish infinitive fits
// grammatically and the sentence stays semantically natural.
const VERB_TEMPLATES: Tmpl[] = [
  { sv: "På lektionen övar vi ordet '{W}'.", vi: "Trong tiết học, chúng tôi luyện từ '{W}'.", en: "In the lesson, we practise the word '{W}'." },
  { sv: "Läraren visar ett exempel med '{W}'.", vi: "Giáo viên đưa ra một ví dụ với '{W}'.", en: "The teacher shows an example with '{W}'." },
  { sv: "Jag skriver '{W}' i min ordlista.", vi: "Tôi ghi '{W}' vào danh sách từ vựng của mình.", en: "I write '{W}' in my vocabulary list." },
];

const ADJ_TEMPLATES: Tmpl[] = [
  { sv: "Filmen vi såg i går var {W}.", vi: "Bộ phim chúng tôi xem hôm qua thật {VI}.", en: "The film we saw yesterday was {EN}." },
  { sv: "Boken jag läser är riktigt {W}.", vi: "Cuốn sách tôi đang đọc thật sự {VI}.", en: "The book I am reading is really {EN}." },
  { sv: "Vädret i dag känns {W}.", vi: "Thời tiết hôm nay có cảm giác {VI}.", en: "The weather today feels {EN}." },
];

const PHRASE_TEMPLATES: Tmpl[] = [
  { sv: "'{W}?' frågade han när jag kom hem.", vi: "'{W}?' anh ấy hỏi khi tôi về nhà.", en: "'{W}?' he asked when I got home." },
  { sv: "Hon log och sa: '{W}'.", vi: "Cô ấy mỉm cười và nói: '{W}'.", en: "She smiled and said: '{W}'." },
  { sv: "Vi använder '{W}' varje dag hemma.", vi: "Chúng tôi dùng cụm '{W}' mỗi ngày ở nhà.", en: "We use '{W}' every day at home." },
];

const NUMERAL_TEMPLATES: Tmpl[] = [
  { sv: "Jag har {W} böcker i väskan.", vi: "Tôi có {VI} cuốn sách trong túi.", en: "I have {EN} books in my bag." },
  { sv: "Vi är {W} personer i familjen.", vi: "Gia đình chúng tôi có {VI} người.", en: "We are {EN} people in the family." },
  { sv: "Kaffet kostar {W} kronor.", vi: "Cà phê giá {VI} kronor.", en: "The coffee costs {EN} kronor." },
];

const PRONOUN_TEMPLATES: Tmpl[] = [
  { sv: "'{W_C}' är ett vanligt ord i svenska samtal.", vi: "'{W_C}' là một từ thường gặp trong hội thoại tiếng Thụy Điển.", en: "'{W_C}' is a common word in Swedish conversations." },
  { sv: "Kan du säga '{W}' i en hel mening?", vi: "Bạn có thể dùng '{W}' trong một câu hoàn chỉnh không?", en: "Can you use '{W}' in a full sentence?" },
];

const ADV_TEMPLATES: Tmpl[] = [
  { sv: "På svenska använder vi ofta ordet '{W}'.", vi: "Trong tiếng Thụy Điển, chúng ta thường dùng từ '{W}'.", en: "In Swedish, we often use the word '{W}'." },
  { sv: "Han svarar med ordet '{W}' när det passar.", vi: "Anh ấy trả lời bằng từ '{W}' khi phù hợp.", en: "He answers with the word '{W}' when it fits." },
  { sv: "Ordet '{W}' används ofta i talat språk.", vi: "Từ '{W}' thường được dùng trong giao tiếp.", en: "The word '{W}' is often used in spoken language." },
];

const PREP_TEMPLATES: Tmpl[] = [
  { sv: "Prepositionen '{W}' står ofta före en plats.", vi: "Giới từ '{W}' thường đứng trước một địa điểm.", en: "The preposition '{W}' often comes before a place." },
  { sv: "Vi övar på prepositionen '{W}' i en mening.", vi: "Chúng ta luyện giới từ '{W}' trong một câu.", en: "We practise the preposition '{W}' in a sentence." },
];

const CONJ_TEMPLATES: Tmpl[] = [
  { sv: "Bindeordet '{W}' kopplar ihop två satser.", vi: "Liên từ '{W}' nối hai mệnh đề với nhau.", en: "The conjunction '{W}' links two clauses." },
  { sv: "Vi använder '{W}' i en längre mening.", vi: "Ta dùng '{W}' trong một câu dài hơn.", en: "We use '{W}' in a longer sentence." },
];

/* --------------------------- article helpers ----------------------------- */

function artSV(word: SwedishWord): { full: string; capWord: string } {
  const a = word.article;
  if (a === "en") return { full: "en ", capWord: "En " };
  if (a === "ett") return { full: "ett ", capWord: "Ett " };
  return { full: "", capWord: "" };
}

function artVI(word: SwedishWord): { full: string; capWord: string } {
  if (word.article) return { full: "một ", capWord: "Một " };
  return { full: "", capWord: "" };
}

function artEN(en: string): { full: string; capWord: string } {
  const word = stripTo(en).trim();
  if (!word) return { full: "", capWord: "" };
  const useAn = /^[aeiouAEIOU]/.test(word);
  return useAn
    ? { full: "an ", capWord: "An " }
    : { full: "a ", capWord: "A " };
}

function fill(tmpl: Tmpl, w: SwedishWord): Tmpl {
  const W = clean(w.sv);
  const VI = clean(w.vi);
  const EN = stripTo(clean(w.en));
  const aSV = artSV(w);
  const aVI = artVI(w);
  const aEN = artEN(w.en);

  const replaceAll = (str: string, find: string, repl: string) =>
    str.split(find).join(repl);

  const isEtt = w.article === "ett";
  const MIN = isEtt ? "mitt" : "min";
  const SIN = isEtt ? "sitt" : "sin";
  const NY = isEtt ? "nytt" : "ny";
  const ETT = isEtt ? "t" : "";

  const sub = (s: string) => {
    let r = s;
    r = replaceAll(r, "{ART_C}", aSV.capWord);
    r = replaceAll(r, "{ART}", aSV.full);
    r = replaceAll(r, "{ARTVI_C}", aVI.capWord);
    r = replaceAll(r, "{ARTVI}", aVI.full);
    r = replaceAll(r, "{ARTEN}", aEN.full);
    r = replaceAll(r, "{MIN_C}", cap(MIN));
    r = replaceAll(r, "{MIN}", MIN);
    r = replaceAll(r, "{SIN}", SIN);
    r = replaceAll(r, "{NY}", NY);
    r = replaceAll(r, "{ETT}", ETT);
    r = replaceAll(r, "{W_C}", cap(W));
    r = replaceAll(r, "{W}", W);
    r = replaceAll(r, "{VI_C}", cap(VI));
    r = replaceAll(r, "{VI}", VI);
    r = replaceAll(r, "{EN_C}", cap(EN));
    r = replaceAll(r, "{EN}", EN);
    return r;
  };

  return { sv: sub(tmpl.sv), vi: sub(tmpl.vi), en: sub(tmpl.en) };
}

/* ------------------------ main normalization ----------------------------- */

function templatesFor(word: SwedishWord): Tmpl[] {
  const pos = word.pos.toLowerCase();
  if (pos.startsWith("phr")) return PHRASE_TEMPLATES;
  if (pos.startsWith("num")) return NUMERAL_TEMPLATES;
  if (pos.startsWith("pron")) return PRONOUN_TEMPLATES;
  if (pos.startsWith("v")) return VERB_TEMPLATES;
  if (pos.startsWith("adj")) return ADJ_TEMPLATES;
  if (pos.startsWith("adv")) return ADV_TEMPLATES;
  if (pos.startsWith("prep")) return PREP_TEMPLATES;
  if (pos.startsWith("conj")) return CONJ_TEMPLATES;
  // nouns, phrases, pronouns, numerals → noun-style by category
  const rawCat = (word.category || "default").toLowerCase();
  const cat = CATEGORY_ALIAS[rawCat] || rawCat;
  return NOUN_TEMPLATES[cat] || NOUN_TEMPLATES.default;
}

/** IDs of entries with hand-curated examples — preserved as-is. */
const CURATED_IDS = new Set<string>([
  "m802", "m751", "m750", "m706", "m356", "m24", "m77", "mm646", "mm641",
]);

// Exposed for potential future QA tooling.
export { isAutoGenerated };

export function normalizeSwedishWordExamples(word: SwedishWord): SwedishWord {
  if (CURATED_IDS.has(word.id)) return word;

  // 1) Hand-curated per-word overrides take top priority — they guarantee a
  //    natural, semantically correct example for the most common A1 vocab.
  const override = getSwedishExampleOverride(word.sv);
  if (override) {
    return {
      ...word,
      example: override.sv,
      exampleVi: override.vi,
      exampleEn: override.en,
    };
  }

  // 2) Otherwise, fall back to category/POS-aware template generation.
  const tmpls = templatesFor(word);
  const chosen = pick(tmpls, `${word.id}|${word.sv}`);
  const filled = fill(chosen, word);

  return {
    ...word,
    example: filled.sv,
    exampleVi: filled.vi,
    exampleEn: filled.en,
  };
}
